// auto-generated 2026-06-23 17:35 IST
window.BRIEF = {
  "date": "Tuesday, 23 June 2026",
  "edition": "2026-06-23 17:35",
  "topline": "As Iran-US ceasefire talks accelerate with Hormuz's future uncertain, India faces pressure on multiple fronts — trade deal negotiations with Piyush Goyal meeting Greer in Washington, a crashing Sensex, slowing business activity, and a historic low in tech hiring.",
  "lensLabel": "Why it matters",
  "sections": [
    {
      "id": "world",
      "name": "World",
      "stories": [
        {
          "hour": 8,
          "time": "08:00 IST",
          "headline": "With Hormuz in flux, can Pakistan muscle in on India's dominant Basmati rice trade in the Middle East?",
          "what": "As the Strait of Hormuz's status remains uncertain following Iran's actions, a question is emerging for India's agricultural export economy: could Pakistan exploit any disruption to challenge India's commanding position in Basmati rice exports to the Middle East? India is the dominant supplier of Basmati to Gulf markets, but shipping slowdowns and route uncertainty could create an opening for rivals. The situation puts a premium export earner directly in the crossfire of geopolitical turbulence.",
          "lens": "Basmati rice is a billion-dollar export for India, and any erosion of its Gulf market share — which relies on Hormuz shipping lanes — would hurt Indian farmers and exporters directly.",
          "source": "India Today",
          "url": "https://news.google.com/rss/articles/CBMi3gFBVV95cUxOWU5uOHp0b2NSd2l5U2x4bTF3WG11TlR2SXFSWWhXTVlVeWFtXzdyTHZxNHY2M0pVeWpTTUp0S3lSVmxrQ1pVeXlfMDFvRmk1MldydmV1emtiTXk2WWJVNXhISmt3S2hyZkNVRnlEU0x2QlZKZnNUYTlMV09QTnZRY21CUllUSlY4MkhsSGZCMG1pRFdXUWxDZ3hVUmpUU2tTT0ZtVG8tNXAzT19XVmVqaGhpYWZhZzBxWVladS1ROFUzYnAzNFBzaTh4WEZDWExNbk5DdFVPaGJMWWU3VXfSAeMBQVVfeXFMTTE2TkoyZ3FUR3VObS0xWktFQTBuZm1Sa01EUFZQd0Z0ajlmNDZHZHpNQm40SERYQ1JycmhwaEx5ZnVGb0J0b1J4T3pObzI3c1NzR3VTSUstRXdhX3dVd0ZWZHMzVTVQQXZwT3lkMjJPaFktV01vRi1vZWNZWlN5Qk5QeUNPZXlHQ3Y3cFRoX0pyYlQzcEZmemFHN0JpZDZuWjloaU95Vk5LcGFuMWd4Q0l5VVo1di1oZ0pqYlkzUmtHWlJHSjl3QnhNRFd3WDdtSlJfbHN0MEV3MGNRQ3JYZVgwTDQ",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-with-hormuz-in-flux-can-pakistan-muscle-in-on-india-s-dominant-basmati",
          "image": "https://upload.wikimedia.org/wikipedia/commons/1/16/Strait_of_Hormuz_and_Musandam_Peninsula_%28MODIS_2018-12-10%29.jpg",
          "image_kind": "photo",
          "image_credit": "MODIS Land Rapid Response Team, NASA GSFC / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Strait_of_Hormuz",
          "carried": true
        },
        {
          "hour": 6,
          "time": "06:00 IST",
          "headline": "India-US trade talks begin: Piyush Goyal meets Greer as India's trade surplus with US falls over 40%",
          "what": "Indian Commerce Minister Piyush Goyal began formal trade talks with US Trade Representative Jamieson Greer, as India's trade surplus with the United States fell by over 40%. The negotiations come at a critical juncture as both countries seek to finalise a bilateral trade deal and avert the threat of US tariffs. The sharp drop in the surplus reflects India's efforts to demonstrate goodwill ahead of the negotiations.",
          "lens": "These talks could determine tariff rates on key Indian exports — from pharmaceuticals to IT — directly affecting jobs, industry competitiveness, and the broader India-US economic relationship.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxON3ZlTXBQSm9MV3VXMXR1aGVGc3JOZ2NLcUUybV9ISkZ3WUNYbVdjUzhwbUEyLWZfNThvNzFqZVJqYnhRTFIxdjZTQmtTV2xFQzJ6VFVtV00zVjd6RFJiNnNCaldUeHhfSEtydV85NHY1R0tpWThreU1OSHRfdVozcXNjN3JDMGZ0OTl2c3ZIdnJySnVTNzFZSEw5ME5NVnlGT2FRNFlIXzZkUWhEa3QtUlVfZ3RKM3lScnlfXy1YVWRxSm1zM1Zpa1JsaWd6LUZJMGNXdA",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-india-us-trade-talks-begin-piyush-goyal-meets-greer-as-india-s-trade-s",
          "image": "https://upload.wikimedia.org/wikipedia/commons/6/63/Piyush_Goyal_crop.jpg",
          "image_kind": "photo",
          "image_credit": "Ministry of Textiles / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Piyush_Goyal",
          "carried": true
        },
        {
          "hour": 6,
          "time": "06:11 IST",
          "headline": "Trump threatens to sue ABC News over reflecting pool coverage, claims Biden administration planned to spend $100 million on it",
          "what": "US President Donald Trump threatened to file a lawsuit against ABC News over its coverage of damage to the Washington reflecting pool, and claimed the Biden administration had planned to spend $100 million on the landmark feature. Trump had earlier threatened prison for those responsible for damage to the pool. The move is the latest in a series of Trump administration confrontations with major US media outlets.",
          "lens": "Trump's repeated threats against US media and his invocation of large government spending figures are part of a pattern that shapes global perceptions of press freedom and US institutional stability — both of which India monitors closely as a strategic partner.",
          "source": "Mint",
          "url": "https://news.google.com/rss/articles/CBMihAJBVV95cUxPNXBWMXdQOEs0V2NDSzJqb2w2M0FCWElqbHY0eUpONU9JOUpaNEdqTGh3Z29kM1Q1SkdIZzlkTVNIdFFVRTRGNlVTSGNKbHJiMTNDaFlFTzNLQk9CbnVaNmJCMWVtMm0wN2o0MFEzVnFmY0RYR1VEQnNlc2pQS2VkVEs4NUVrSW5RZFF4OFVZR0VLNW4ycW1vOW5NRm9JR1lpZkRsbUNJNjI2d1hVVDRuMFB6WVZfcmRQd1BQR3VxNXBROGFkVE91TEN6Qk9nUTlBaGdDTnZKbG5taWdnZDRJcUZINWU4Sl8xTlUzamlldWFsci14aFZtaXRXZGRWMG1pMEFHZA",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-trump-threatens-to-sue-abc-news-over-reflecting-pool-coverage-claims-b",
          "image": "https://upload.wikimedia.org/wikipedia/commons/0/0e/2026-06-17_Lincoln_Memorial_Reflecting_Pool_post-restoration_Washington_DC_18-53-22.jpg",
          "image_kind": "photo",
          "image_credit": "G. Edward Johnson / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Lincoln_Memorial_Reflecting_Pool",
          "carried": true
        },
        {
          "hour": 5,
          "time": "05:56 IST",
          "headline": "Iran-US ceasefire diplomacy accelerates: Vance says talks set 'good foundation', hotline agreed, but Tehran warns Hormuz will never return to pre-war state",
          "what": "US Vice President JD Vance has said talks with Iranian officials have set a 'good foundation' for a deal to end the war, as the two sides also agreed on a direct Hormuz hotline to manage shipping tensions. Iran has agreed to allow UN nuclear inspectors to return as part of the emerging agreement. However, Tehran struck a defiant note, warning that the Strait of Hormuz will 'never return' to its pre-war state.",
          "lens": "The Hormuz strait carries roughly a fifth of the world's oil — any deal or continued closure directly affects India's energy import costs and fuel prices.",
          "source": "The Hindu",
          "url": "https://news.google.com/rss/articles/CBMirgJBVV95cUxNSndlb1Fvd1FwZnh1UXZwNVFnS3ZrX3pGaUJiYXFtTERfRE1EVkpSMVktbWNNMFF0aWZxUU12YVZUc3Q4WFViaGZDOVZXRUJkUnNqZGtfTnpsT2lDU0tWOTF5WVJiN1JUVFN4MVFvZ1BPajBkd1dsZGlndXRkRTVXTl9oUkZIenNwZTlLYmJkdnhtWFpJcl9YNnlZRllOdW9ndXNvUXRtdFp0MDNDamUtb1JNUWMyWDdCMXRvb3lVNFBCQlBPbl9JU0lNVEg5QW9pcmZzd1l5ckI0QU1DUWVWSUREdXk2YVpCOGhNR1V1Q1MyTXpZR1VhMDQ2VzZfN2pQWDV2RE5ZQzhSTFZRWWx0a3kxYmJCQXZRaVNXUUxhUE5QQWhQMXN3Smx1ZzNZQQ",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-iran-us-ceasefire-diplomacy-accelerates-vance-says-talks-set-good-foun",
          "image": "https://images.pexels.com/photos/32237794/pexels-photo-32237794.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "İrfan Simsar",
          "image_credit_url": "https://www.pexels.com/@irfansimsar",
          "carried": true
        },
        {
          "hour": 3,
          "time": "03:13 IST",
          "headline": "Lionel Messi sets more records as Argentina advance in World Cup 2026 qualifiers",
          "what": "Lionel Messi added to his extraordinary list of records as defending champions Argentina continued their World Cup 2026 campaign, according to BBC Sport. The Argentine captain's latest record-breaking performance underlines his continued influence on the international stage even as he enters the twilight of his career. Argentina, as the reigning World Cup holders, are among the favourites for the 2026 tournament.",
          "lens": "With millions of Indian football fans following Messi closely, any record he sets resonates widely — and Argentina's World Cup form will shape how Indian viewers engage with the 2026 tournament.",
          "source": "BBC",
          "url": "https://news.google.com/rss/articles/CBMiZ0FVX3lxTE8zdGpmY1RZMmlzZ2o0LXRlSzRhbEJ0ZXctTWxNNVk5V2Vjb09kaDM1V3NWa3lObTZ6dVd2d1NFSWtyb1YzZS1fUEV0LTYtbUVGZmZYeHFNRWd4N215Mnpib1FTdTZ3cUE",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-messi-sets-top-scorer-record-as-fifa-world-cup-2026-action-continues",
          "image": "https://pixabay.com/get/g733b93d5aefbed3f04dd302bc491b4259a056b24bbb32dedb90bc37be2508ba5a3b7b21742253a2c3cdf92ac57627e9f4b2aa5edd9e155d069d67ce65e6c3bd2_1280.jpg",
          "image_kind": "photo",
          "image_credit": "The White House / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Lionel_Messi",
          "carried": true
        }
      ],
      "carried": true
    },
    {
      "id": "business",
      "name": "Business & Markets",
      "stories": [
        {
          "hour": 16,
          "time": "16:17 IST",
          "headline": "Sensex closes almost 900 points down as global sell-off batters Indian markets",
          "what": "Indian equity markets took a sharp hit, with the BSE Sensex closing almost 900 points lower — having crashed as much as 1,000 points from the day's high — while the Nifty hovered near 23,800. A global sell-off was cited among the key factors driving the decline. The fall extended losses that began at the open, when the Sensex had already started 170 points in the red and Infosys dropped 3%. The broad-based decline reflected investor nervousness about international cues rippling through domestic markets.",
          "lens": "A nearly 900-point Sensex drop directly erodes the value of mutual funds and equity portfolios held by millions of Indian retail investors.",
          "source": "The Times of India",
          "url": "https://news.google.com/rss/articles/CBMingJBVV95cUxNMndvd3JhcEMySGZTRjNXVW4zRVhpQ0NpbVFIaUxKR1J5Q0JreFRaejhuNFpzMzR3aWpxSFB1Wmd0dTktZzhfMVdWX3RmR1o3d3FyWkpTSW8tdmx0cXhfUDBqQ3RRajg2X3hhc1U2YXVXeWt3WFUwalJGcWxmRGl1S283UG5TTmZWbmY3NElHMzM1X2RDbUZQcjVjZjFwdEtSMC1DcXpvUGliUXBOcmY5b1RkalJqVjIwNmhJQ0NIUzMyMDdPUGlqUDNjSDYwU2IwbG5hUWJKSzB0bkZYM0FnQmY2MTVISC1uV1A0Z2lVdTRUZm9vMGhzRnREX1ZBRkx2RjJPYnR2Q0JZajlwSzN1a3J1dEV0dGt0XzBSTG530gGjAkFVX3lxTFBTNldLU2wwLWJyRzRNRWZKbUpaSWFRTUxkSkQxbGYxSU9nVjc5QnNucUZJSDJ1Rm9MLTZwS0pzTWJMNE5HeUJrQ25hTlpEdENPVURBUjJydTNMNTkyR093bEZGMGk2eHpMMlppbVU2Slh1OHNjdzQtTDVkN3l6SWlUYVRyZzFZVUJ6V0pVUG9FRGQxaEQyTUtibkVKYVgyemJWZ1dnRkFfd2lmZVJkUFNiOWNnMXVnb2VIWjlBN0YtQTNCZEhHY0JVYkpvVUdFUV9TVmZUS0FqRGZBRGlEWUNmY3ZIRDlNVjRYY2w1VU95UnF3dmVTeWEwYlI1N0dRbGlGLWhINHdWcm5KemtUM2tWbG1ZSWdJWk1qaDhVMTJJRDJIcw",
          "breaking": true,
          "_hot": true,
          "slug": "20260623-sensex-closes-almost-900-points-down-as-global-sell-off-batters-indian",
          "image": "https://upload.wikimedia.org/wikipedia/commons/4/4b/BSE_building_at_Dalal_Street.JPG",
          "image_kind": "photo",
          "image_credit": "BSEINDIA / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Bombay_Stock_Exchange"
        },
        {
          "hour": 13,
          "time": "13:38 IST",
          "headline": "Kunal Shah named WhatsApp CEO, sparking conversation about his educational background",
          "what": "Kunal Shah, best known in India as the founder of fintech company CRED, has been named the new CEO of WhatsApp, one of the world's most widely used messaging platforms. The appointment has generated significant public attention in India, with many commenting on Shah's educational background — he studied philosophy at Wilson College in Mumbai and dropped out of an MBA programme. His rise to lead one of Meta's flagship products is being seen as a landmark moment for the Indian startup ecosystem and its global standing.",
          "lens": "An Indian entrepreneur taking the helm of WhatsApp — a platform used by hundreds of millions of Indians daily — marks a striking milestone for India's tech generation.",
          "source": "India Today",
          "url": "https://news.google.com/rss/articles/CBMi4AFBVV95cUxPWGMxLWZWX2xTcE9ubUpVTk5FUlBZMy1oVXlUT05GZnFlQjdHUXpKYUdiX2Ixd1doZzhnZ052S1RJSzhpR0lJWjR6dUdBa3cxZXlGTEhzQ1dWTmFEN0IzeHBmY3pra0cxZGo4QU5HcHpGZTBlSUljaE1icTJUN3QtZ3FYU3RlUGFEc2hTNnhmeHY5MjRiY2NSZTQ0RVNZam5iZ3BmMzd0ZmZVUnJvZlRRb1pwc1JLYXJ0TGRMZWRFT1llNVBDdThkOXBzNm9jRW9wZ25tUnJFWTZkQ09MM1pGRNIB5gFBVV95cUxPODhtRVMtMlh5TzFPT0xic01YNXdiOUlFNkg0NVBQVFNwWWdUdWpKR0NXcDFuNGNEVUdKSXd4ZkdCTks1cEY5UlR6TUdwQkZsTmdNQ1ZxQkRhM0VYQ0tOODN6SXB4aXZFcTd0UDlZRE01Szg5MGQ1RngtTEVTMGJfUTN3Qi1pQ011RjNJOE1lSnlBM19JcWpDVUlHRU0wMDZtdk1RS25pYXJtSDdkeFIwem00TlNsOU9RVUNHTVk2aGJtM1dwSEt2UGJNOXc2czctbGdLU1Zac3plVlgwRWo4S0U0MzItUQ",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-kunal-shah-named-whatsapp-ceo-sparking-conversation-about-his-educatio",
          "image": "https://upload.wikimedia.org/wikipedia/commons/8/83/Kunal_Shah_in_FreeCharge_T-Shirt_%28cropped%29.jpg",
          "image_kind": "photo",
          "image_credit": "Kaustubha Dahibhate / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Kunal_Shah"
        },
        {
          "hour": 11,
          "time": "11:32 IST",
          "headline": "India and US hold ministerial-level talks on trade deal as US embassy signals push for fair pact",
          "what": "India and the United States held ministerial-level talks on a bilateral trade deal, with US Trade Representative Jamieson Greer meeting Commerce Minister Piyush Goyal to work through outstanding issues. The US Embassy stated that Washington is focused on a fair trade deal that benefits both countries. Significant sticking points reportedly remain, including market access, tariffs on agricultural goods, and digital trade rules. The talks are taking place against a backdrop of US tariff pressure and India's effort to secure a preferential arrangement before any broader tariff reimposition.",
          "lens": "A US-India trade deal would directly affect the price Indians pay for imported goods and the market access available to Indian exporters in America — the country's largest trading partner.",
          "source": "NDTV",
          "url": "https://news.google.com/rss/articles/CBMikwFBVV95cUxNclhhZ2ZqbnlUaDNRWVltZXc4YXMtUXY4QzQ5M25HNGc4YUZOYXRtaGFZYTVuUHRVRVhLcmw5NmhpU2dHQzI3M3ZxVjBMSW92bF9INk10VnVhM0VFOEtBUVRVOU1xd3BFbXZvUURtQ1g4b2hDOGdmY0VWZHc2LWdoYXdKak1zUWRERXVyUXFhV0RqRzjSAZsBQVVfeXFMT0R0LUZidEtpNXlpdW9qYndfSFVtVDdIYWw3QVlLdDlSdDg3THVCaThkTkZpZlFyVGxVT21jVWxDWmRlSDJweEI3RDVLN3RQdmZVSTBWOHh3aV9ZVDZoSnhlTnpmU0RLM0VWOXdUd1UtYWJFVVNoVGFfOWdSNkdrWGRuV1pqMDdTbWRtNVBPU1FtR3l0cUhpa1RVLWM",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-india-and-us-hold-ministerial-level-talks-on-trade-deal-as-us-embassy",
          "image": "https://pixabay.com/get/g93ec0e8cb904853d27b967028ae9d27d7e86437fba51a15fddde28a12ec4c90dadf280138829ab1b0548484ced805601_1280.jpg",
          "image_kind": "photo",
          "image_credit": "Simon",
          "image_credit_url": "https://pixabay.com/users/Simon-3/"
        },
        {
          "hour": 11,
          "time": "11:00 IST",
          "headline": "India's business activity slows to three-month low in June, optimism at six-month low",
          "what": "India's business activity decelerated to its slowest pace in three months in June, with a closely watched survey also showing that business optimism dropped to its lowest level in six months. The data points to a softening in both current activity and forward-looking confidence among Indian companies, raising questions about the durability of the country's recent economic momentum. The readings come as global headwinds — including trade uncertainty and weak external demand — continue to weigh on the outlook for Asia's third-largest economy.",
          "lens": "Slowing business activity and dipping confidence are early-warning signals that could translate into weaker hiring, investment, and growth for everyday Indians in the months ahead.",
          "source": "Moneycontrol.com",
          "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxPLTl6aHhGOXhja0c4aXcxSzd1Z1dSeWNrQzhHOFRvUWlhOHB1eFpZaVh0X3liNVJJNVMzSXo1c1dkV0trQTZ5dVdIamRqdFFmMk8zREZHSXVCQkdEVjF2WnpRZFBHMms2TGlJWV80UzI5X080ckVCNnJyTHd1TzZKRkhJQWI2eTRBbi1ONGdqc3loaGl2QWpJaU83MzVJRzVBaWdITXlxSm9abzU2aHRKY01ELVRjWHI1U21pUFpkWGdPaEp2d1dnc1VoOXljamItQjdxX1NmTFZseDk0VU9EZXFtZEZjSEnSAewBQVVfeXFMT3dtdHFBS00zdHpsVU0yclItUkFkaFBERUZiZ0ktSXUzRnZRaFluZW5Kc3o3dHhDN1BTZjVkU2otN2JiT3cyaXBlSGtCTTZPbGtaOHNSZnZxbXdHVmpDcHc4Z3Z1VHVmVExQdk53aERxWTBPRmNtZVBTN241RnpRVk9DM0xoa25TQVYxMEFvYks0RzMwZ21lamotbUlBZy1CalJLbHNxV2J0Vmg2TU1sYno2RldORDFwaDZXSFdHbmVYT3dfVFl6OU9Bc2FCamVrOW1kdW9ZendVeUVjNnB5MDN3Tm11Y1UwU1pGdnk",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-india-s-business-activity-slows-to-three-month-low-in-june-optimism-at",
          "image": "https://pixabay.com/get/gfb031acecf3d0ad2fdade282b96f2bdefd11214fc314f548ec9549aaad9a8c4f8f2691afb180027290cccac3f8a4779b1d23d8a58de1b515af9ae7fe186ccc3b_1280.jpg",
          "image_kind": "photo",
          "image_credit": "stevepb",
          "image_credit_url": "https://pixabay.com/users/stevepb-282134/"
        },
        {
          "hour": 7,
          "time": "07:13 IST",
          "headline": "India's Biggest Equity Fund Makes Contrarian Bet on IT Stocks",
          "what": "India's largest equity fund has taken a contrarian position by increasing its exposure to information technology stocks, moving against prevailing market sentiment that has been cautious on the sector. The move is notable given concerns about global IT spending slowdowns and uncertainty around US demand — key headwinds for Indian IT majors. The fund's bet suggests its managers see IT valuations as attractive relative to fundamentals.",
          "lens": "When India's biggest equity fund bets heavily on a sector going against the crowd, it often signals a turning point — retail investors and smaller funds tend to watch such moves closely before repositioning their own portfolios.",
          "source": "NDTV Profit",
          "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxQMERjd0I2YnpYcWFMQ2FrM1lBLVRCaC1qSjluSEV1QjJ3ZDdoeGcyZDRTTXAxTDd3cVhhVmtWOUl5RG9kX01TQXkxdFBHMENST2ZDRmI3UWJZV0dPRmU1Q0Jhd1ZINV8yNEhBT2d5a1Q2Nk1YVjZXQ0k3WmZ3djA4SzJpR2RmZU9qZENROEJSTDRfSTE1STI4aUhZaS1JRnFHVHNGaWliZw",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-india-s-biggest-equity-fund-makes-contrarian-bet-on-it-stocks",
          "image": "https://images.pexels.com/photos/14907378/pexels-photo-14907378.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Ravi Roshan",
          "image_credit_url": "https://www.pexels.com/@ravi-roshan-2875998"
        }
      ],
      "carried": true
    },
    {
      "id": "tech",
      "name": "Technology",
      "stories": [
        {
          "hour": 20,
          "time": "20:48 IST",
          "headline": "Meta Invests $900 Million in CRED and Names Founder Kunal Shah to Lead WhatsApp",
          "what": "Meta is investing $900 million in Indian fintech startup CRED and has tapped CRED's founder Kunal Shah to become the new head of WhatsApp, making him the first Indian to lead the world's most widely used messaging platform. The move is a landmark moment for India's startup ecosystem and signals Meta's deep strategic bet on India, where WhatsApp has its largest user base. Shah will now oversee a product used by hundreds of millions of Indians daily.",
          "lens": "An Indian startup founder taking charge of WhatsApp — an app that is effectively India's digital backbone for communication and payments — is as significant as it gets for the country's tech ambitions.",
          "source": "Reuters",
          "url": "https://news.google.com/rss/articles/CBMitwFBVV95cUxOeDR6YTZ1Tk4zWG9sZF9FMU1vVXlHRWhlUkJHNjZ3STVXSExVbDhVZ1lXeHljVVdkanR6LVozR19IdWxiSzJ2TlVCQk1ZT05VUXplT0pXUzJvdzBmaWVyV21xeFU2el9COHpDQXNkTExwVVNHVmp4cjFXODJ2eG11d190bDFZeGNMT1Bhek9BV0NmbnFTYTdxeWQxampoTVZfMW4wa01xZnlaN3RrSTh3ZXhLSDhkNXc?oc=5",
          "breaking": true,
          "_hot": false,
          "slug": "20260623-meta-invests-900-million-in-cred-and-names-founder-kunal-shah-to-lead",
          "image": "https://images.pexels.com/photos/17614479/pexels-photo-17614479.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Julio Lopez",
          "image_credit_url": "https://www.pexels.com/@julio-lopez-75309646"
        },
        {
          "hour": 15,
          "time": "15:55 IST",
          "headline": "Tech hiring in India hits all-time low, software engineers worst hit",
          "what": "Tech-related hiring in India has fallen to an all-time low, with software engineers bearing the brunt of the downturn, according to a new study. The findings signal a significant contraction in one of India's most sought-after career sectors, which had seen explosive growth in the years following the pandemic. The slowdown reflects both global headwinds in the technology industry and the growing impact of automation and AI on traditional software roles.",
          "lens": "For lakhs of Indian engineering graduates and working software professionals, a historic hiring slump means fewer job offers, longer job hunts, and mounting pressure on salaries.",
          "source": "India Today",
          "url": "https://news.google.com/rss/articles/CBMi2gFBVV95cUxQUDdnb0xaLU5YSzhjM25vMFdWMnpsMTZDSHVhRUxSVlJXTXBvMUZoSk9hMzNzQi03YVdhTEhPWVROZnFhZ2xMOHBGcUM1SDRZLW4tekk0bmdPNVRnY2J6bkxmNVppMHg3bWtQMUtCR3RxeEotTm5Pb00zUzVWeHlfX1ljcHBSVlk0UW1ZNGtEcnFCRnVvbHQ3a1dIaElVTUtpNm9DMlNjcVhSSWRMRVBnZ3o3RVVBWXoxMXJ5T0gyNUZsbm5zb05US3RtX1kwQkZzN0lJRzU1RTc2UQ?oc=5",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-tech-hiring-in-india-hits-all-time-low-software-engineers-worst-hit",
          "image": "https://images.pexels.com/photos/1181341/pexels-photo-1181341.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Christina Morillo",
          "image_credit_url": "https://www.pexels.com/@divinetechygirl"
        },
        {
          "hour": 15,
          "time": "15:27 IST",
          "headline": "Silicon Valley's India talent story takes an unexpected turn",
          "what": "A new report from The Economic Times examines a notable shift in Silicon Valley's relationship with Indian tech talent, suggesting the long-established pattern of Indian engineers emigrating to the United States for top-tier roles is facing unexpected disruption. The piece points to changing dynamics — including return migration, remote work, rising Indian startup salaries, and global tech layoffs — as forces reshaping where and how Indian engineering talent deploys itself. The shift has significant implications for both India's domestic tech ecosystem and American technology companies.",
          "lens": "If high-skilled Indian engineers increasingly stay home or return from abroad, it could accelerate India's own deep-tech ambitions while changing how Silicon Valley thinks about its talent pipeline.",
          "source": "The Economic Times",
          "url": "https://news.google.com/rss/articles/CBMIngJBVV95cUxQMzNPT0swWHJUVm1WY2dibFY0cGFnTHE0M3VUU0tSa08wNlNNS2t5eXZXWjZQeTlMOTJhbGdxRXFVNFRBa3NEam9HMGU2bzNEaWdLbDRNVjdEUW5DUlY2Vks1SUJkdE50XzlUVjBiOWhpZXRES0c0UU1kejFOZXppOUZLcTN1c1dpd3V2bktWQTRlS3ZJMWsxYlVyZVFZam5HT2poaGgzbmNvUEpLVzQxSmgxMUVCSGd6MmVuVDRyV01hZlZiWE9JOC1CVVpGQzVDeHBQMHJ1em1IWlV2Ykw0LXBzSWl0OFRHQkRsTkd1TjZ0YVhuVWRkU0VRYW9YREFKTnIwd0NKZHJKUlFiUmJYZnZWbnRPQ0JGdUd6SDJ3?oc=5",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-silicon-valley-s-india-talent-story-takes-an-unexpected-turn",
          "image": "https://pixabay.com/get/g1685f49b2ae739ec67d34642073ac72d7fababdc9ba6c97345dd0342ea046bdf9f4fcdf9848bee35a292b350aaa0ef0be5ee9ff2ce21db987d7e520fd1be4cb8_1280.jpg",
          "image_kind": "photo",
          "image_credit": "itay-verchik",
          "image_credit_url": "https://pixabay.com/users/itay-verchik-12396835/"
        },
        {
          "hour": 14,
          "time": "14:48 IST",
          "headline": "Nothing Phone 4b launches in India on July 7, first in the 'b' series",
          "what": "Nothing has announced that its new Phone 4b — the first model in its 'b' series to carry the number 4 — will go on sale in India on July 7. The Hindu reports that the device marks a new chapter for the London-based brand that has built a cult following in India with its distinctive transparent design and Glyph lighting system. The 'b' series has traditionally positioned Nothing's more affordable, mass-market offerings against mid-range Android rivals.",
          "lens": "For Indian smartphone buyers looking for a stylish mid-range Android alternative, the Nothing Phone 4b launch on July 7 is a concrete date to watch and compare.",
          "source": "The Hindu",
          "url": "https://news.google.com/rss/articles/CBMiuAFBVV95cUxNOUN1VldfTnlkRmNtQ1JST0F2NF9Hb2plblpUYVVGa3h4cHBxUUwtMC1LbUFZV2tzM3N5ZmNFc2Q4RWtMMWdSMDdXZnVTTURiOWxPMEl5cXNWaWEyY1ZSSXJHTmIweThJdmFJVURqcVNnSjhvZzZiYWVQbE00cTRPb2JlWU9jejd4ZkFqNkZSN0NqTVV5cWJCS2YtOTZ1dkdRRTYycWtadUZTci1KUlFFTlpoTWtHN2cw0gG_AUFVX3lxTE9fblhzTkoyTmZwb19hbnhXSXVJaV93aWUxN3lmVlF6b1VpaTV6T0NRY3FScWpPaHZ6T0VyU29IWmtzdHJZaGtNX3dIWU55VVZIbXFhZGJyLUpsRG5nSnpOUWhfTmJURXFnMklTV1huRjdHZTZjakI0WndEZE1WSDgyXzJaYVF4QXdZVzNLNEl4SWN3YkZDcjEzMVFTbHFXR2dOM19QZUgyRzlZajdlN1I2YmwzUjdMNmRRN2otRnU0?oc=5",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-nothing-phone-4b-launches-in-india-on-july-7-first-in-the-b-series",
          "image": "https://pixabay.com/get/geff7116c4ec0e6c0b86b8046b9e83b19efc60605464e8fe24d9385419330c42ca4ced2bf7cbf428d3905f04783524a48965e6d5bcbf796486b4722b85e716ae1_1280.jpg",
          "image_kind": "photo",
          "image_credit": "ornanvelazquez",
          "image_credit_url": "https://pixabay.com/users/ornanvelazquez-23340895/"
        },
        {
          "hour": 14,
          "time": "14:53 IST",
          "headline": "A Tamil Nadu engineer's Rs 10 question shines a light on everyday corruption",
          "what": "An Indian Express investigation follows a Tamil Nadu engineer whose persistent questioning of a Rs 10 bribe demand has become a remarkable case study in the everyday corruption that pervades routine public transactions in India. The story illustrates how even the smallest informal payments — often dismissed as minor inconveniences — reflect a systemic culture of petty graft that millions of citizens navigate daily. The engineer's refusal to pay has exposed the mechanics of how small bribes are extracted and normalised in bureaucratic interactions.",
          "lens": "Most Indians have faced a 'small' bribe demand at a government counter — this story names the problem precisely and shows what happens when someone refuses to look away.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMixwFBVV95cUxPTnVremhUYVV2OFVRZ21yejRXblg4WDUxRUU3QWZEbV9KZE1zR2dEbXNXNTBrTWppMFJHRWc2aUxWOEN4WWdoVGNmak11UGNnckdXWHFjZVMzUjlnN05NNzdGLXVQQ1dINk1oVE81UDdJVEc5dWo4a19lb0tvYTNMWnpQWVFoNV9ZZ05qRVFLOENWRjE2S1ZSOUsxZFB2cFo5M2puLTN6SUdCSTRwT2JySXNia2lFTFhselN6MlQ2R2RpV3ZvMzBZ0gHOAUFVX3lxTE5WQWJCOEM1OXB4WVdJLWw3RXVaMmlRMVcxZ0Q2ekpZNW9RRUgzbTBDbVduYUV0NzQxTldySktmWm9sZHV0ZVVpM2VMY1FwTHFMWFZqeFZDS0tvSHB5bEVfbEJESHplMVRhRWNDX1RRYlh2VnNCc3k0VWRHcWlFa0djMlR5U0tKd096V3B2QUZlTkFfZmJZVzZzUUMtMnNCNTN0VjBxMXBNZV8tX1dKcGlvLS1XR0FIZm9pSHVoMGpqMzBvTWY4Nmx2cm40Q0Fn?oc=5",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-a-tamil-nadu-engineer-s-rs-10-question-shines-a-light-on-everyday-corr",
          "image": "https://images.pexels.com/photos/9245871/pexels-photo-9245871.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Rohan Dewangan",
          "image_credit_url": "https://www.pexels.com/@rohan-dewangan-2844320"
        }
      ]
    },
    {
      "id": "national",
      "name": "National",
      "stories": [
        {
          "hour": 16,
          "time": "16:25 IST",
          "headline": "Supreme Court Orders Right to Walk on Footpaths Amid Surge in Pedestrian Deaths",
          "what": "The Supreme Court has issued an order affirming the right of citizens to walk safely on footpaths, a ruling prompted by a sharp rise in pedestrian deaths across India. The Indian Express reports the order is backed by data showing a troubling surge in fatalities among people on foot, highlighting the systemic failure of urban infrastructure to protect non-motorised road users. The directive puts pressure on civic bodies and state governments to clear encroachments and restore footpaths to pedestrians.",
          "lens": "With pedestrian deaths rising sharply nationwide, this Supreme Court order directly affects the daily safety of tens of millions of Indians who walk to work, school, or markets every day.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMiswFBVV95cUxPSGN3QlZqVWN4VnNWZUQwUmRmOUNJeHZEWlFuckF4VU5oRUtGX21XRlBvNVYzM1BxS2VONnZmOTZEMGF1bWxrSjVyNktkMjNDQ29pakFXUjdCNEtXSXZ4MnZ0NjNLUUd4ZTM1amJjdmFlYTk2bU4tQnYtMzhkSU8zM0VVTlRjRko0dWQ4R1RTaFRKNFpGQ3h1S2RtTlA2QW9SS3BWRXVmYnljU3U1RzVhOGlaNNIBugFBVV95cUxOY09BVVJvSktoemRic2JBS1VOcWI5a2JqNFFhOWYzUG9SclRncWw2Y3ByX3Z0TnVUclFWRTZGeU4yZDdqekxrTHdILVAtZGlnSWd1cElISFQ0bDF3ZXhsMVhjS2s3eHcxZktyUGd5MVhzcU1FSEhGSWdPd2V6WXFydmJ2dXg0cHRtSUZUUUpZNWg2elVULTJoS0dDOTdsOFQtMDI4dmhabzJSTVpHZldiUTRPOXBsZDZMVVE",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-supreme-court-orders-right-to-walk-on-footpaths-amid-surge-in-pedestri",
          "image": "https://images.pexels.com/photos/365813/pexels-photo-365813.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Avrajyoti Mitra / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Calcutta_High_Court"
        },
        {
          "hour": 16,
          "time": "16:38 IST",
          "headline": "Tamil Nadu Moves Supreme Court Against High Court Order in Deepam Scheme Row",
          "what": "The Tamil Nadu government has approached the Supreme Court challenging a High Court order related to the Deepam scheme — a state initiative providing free cooking gas cylinders to eligible households. The legal battle centres on the High Court's directive, which Tamil Nadu contests, and the state's move to the apex court signals how politically and administratively significant the scheme is to the ruling TVK government. The case adds to a growing docket of state-Centre and state-court disputes over welfare programme implementation.",
          "lens": "The Deepam scheme directly benefits low-income Tamil Nadu households who depend on subsidised cooking gas, making this legal fight over its continuation a kitchen-table issue for lakhs of families.",
          "source": "NDTV",
          "url": "https://news.google.com/rss/articles/CBMitgFBVV95cUxNcFEwRUd1VEtSdXJLRlBCVDI5N0pncFY1Si1jNWFNdDM0UFdOUWhRcUE4YWhrdzN1WmxNTnRkejUtVUdWUHNyYzlfeDRERnZoaTFrTHFGNHpWOUxVQ3dDdlZCbE94YkdJRkpRY1Y3N2lYN0g1NzFmX3RBcWc5d0JEQU1xcUJMa2tpa3B6blpWLUkzRVBXTEtLSjl6ajg3ZkY3NjI1U0NzbGNCemRvb0hHa1FfV3Bydw",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-tamil-nadu-moves-supreme-court-against-high-court-order-in-deepam-sche",
          "image": "https://images.pexels.com/photos/36405818/pexels-photo-36405818.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Tejash Mishra",
          "image_credit_url": "https://www.pexels.com/@tejash-mishra-2159944989"
        },
        {
          "hour": 15,
          "time": "15:14 IST",
          "headline": "Supreme Court Stays Release of 1993 Bowbazar Blast Convict",
          "what": "The Supreme Court has stayed a Delhi High Court order that had directed the early release of a convict in the 1993 Bowbazar blast case. The apex court's intervention halts the convict's release pending further examination of the High Court's reasoning. The Bowbazar blast, which occurred in Kolkata in 1993, was a major criminal case and the legal proceedings against those convicted have stretched over three decades.",
          "lens": "The Supreme Court's stay ensures that a three-decade-old terror and explosives case conviction is not undone by a lower court order without full scrutiny — a matter of justice for victims and their families.",
          "source": "Deccan Herald",
          "url": "https://news.google.com/rss/articles/CBMi3wFBVV95cUxOVzN0U1hmME5uZW5STVpVTEtJZFJlUmh3endneFN6el9XUjNJS0o3V2NEXzM2dUhNemg1SFV2S2ZobWtJdjJzQk1ZVDZwRWkteUI2SjVpX0RuUmNIaEp3VlViLVFNbE5EUlhKVmVnRkMyRXRGSV84VUdhLThJbWhEUjZncmMtRUtLNktNZjRZOGhTMEw0VG1USVZIY3diNm1SWEFqckxlNXgzUGpUc01ydlVLYXpYN2ZMcDVwZ0pQam5vRFQxWWNiVHpQbWxpOWRuYlJ0U2RIdjRXVnA4aGE0",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-supreme-court-stays-release-of-1993-bowbazar-blast-convict",
          "image": "https://images.pexels.com/photos/36984938/pexels-photo-36984938.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Mark Stebnicki",
          "image_credit_url": "https://www.pexels.com/@nc-farm-bureau-mark"
        },
        {
          "hour": 14,
          "time": "14:35 IST",
          "headline": "Supreme Court Issues Notice to Assam Govt in Zubeen Garg Death Case Bail Plea",
          "what": "The Supreme Court has issued a notice to the Assam government on a bail application filed by the event organiser arrested in connection with the death of celebrated Assamese singer Zubeen Garg. The case centres on the circumstances of Garg's death, which has deeply affected Assam, and the legal proceedings around those held responsible. The apex court's notice indicates it will scrutinise the state's position before ruling on the organiser's bail request.",
          "lens": "Zubeen Garg was among Assam's most beloved cultural icons, and the SC's involvement in the case signals that justice for his death is being pursued at the highest judicial level — a matter of deep concern to millions of his fans and the people of Northeast India.",
          "source": "Deccan Herald",
          "url": "https://news.google.com/rss/articles/CBMi5gFBVV95cUxQbGdWb1F3ZVdzODRnYlRsV2xWUk9Nem9Sa2J5dXZCTlh5emUtUGhINUNZMGd1UU1zQjl3SlZpMnM0ZlhTcGtOclBibmJycllBMkYwZWhRb1JFT2dYRWxSa2lrXzZhZU9KbVdxbmFTV19sOTdheDJLMnNDZEhBR3FFMndPN3MzdEFyRG01ZG1ZOUVtT1hpcHNyTWpvamdhQWx3Rk52NmFiRDczZ3BIOUxKTmxoM2UyWFFfb2JnZHd4RHI4cnY5MjBvczBFa1VJaGFKdjhoaVJkOFlpN19JWDRJUVRxTzhTQQ",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-supreme-court-issues-notice-to-assam-govt-in-zubeen-garg-death-case-ba",
          "image": "https://upload.wikimedia.org/wikipedia/commons/1/12/Zubin_Garg_Live_performance_%28cropped%29.jpg",
          "image_kind": "photo",
          "image_credit": "Donvikro / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Zubeen_Garg"
        },
        {
          "hour": 13,
          "time": "13:23 IST",
          "headline": "Akasa Air Eyes 30% Capacity Growth in FY27, Adds 39th Aircraft",
          "what": "Akasa Air has set its sights on 30% capacity growth in the financial year 2027, as the young airline continues a rapid fleet expansion that recently saw it add its 39th aircraft. The carrier is also reportedly weighing participation in a government credit scheme to support its growth plans. The targets mark one of the most ambitious expansion trajectories among Indian carriers and come as Akasa seeks to cement its position in an increasingly competitive domestic aviation market.",
          "lens": "For travellers, more Akasa seats on more routes could mean greater competition and better fares — making this expansion directly relevant to anyone who flies domestically.",
          "source": "The Economic Times",
          "url": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxPRkxYQUliR2p6RF9qVnJIQ05RbHFrNEF1NGxXMG9pRjVhYUZFbXIzeUh6dHd5REpDeGc1bmlmXzZleHoxS1VoRFBPVFg0RDZjWGRHVldlRkFPejUyRVJPMWFJWm5KSXA5XzIxcm9HQUZOS19GOEcxT3FiMVY4UzZGcDl6ckJOUmpRTldzbEFzbnltNFl6b3pVZjRuV2prZjlrR3k4TWFMNjlicWQ0ZmJObmF5VGVQWGhNMDFaNUVqM01kRzhFc29NRURqZzJfZmRtYmFEd2d3",
          "breaking": true,
          "_hot": true,
          "slug": "20260623-akasa-air-eyes-30-capacity-growth-in-fy27-adds-39th-aircraft",
          "image": "https://upload.wikimedia.org/wikipedia/commons/6/6c/Akasa_Air_737_max_8-200.jpg",
          "image_kind": "photo",
          "image_credit": "Krish Aarush / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Akasa_Air"
        }
      ]
    },
    {
      "id": "ai",
      "name": "Artificial Intelligence",
      "stories": [
        {
          "hour": 17,
          "time": "17:03 IST",
          "headline": "Why AI sounds certain even when it's wrong — and why we believe it anyway",
          "what": "A new analysis explores the psychological and technical reasons why AI systems project confident, authoritative language even when producing incorrect or fabricated answers. The piece examines how the fluency and certainty of AI-generated text exploits cognitive biases in human readers, making it harder to identify when AI is hallucinating. As AI becomes more embedded in everyday information access, understanding this dynamic is increasingly important for informed use.",
          "lens": "With millions of Indians now using AI assistants for news, health queries, legal questions, and financial decisions, understanding that AI's confident tone is not a reliable indicator of accuracy is a practical consumer safety issue.",
          "source": "The Times of India",
          "url": "https://news.google.com/rss/articles/CBMiywFBVV95cUxOMEhlRUVaT3VDRUl0OHAtcVdYbDBWLUgydEJjZWdYY2k3NXZTd29yZnlnSTBrbHBIclNnVkxpS2tYU1poaHZEdGNXYXREOHU3U0xSUDRBMDRycFd3UDJpaVR1ajdnb2N3WXNpX2ZFUEJReGdZNkMtMzFmM0RvTVp0d2lzSV82d2UyT3lrWmVoSk13UlBmM1RmQ0ktT2ZTOGE4UFY2QU5LSmZCUGdNNGFGQUxpZE9iX1BpQks3YThxNGhNbG1tU2tLOVlUNA?oc=5",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-why-ai-sounds-certain-even-when-it-s-wrong-and-why-we-believe-it-anywa",
          "image": "https://pixabay.com/get/g1e8737d49ae4e101e413981ade960210c9324ac8c365b68fbb4dd005c4b3171e56906fd51f9c651a5e047a71ec23783ab3278ccb671d9fa50a2f7588ed62e865_1280.jpg",
          "image_kind": "photo",
          "image_credit": "Alexandra_Koch",
          "image_credit_url": "https://pixabay.com/users/Alexandra_Koch-621802/"
        },
        {
          "hour": 16,
          "time": "16:18 IST",
          "headline": "Alphabet stock tumbles after top AI talent exits raise retention fears",
          "what": "Google's parent company Alphabet saw its stock fall after a series of high-profile departures from its AI division sparked investor concern over talent retention. The exits have raised questions about whether Alphabet can maintain its competitive edge in the global AI race, particularly as rivals aggressively recruit top researchers. The selloff reflects deepening anxiety on Wall Street that losing key AI minds could slow Alphabet's ability to compete with rivals like OpenAI, Microsoft, and Anthropic.",
          "lens": "Alphabet's AI talent crisis matters to Indian tech professionals and investors because Google is among the largest employers of Indian AI talent globally, and a weakening Alphabet affects everything from research funding to job pipelines in India's AI ecosystem.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi-AFBVV95cUxORThaOUllcmJPVXdYYTFSUE5ENjJSRVlLY3NrLTBrdDZQdm9vaUxIZ2VHbnYxS3dGdXNTWXNZVndDZ3dPVklwR1ZwTExzRkE4M01GMjQ2MHdiSDQ2NEZPMWc3UFRaNTJ2RE5iQ2staFRoYTFyVVYtLXB6d2ZaLWpQZGp5azJWQVU4LTZhLUVERUVnVGRuQWE4ZmtkeERuM0w3VF94ZkQtR1RJVXBxeUlWcGt6VlNCeHg3X2pOdnQ2a2ZDYTYwTEVvZklTaVdYV21NbkhDZXNkM0dUQWJibzVyM2RjVVBpTEVFcV9KNzdrUVhJeWJnbmRjcNIB_wFBVV95cUxQcDBiYmZZS1YteU5HclNEYXM5LW5RYjhtVElLU2F0S0g0RXhfSHpkTUxuOVZER0IzY0ZjUDNOY1QxSUFIbGM4LXd3MXpZOXNmMWNRaGF4RFhuMUN5TWQtRXBrbmtQeUlQR2RPLVJYWFl2bkJDMjZRSy1CUmRDV1Q5ai1LX1d5RlZFS0ZGQzA3d21YUy01WnlqVnZENElCQnB0dXpQMFZDV2RzYmdrc0Vpel9aNWxKUEVNOTB0M1hCdkRGbGp2TXZxN1pNalBkNHd4MjhSYllRNFhvOG91SzJ1N1Y0TWJLM1paazNSU3lLblRIVG4xYW5tRVUyTHh4RFE?oc=5",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-alphabet-stock-tumbles-after-top-ai-talent-exits-raise-retention-fears",
          "image": "https://upload.wikimedia.org/wikipedia/commons/e/e2/Google_Campus%2C_Mountain_View%2C_CA.jpg",
          "image_kind": "photo",
          "image_credit": "Austin McKinley / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Alphabet_Inc."
        },
        {
          "hour": 16,
          "time": "16:07 IST",
          "headline": "'AI eating itself': Trainers use chatbots to generate training data, experts warn of model collapse risk",
          "what": "A growing number of people tasked with training new AI models are admitting they use existing chatbots to generate the training data — effectively having AI teach AI. Experts have warned this practice, sometimes called 'AI eating itself', risks a form of model collapse where errors and biases compound over successive generations of AI training. The revelation raises serious questions about the quality and integrity of future AI systems if the feedback loop of AI-generated data continues unchecked.",
          "lens": "As Indian companies and startups race to fine-tune and deploy AI models, this warning is a direct caution that cutting corners on human-generated training data could degrade the reliability of AI systems used in healthcare, finance, and governance.",
          "source": "The Times of India",
          "url": "https://news.google.com/rss/articles/CBMi9AJBVV95cUxNRlZmUmRqRTA2TFVVZm0taHR4aFFXN2g3T25IRUF5OThMVmJFRllmSkFWdjk0dzFZV1hMVVFxOU1DRjhVVkxfVm1ndnlsT1Fod1k2ZDNWMWFrWlpQNGZVZHVzVTRfVmpab1daNjVjaEpVY0VRWGVVcUc3RU9fRXIzVEJNaEV5bFdTOWVCNzZoUEZNSDhmb2g2clRsY0pFSVc2LVRiam5qSm1CU1NncktBZzZ3Q1N2UHEyS1liWEhWSm1ULVcyODJUaElNaFdwaFFiUGNsMVRaSjZKcmgxbldPMllBWVNCa3BpZEloYmcwXzFhcDlQdkhpd0RuSDNSZmNsX2FiZDkyWV80R0JhSlNDUklyckZJeVd0UUFoQ3FLNFBIcUJVME1nR1NGN2V5RUt5eVJGaG1pM3VMUEhGOGlUNGlveEEyWDhFSlBvUDJnRlc4cTJ0QmpTakV2cC1fWDlNa3dsRWJOOWR1YTUzVXNHMXE4dDnSAfoCQVVfeXFMTlpPNVljSlBaUU1SZEc4dzg3Sk1CUUozbHpvdENEbXkzRmdnMnNNbTFZblhNZm54NGNQSGJpZ2hnVVhnU1YzN2dVdFBvRFNrSXVyTHZpSW9GX3dBdVZjZ0lCYWtKNnhETjhuUEJLQ3ozaTlub2ZTRUItMWd5NlBlbllPUGxZdzRQZFRnX2FLRzI4Q0tiN3Z1b2JIVTBQMmhkUXZIVml2OTYwekJWdm1FbzlXamRCUlIxNXllNGlhZ2ZzSWZhSlRwRGZMd1ZuRlg5OVBJQnMtSWRHUGZZaFUxQy1CTGpnRi1sSXZ5bDkzWGZjb05LdF9wdnF1a0NDTzFXQVY2ZkFxU2NQdVB5bUQyRXQyYWdNQmxYekowaVc0VE5yRFN0MVlYNFU1dk0wU3ZoSFJsNldfdzV2QTBJX1FJRWV0blVjVXg1Yk94T080Sk5YdjFwWXU3MGQ3eGNNb0NkMUhybzNDdXk1eG9vUU1xeEEzUm9LWERSeXJB?oc=5",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-ai-eating-itself-trainers-use-chatbots-to-generate-training-data-exper",
          "image": "https://pixabay.com/get/g207bca9678425be2826166d528c872127ff40945ad008c31cbc215b0401ed36da3e9f760abd7e6057774091b1b566e78cc3fdd423fafa93b15b08b6d85a4c0c4_1280.jpg",
          "image_kind": "photo",
          "image_credit": "geralt",
          "image_credit_url": "https://pixabay.com/users/geralt-9301/"
        },
        {
          "hour": 14,
          "time": "14:32 IST",
          "headline": "Japan's Sakana AI claims its Fugu Ultra model matches Mythos on certain benchmarks — and reportedly beats Claude 5",
          "what": "Tokyo-based AI startup Sakana AI has announced that its new model, Fugu Ultra, matches the Mythos model on certain benchmarks, with reports also indicating it outperforms Anthropic's Claude 5 on specific tests. Fugu is designed as an AI agent-orchestrator built to help companies navigate complex export controls, representing a novel application layer rather than a general-purpose chatbot. The development signals Japan's growing ambition to field competitive, specialised AI systems on the global stage.",
          "lens": "India is actively building its AI policy framework and evaluating which global models to adopt for sensitive government and enterprise use — a capable Japanese AI system designed to handle regulatory complexity could become relevant as India tightens its own technology export and import rules.",
          "source": "Business Standard",
          "url": "https://news.google.com/rss/articles/CBMi7gFBVV95cUxQZWxNenpOZG96X3pQRVkxNWR3QnlWUmxXdldPWnM3MUpkMURjS2hodXRuTzFCb3dCUmdBRTR4SXpNV1ZkLXltQ29RdDBwaDRoMzZCdUVkREU3b01DaFNJcWM4Z2hOS1JVQ3dXTU5qRkZCaUpoZWNJbExVTE1LdlpCYlZPZWxaQzdUbFVkTXhXNFowWU1TMWR0Zlhud2JwUWNueUhrYXJrdTAzaGtVQVlDOEdTTkRmV3lYcmN0NzZnNms3VWkzZGR3WkkwUkdMVDIteTBuSEhiOHQ0d2hzMjQyZ084Y2lqUXJJRUlFVDh30gHuAUFVX3lxTFBlbE16ek5kb3pfelBFWTE1ZHdCeVZSbFd2V09aczcxSmQxRGNLaGh1dG5PMUJvd0JSZ0FFNHhJek1XVmQteW1Db1F0MHBoNGgzNkJ1RWRERTdvTUNoU0lxYzhnaE5LUlVDd1dNTmpGRkJpSmhlY0lsTFVMTUt2WkJiVk9lbFpDN1RsVWRNeFc0WjBZTVMxZHRmWG53YnBRY255SGthcmt1MDNoa1VBWUM4R1NORGZXeVhyY3Q3Nmc2azdVaTNkZHdaSTBSR0xUMi15MG5ISGI4dDR3aHMyNDJnTzhjaWpRcklFSUVUOHc?oc=5",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-japan-s-sakana-ai-claims-its-fugu-ultra-model-matches-mythos-on-certai",
          "image": "https://pixabay.com/get/ga8288a1171b9abacc30fae55d86e32ebb574c93697ba0a47059285b4dce799b1c9ea2cb1d11cf87b274c13d3534e6822d6a6ea26528d3efd9abfee1a9a4dea1e_1280.jpg",
          "image_kind": "photo",
          "image_credit": "51581",
          "image_credit_url": "https://pixabay.com/users/51581-51581/"
        },
        {
          "hour": 7,
          "time": "07:42 IST",
          "headline": "Satya Nadella warns against concentrating the world's AI curiosity in a few companies",
          "what": "Microsoft CEO Satya Nadella has issued a pointed warning against allowing the world's intellectual curiosity and AI development to be captured by a small number of powerful companies. Speaking publicly, Nadella argued that the concentration of AI capability in a few hands poses a systemic risk to innovation and access globally. The warning is notable coming from the CEO of one of the world's largest AI investors, lending it unusual credibility and self-awareness.",
          "lens": "For India — which is simultaneously trying to build domestic AI capacity and negotiate access to frontier models from US giants — Nadella's warning about AI monopolisation is directly relevant to the country's AI sovereignty debate.",
          "source": "Moneycontrol.com",
          "url": "https://news.google.com/rss/articles/CBMi9wFBVV95cUxNZG9tdk5aMzdQcXg3T2wteFBsQTJGTl9fQVVRaG5SUURTc2JsczdBUXozTE41OTN0OER5Z2JOYWpIYmZIbUpENlJWd2VyR1ZhRnluVkhfY29mRHBIY2cyOGpyNldlZXZzRG9DSnJ3UDFNTnM1RENZY0xnWWpreFVDb1ZVZkFhZnM2NS16X0lfc21wczR6TTVjZTJ4QldnbmtjT3JXTkk0UkYzWVFYbXU1eXp5T2JUa1lJNWotczNfQzRWUDlBR1ZfV09iVm1XQ0h3bkd4aUNsMXdPNHRFMWxQVXVnd2F3Y0pyVWJwMUs5c1ZKODIxMUJz0gH8AUFVX3lxTE4taVJaSkdrSEZpN2NXV05qSnUxSWlxWWRxYjVKMmhUU3ZXOGYzdlRrYklBYWZCZWI2S0xlX1cxQzJXTHlqdlluWTlvQVFjOUctUzVDT3o5Nmd1UFoxY2lUUEpxV1VibUx5bFhZZmQ5cVRXdGlmajdjcFRGSmJPMFU3TTNUbVFPU0xqRld6cjJ4b3B5OVdacVZUc1JYUlFZbDRTLUR3bjlRWm4yYWZpUXdzenI2MkVuQ3dqZFE0bi10RTZmV3dUbUlqeTlwb1RTX0pibUNGWnBNQjI4QXZ4Z3ZCWkpuMnB1d2kyblJjNnZGYTFOdHl3a2ZZYmpKcg?oc=5",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-satya-nadella-warns-against-concentrating-the-world-s-ai-curiosity-in",
          "image": "https://upload.wikimedia.org/wikipedia/commons/7/78/MS-Exec-Nadella-Satya-2017-08-31-22_%28cropped%29.jpg",
          "image_kind": "photo",
          "image_credit": "Brian Smale and Microsoft / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Satya_Nadella"
        }
      ]
    },
    {
      "id": "sports",
      "name": "Sports",
      "stories": [
        {
          "headline": "FIFA World Cup 2026: latest scores and full results",
          "time": "18:04 IST",
          "hour": 18,
          "what": "The latest FIFA World Cup 2026 results in full — scorelines, goalscorers and what's coming up next, all in IST.",
          "lens": "Every matchday, tracked in your time zone.",
          "source": "openfootball",
          "url": "https://thelast24.in/worldcup.html",
          "breaking": false,
          "worldcup": true,
          "slug": "20260623-fifa-world-cup-2026-latest-scores-and-full-results",
          "image": "https://pixabay.com/get/gd625b7a88cdc981183e4b1ba9fefe54eb34dfd010b688c2e99f0c386f82225ccbe127deb3ef6197650a80cd67e86098b52d29988b252966381707b17ac82672d_1280.jpg",
          "image_kind": "photo",
          "image_credit": "jorono",
          "image_credit_url": "https://pixabay.com/users/jorono-1966666/"
        },
        {
          "hour": 16,
          "time": "16:15 IST",
          "headline": "Sooryavanshi overcome with emotion, touches coach Raghu's feet after India call-up",
          "what": "Vaibhav Sooryavanshi was visibly overwhelmed after receiving his India jersey and call-up to the national squad, touching the feet of his coach Raghu in a moment that has gone viral. The teenage sensation has been the talk of Indian cricket since his stunning performances, and his reaction to the India selection captured the hearts of fans across the country. Multiple videos of the moment have been widely shared on social media.",
          "lens": "Sooryavanshi's emotional reaction is a rare, human moment in Indian cricket — a reminder of what pulling on the blue jersey still means to a youngster from a small town.",
          "source": "Moneycontrol.com",
          "url": "https://news.google.com/rss/articles/CBMi8wFBVV95cUxOQkdlOTQ4b0RhSWdRaUFvS0k3dE13RlJUWE82UVlMd0hOWWxaSGJKN0hLUklWZHdCcTFkb0pTeDNRQjZnLU9jMnBKMS12VFBkMWFmaENScmhtMnNXM0lySDlkZlpVdVRyb1dKOHJteko3dk0xZXpfZ202UV9SNldocUF4TkRfZGR4c1V5bDI4ai1jczdvNDNYVGs1MlNRdE4yUTlUTU0tYng4blNvVEpjQUJWOVN6bVRCYmp0d0NMVlRWbjRuay1yYlpDUEFNSTJ1bUdEb3U5U2VaTldqZkUwUVdwOXF4NGZMSXROY0pUVGZSMEnSAfgBQVVfeXFMTVdJbnFJZXM2U3ZqamlkNFJWMk4wY3VYSnlpX3FYYkhYWGtSTkcyRTgxZThLWTNLQWh3dDlXUV8xTElyQlR3TlN1R21QSzNnajV6UnUwbU1fVVVmamlVQlg1c19JaXFac3E0OGEtdVBXNTc5XzJOaWNoc1NlOEw5RklhcG11em1sU0tFbE5MR2Y4VmhWRi1pS3duWWF5OG9KLTMxbEsyM2dKQkJ0N0dhSS1rRzlheVB4UzZxMDhWR0pPaDJVN29LdEN3YW1HUTl2SnhZQ0Y3M1lZc2xPTWl0azUwdXY5QXJBbjFkNFhWVk5WUVpWQkhnTkg",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-sooryavanshi-overcome-with-emotion-touches-coach-raghu-s-feet-after-in",
          "image": "https://upload.wikimedia.org/wikipedia/commons/6/68/Vaibhav_Suryavanshi_meets_PM_Modi.jpg",
          "image_kind": "photo",
          "image_credit": "Prime Minister's Office / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Vaibhav_Sooryavanshi"
        },
        {
          "hour": 15,
          "time": "15:13 IST",
          "headline": "Algeria stage comeback to knock Jordan out of FIFA World Cup",
          "what": "Algeria produced a resilient comeback victory against Jordan to eliminate them from the FIFA World Cup, in a result that underlines the improving quality of African football on the global stage. Jordan, who had made history by qualifying for the World Cup, could not hold on as Algeria fought back to secure the win. The result ends Jordan's World Cup campaign.",
          "lens": "For Indian football fans watching the World Cup closely, Algeria's comeback is a reminder that African and Asian sides are increasingly competitive at the game's biggest stage.",
          "source": "India Today",
          "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxPS2lLVW1ZT3hKUzktd0xlcU54X0FhUWN6c2hKNVpOeGtGNUhSSFhuWmVYeWpwbHNrenpPV2g4OW54a04tdGxoMG5hdEZoT0pWXzJBNzFiR1d1clJyWWQ0a0ZqQnlES2hjQk5Yd0hNV3Y1dXVnX0dQa3hPUERsaTBjS3NKdTYzT1FtU0QzVmFMTDV3UXd6Rl9OZ3laMklJMnl2dkVrNWU0N0JaRm9SQU94ZDZR0gG3AUFVX3lxTE1VZno2RDZIS3lBM2NCRUM3bHh2TzFRdGNyMlZKMzNYMmFTay1jQUdjcmtKNnQwM0kybHhjNmNDQ2N2OHIwMURJTm4xenpieS02b0xNQVo1WTl6QTB5VEhVTlBweXdKeHpkeHpqSmpacjlMeGFaQ1hjQWEwQ2ozQzlZUFJ0dGpqdzBCYy0tdFZYQUNpdUdZaURxenlyc202V0tHakNCRjBmdzJhVzgtaW1RaFRiX1pqWQ",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-algeria-stage-comeback-to-knock-jordan-out-of-fifa-world-cup",
          "image": "https://pixabay.com/get/gd2b823aa740f35512bbfd7ac94347e6f0c2d317cb62a589125293b58f4865e0dbacc46fe47d03dc9648134733be66df51644087b99cd1c39f46bc5280833d606_1280.jpg",
          "image_kind": "photo",
          "image_credit": "Pexels",
          "image_credit_url": "https://pixabay.com/users/Pexels-2286921/"
        },
        {
          "hour": 14,
          "time": "14:40 IST",
          "headline": "Injured Nitish Kumar Reddy to miss India's T20I series against England and Ireland",
          "what": "Nitish Kumar Reddy has been ruled out of India's upcoming T20I series against England and Ireland due to injury, dealing a blow to India's squad ahead of an important white-ball run. Reddy had established himself as a key all-round option for the national side and his absence will be a notable setback. The series against England and Ireland represents an important part of India's T20I calendar.",
          "lens": "Reddy's injury could reshape India's lower-order batting and pace-bowling options just as the team builds toward key T20I assignments — selection decisions will be closely watched.",
          "source": "Reuters",
          "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxOSlBMS1hzLTkyU2JPMmNqMWk1dkp3RVc4Vlp2cEFfeGphU2JrdExKbW5EZjIwM1pCdE5CNWlxX0VuYmZCRlRad3U3Njd6NzdPRE1YZVRPWEJfek12QU5kOThBV3BkN055NHZhMkZ6ZXpkYTZyQ0xpZWxFVXVqaHVKc1dVXzg2cEFOQ00zRTJ2SUttRXlqN3FabU9QcXBuS0tjNFMzSGpYQm1WQnlSNGNTbXR3",
          "breaking": true,
          "_hot": true,
          "slug": "20260623-injured-nitish-kumar-reddy-to-miss-india-s-t20i-series-against-england",
          "image": "https://upload.wikimedia.org/wikipedia/commons/1/1e/Nitish_Kumar_Reddy_BGT_2024_%28cropped%29_2.jpg",
          "image_kind": "photo",
          "image_credit": "WikiWanderer261 / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Nitish_Kumar_Reddy"
        },
        {
          "hour": 14,
          "time": "14:28 IST",
          "headline": "Rishabh Pant takes 44.4% pay cut to return to Delhi Capitals from LSG at IPL 2027 auction",
          "what": "Rishabh Pant has accepted a 44.4% pay cut to return to his original IPL franchise Delhi Capitals ahead of IPL 2027, moving from Lucknow Super Giants. The significant salary reduction underlines Pant's desire to return to Delhi, the franchise where he spent most of his IPL career and built his reputation as one of the game's most explosive batters. The move is one of the more striking transfer stories of the IPL 2027 auction cycle.",
          "lens": "A 44.4% pay cut from one of cricket's biggest stars signals that franchise loyalty and personal fit can still outweigh pure financial calculation even in the high-stakes IPL market.",
          "source": "Business Standard",
          "url": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxQNDB3WW91MnFCd3FWbkNES2JNbTEtUDlmU0lpcXlUNW9kNHJJU0V2eXUwelZnaHE1QmpJMng3V0xocV9BeGFaOEMxRlRxTUUwc0tkRUcyQkszNFVSUUZMRExzTlA4eFA3alpiMGJlcmtBVHE3SmZ6RUZZclI0Y0ZGeXRnd285c0t4b1RQNm50UjM2bFUwbXA0QjdnQmhHc3R1TTBONHhwNWtaMnhLUC1rZ0hvdUloNXNjVVZtMFhFQ3ZRRlUtaTVsdks1MXJKNzJSTHJMaUJn0gHWAUFVX3lxTFA0MHdZb3UycUJ3cVZuQ0RLYk1tMS1QOWZTSWlxeVQ1b2Q0cklTRXZ5dTB6VmdocTVCakkyeDdXTGhxX0F4YVo4QzFGVHFNRTBzS2RFRzJCSzM0VVJRRkxETHNOUDh4UDdqWmIwYmVya0FUcTdKZnpFRllyUjRjRkZ5dGd3bzlzS3hvVFA2bnRSMzZsVTBtcDRCN2dCaEdzdHVNME40eHA1a1oyeEtQLWtnSG91SWg1c2NVVm0wWEVDdlFGVS1pNWx2SzUxcko3MlJMckxpQmc",
          "breaking": true,
          "_hot": true,
          "slug": "20260623-rishabh-pant-takes-44-4-pay-cut-to-return-to-delhi-capitals-from-lsg-a",
          "image": "https://upload.wikimedia.org/wikipedia/commons/7/77/Rishabh_Pant.jpg",
          "image_kind": "photo",
          "image_credit": "Prime Minister's Office / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Rishabh_Pant"
        },
        {
          "hour": 13,
          "time": "13:28 IST",
          "headline": "Gavaskar pushes for one-month rest window in cricket calendar, links player rotation to 'cheapening' of game",
          "what": "Legendary India batter Sunil Gavaskar has called for a dedicated one-month rest period to be built into the international cricket calendar, warning that relentless player rotation is devaluing the game. Gavaskar linked the trend of rotating players in and out of squads to what he described as a 'cheapening' of cricket, arguing that constant churn diminishes both the status of selection and the quality fans see on the field. His comments come amid a hectic international schedule with multiple series overlapping.",
          "lens": "With Indian players juggling IPL, international fixtures across all formats, and rest rotations, Gavaskar's call for a structured rest window directly addresses the burnout and quality concerns that affect every Indian cricket fan.",
          "source": "The Times of India",
          "url": "https://news.google.com/rss/articles/CBMiqAJBVV95cUxQUGhzNkNiN0RxcWlPaHlPeDRyTHhsRVZ5R3ozUnRFeGwwSXctMTZnMVhINDdsZFU4WHVtQjlwRFVlejQ4c19yX1NvWlhLSHpYdVI4Y1lkWU54ckcyNFhOY1ZwbDFaVGZWdGtkY2NnVlJZOUFZSjNibUx5UkdEOUd2VDJ3c3ZyTkhrTUN1YWp3WVFmc1dweDY5U0dpU0QxdEJnSml4c2NWNVBMWXJ1VEpTWlBqZ0RQcEdkLUJoc2lEbWt3NWQyUTItTFZLbmQwVEhPMjlBM2RWaXZFUm9oTllkTGpDcVJZRWhuTTZtbHNPWWJ1ODhxdUYxU1A4LUU0amhXUlZUX3ZMSzlEOG9SeGJsRFVsUGVuemw3VGQ3ZzFyd0Z3RGtDOVlkNNIBrgJBVV95cUxPbnBpOEhVZ3V3Y1ptVXNSTy12U2NuTk55N1owZGdYTDAwVmxPMHR2UktaRlN0SHZyc3JCNVROLU94c3lRcnpqNkg2bUN1LVBBX1FCcmN2ZVdjcW54RjJIQ3VVVENlcnJ5bU9sR3kxVFhiR2M3cjh4Vk43MTZNUERSZ1NhQkRfdWE5T3hfeDJINDU0bGt6MEpjNUhmNGdkMXlxNzlRNnMxTmhRUU11cDlycU1SdjdmZ3JQcU12ZkpmR0EyLVU0Z19pNW9HNDhDX3ZqSTJTM2hCOWpKYXlqQnY5QVZJS1REZzRLUGRjWUFSMWVhNkRHYl9qdEhUZU5lUmNCeEdxQ196dEFHVmFBb3gwcVAyUWdOZFo2Zm53cThQdVVxTmJtclBKdEV4b3ItUQ",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-gavaskar-pushes-for-one-month-rest-window-in-cricket-calendar-links-pl",
          "image": "https://upload.wikimedia.org/wikipedia/commons/3/3d/Anu_Ranjan%2C_Amruta_Fadnavis%2C_Sunil_Gavaskar%2C_Shashi_Ranjan_graces_the_Gr8_Beti_event_%2802%29_%28cropped_-_Gavaskar%29.jpg",
          "image_kind": "photo",
          "image_credit": "Bollywood Hungama / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Sunil_Gavaskar"
        }
      ]
    },
    {
      "id": "entertainment",
      "name": "Entertainment",
      "stories": [
        {
          "hour": 21,
          "time": "21:06 IST",
          "headline": "Ranbir Kapoor's sweet gesture for wife Alia Bhatt's Alpha wins hearts",
          "what": "Ranbir Kapoor has won widespread appreciation online for a heartfelt public gesture in support of his wife Alia Bhatt's film Alpha, which is generating significant pre-release buzz. The moment, captured on video and shared widely, is being celebrated as a rare display of solidarity between two of Bollywood's biggest contemporary stars. Alpha, featuring Alia Bhatt, is one of the more anticipated upcoming releases in Hindi cinema.",
          "lens": "In a film industry where male stars rarely publicly champion their partners' work, Ranbir's gesture resonates as both a personal moment and a small but visible cultural shift.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi4gFBVV95cUxPU2ZOUmdKNjVqVVZPWnF1NUdnM1ZVT2dNWUloUjRpd2VwZlZCUUZ2MkYyWkRZYVdHQ0hkZVMyS3I5NElmYnNzdHZDTWx6WE84U200TVJfa1hzOUtFSm1jSFVGVkJTNWNEZFBwU2xERm1iRU5udVJuSTZCejk5WFo5eldsVndBZkVZdjM3TzBrNld2cUpyY3N0dGxHQ2NVbm9EYk5pVjFoZ2xfRzMxeGRUT0hWTFIyYWhuM0pPQUMwczhERDRFNjJ2b0d3Z1lVSV9KMmJEM083N3BrcW5ocFpvbDRR",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-ranbir-kapoor-s-sweet-gesture-for-wife-alia-bhatt-s-alpha-wins-hearts",
          "image": "https://upload.wikimedia.org/wikipedia/commons/e/e8/Alia_Bhatt_attends_at_the_2026_Cannes_Film_Festival_%28cropped%29_%28cropped%29.jpg",
          "image_kind": "photo",
          "image_credit": "Gabriel Hutchinson / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Alia_Bhatt"
        },
        {
          "hour": 15,
          "time": "15:39 IST",
          "headline": "South OTT and theatrical releases this week: Blast, Lingam and Ananthan Kaadu lead the lineup (June 22-28, 2026)",
          "what": "A strong slate of South Indian films is hitting OTT platforms and theatres this week, with Blast, Lingam, and Ananthan Kaadu leading the charge for the June 22-28, 2026 window. The week promises diverse offerings across Tamil, Telugu, and Malayalam audiences, spanning theatrical outings and straight-to-streaming premieres. It is shaping up as one of the fuller release weeks for South Indian content in recent memory.",
          "lens": "With multiple South Indian titles releasing simultaneously on OTT and in cinemas, fans across language communities have a genuinely packed week of new content to choose from.",
          "source": "Outlook India",
          "url": "https://news.google.com/rss/articles/CBMi1wFBVV95cUxPUEJlYjQ3Zm10Z3FteUNDVTk2aHZyS0hEdk9QYkxMSXZOcEhFYTJNdTFqVW90ZFZhem9URW9QMWVtUVY0TXZCSXhiQVcyNFo1dVRHME1OOVVFUzhYS2tZTUMtY3dFN3dJQk01RmZ0RF95Qnl2YThMSXJVMTVmbWQ4SGdBQWt4RG1NUEtuUElLTnlVcXlwVVRVb3BHN1VXTDdDQ1VScWJyMUowTFE5aUFRei1QVzBjTTRFaENHZWVFdkpRb0p3ejlOcTgxNlRtbjZrajFjalJNOA",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-south-ott-and-theatrical-releases-this-week-blast-lingam-and-ananthan",
          "image": "https://pixabay.com/get/gbd9ac530ab6477b6e271a71e5474ad6048bfa850fb524fd1fe5adb654e515463d521743e682a130974bdf1b9b2cbbb51d8093e1c97126420ae3523e304a622fb_1280.jpg",
          "image_kind": "photo",
          "image_credit": "StefanCoders",
          "image_credit_url": "https://pixabay.com/users/StefanCoders-11782809/"
        },
        {
          "hour": 14,
          "time": "14:35 IST",
          "headline": "Ram Kapoor hugs Ekta Kapoor, addresses their public feud: 'It's nobody's business'",
          "what": "Actor Ram Kapoor and television mogul Ekta Kapoor have publicly buried what appeared to be a long-standing rift, with Ram embracing Ekta and telling the press that the details of their dispute are 'nobody's business'. The gesture, captured and widely circulated, effectively draws a curtain over what had become a topic of public speculation. Both figures are giants of Indian television, making their apparent reconciliation a significant moment in the industry.",
          "lens": "Ram and Ekta Kapoor together shaped a generation of Indian prime-time television, so their public reconciliation closes a chapter that had cast a shadow over both their legacies.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi3gFBVV95cUxPWUR2LXk0VWw2ZGxDMzhFb204UnRoRkxaNWpWLUtvajRCQV9Wemk5WC1wSnI0LTlxT05RRE1mQXpfOTFLSDNhbHo4eG55d0FndnJ6ZE1lbUxhMnFLWVJScThTTlZKaGJtSVlKc0dCdHQ5VTducmpISnJtZm8yblZ5U2hfM1R1YWdEZ0JVM01BWUxyRWlXR0tLQjZBZ3UtXzFIQTZ5QTRCSjhTSkJTVTFRWlkwR094SmlueFZoczBhZjFtMEN0ck00NEdKdW5mTzZUU2NaMl83TnhOOHJBM3c",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-ram-kapoor-hugs-ekta-kapoor-addresses-their-public-feud-it-s-nobody-s",
          "image": "https://upload.wikimedia.org/wikipedia/commons/f/f7/Ekta_Kapoor_in_2025.jpg",
          "image_kind": "photo",
          "image_credit": "Deepak / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Ekta_Kapoor"
        },
        {
          "hour": 13,
          "time": "13:32 IST",
          "headline": "Tamannaah exposes disturbing gaze female actors face in South cinema: 'Not complimentary'",
          "what": "Actress Tamannaah Bhatia has spoken out about the unsettling male gaze that women in South Indian cinema routinely face, calling it far from flattering or complimentary. In a candid interview reported by The Indian Express, she described the experience as deeply uncomfortable, lending her prominent voice to a growing chorus of women in the industry demanding better treatment on and off screen. Her remarks arrive at a time of heightened scrutiny of gender dynamics in South Indian film industries.",
          "lens": "When a mainstream star of Tamannaah's stature names the problem publicly, it puts pressure on a South film industry still processing the fallout of the Hema Committee report's uncomfortable revelations.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi5AFBVV95cUxOT2hjOV9sRU94a1hqQW0zem8zem9sSXFoWHRnYlpFeW9IQ2VWRzVTSGxWSy1ybXdLcFRVUGdwYVN2bVV2S3lQLWl4a1hhcTl3ZVFxVFR5OE5kemxSdjY0SzluQUlKZWJpOFVrV1ZnMVVWNGdJU0VLakt3WDB1UHpjYVRKYlF5YmVJYTZwTjVISm83NW5kQmNtV1FkZVpIZVcyVzNUeHF0ODNaNVBacmsxc0tiVmE2S0xaTlJoSjVRbXhWMW9KZVVGYTF0anhXTERaWWs4dVVDR1p6cS1jcjlQVjdkaHU",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-tamannaah-exposes-disturbing-gaze-female-actors-face-in-south-cinema-n",
          "image": "https://upload.wikimedia.org/wikipedia/commons/6/60/Tamannaah_Bhatia_at_a_song_launch_from_the_film_Vedaa_%28cropped%29.jpg",
          "image_kind": "photo",
          "image_credit": "Bollywood Hungama / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Tamannaah_Bhatia"
        },
        {
          "hour": 11,
          "time": "11:45 IST",
          "headline": "Tamannaah Bhatia net worth: The Rs 120 crore fortune behind Bollywood and South cinema's biggest names",
          "what": "A detailed profile by The Economic Times has put Tamannaah Bhatia's net worth at Rs 120 crore, breaking down the actress's wealth across luxury cars and a substantial real estate portfolio. The figure reflects decades of consistent work across Telugu, Tamil, and Hindi cinema, as well as brand endorsements and digital projects that have made her one of the most financially successful actresses of her generation. The profile arrives alongside her vocal comments on gender dynamics in South cinema.",
          "lens": "At Rs 120 crore, Tamannaah's wealth profile shows how a female actor who built her career across multiple South Indian industries — rather than staking everything on Bollywood — can accumulate significant financial independence.",
          "source": "The Economic Times",
          "url": "https://news.google.com/rss/articles/CBMilAJBVV95cUxOeUJTcU1PWjNtbm1kTnhIeG9yeVdPeUhacTBKajhxSmZJWThJeGxIRFl4NmtpOHpGVndCS1JlUk1yNFktQ0lzRGtnLUgwX2pCN3VsZXdjMkdLSGpEVzk4ckVSMFVOdzg4MFFDZ09peUliT2NvcmtMczdQaVNjalh0QVp3cXptSzVXaVlrVHo1SzFhV1Z3ZFFfMXl3TUowTDFrc0E1eFZ1RTlRTXZYTVBGWjBrUTIzallUcnk2UVpSWE93bHItWE0tcHg1anl0YktfRlE0UXh4eFNHUFUwQnZwbEI5c0lOLUlOTkY4b01kbjRtN3pSd3RHLUlOQXRlUkdYYmdvNzhRemRoWXpWNlltaUJsOFI",
          "breaking": false,
          "_hot": false,
          "slug": "20260623-tamannaah-bhatia-net-worth-the-rs-120-crore-fortune-behind-bollywood-a",
          "image": "https://pixabay.com/get/g15fe877d37b99141cd3a3919e54946335aa87e611068d7e56143f5bf97819e8b7fe4a7ccb014cca3c9e2af9d9d5868924f7b481bab94f20e5955d3f8a4715fc1_1280.jpg",
          "image_kind": "photo",
          "image_credit": "GregoryButler",
          "image_credit_url": "https://pixabay.com/users/GregoryButler-331410/"
        }
      ]
    }
  ]
};
