// auto-generated 2026-06-22 10:45 IST
window.BRIEF = {
  "date": "Monday, 22 June 2026",
  "edition": "2026-06-22 10:45",
  "topline": "Keir Starmer teeters on the edge of resignation as Britain's political crisis deepens, while Anthropic scores a double win — shedding its national security label under Trump and poaching Nobel laureate John Jumper from Google DeepMind.",
  "lensLabel": "Why it matters",
  "sections": [
    {
      "id": "world",
      "name": "World",
      "stories": [
        {
          "hour": 22,
          "time": "22:20 IST",
          "headline": "Over 2 Million Indian Students Resit NEET Medical Entrance Exam After Alleged Paper Leak",
          "what": "More than 2 million Indian students were made to resit the NEET medical entrance examination after allegations emerged that the question paper had been leaked ahead of the original test. The re-examination represents one of the largest such exercises in India's recent history, affecting aspirants nationwide who had already sat the high-stakes test. The NEET controversy has triggered widespread outrage among students, parents, and opposition politicians, putting intense pressure on the central government over the integrity of the country's most critical medical admissions process.",
          "lens": "For millions of Indian families who spend years and lakhs of rupees preparing for NEET, a forced re-sit due to a suspected paper leak strikes at the very heart of fair opportunity in medical education.",
          "source": "The Guardian",
          "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxQeDFIa1U1d2dXVlBsdzFjZ2U0T19tMmxCZnZJWXJfOXpuMGVyX3FwRU80ZGl0YTlUbmVLWTF0d3lQUElQc2RhaVhJb1ZhVWNsTnlVbF9GQnBPU09JanhlSTU3NW9PYnlYb0JCRElGdHB2Vmx2TWtDalpRaWtybEV5V0wyZ2RkN3lsX0U2NGZ0RmVhdktQN0hud3hDeFlMbnV3X2QwS3puOWJmVlJPaVBNdVpSSF9mS21KRmZwU1R3?oc=5",
          "breaking": false,
          "slug": "20260622-over-2-million-indian-students-resit-neet-medical-entrance-exam-after",
          "image": "https://images.pexels.com/photos/6683393/pexels-photo-6683393.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Andy Barbour",
          "image_credit_url": "https://www.pexels.com/@andy-barbour"
        },
        {
          "hour": 20,
          "time": "20:54 IST",
          "headline": "Trump Says Keir Starmer 'Failed Badly' and Will Resign as UK Prime Minister",
          "what": "US President Donald Trump publicly declared that UK Prime Minister Keir Starmer has \"failed badly\" and predicted he would resign from office, adding international weight to growing domestic pressure on the Labour leader. The comments from Trump come amid a turbulent period for Starmer's government, with falling poll numbers and controversy over several policy decisions. Trump's intervention — however unsolicited — is likely to further energise Starmer's political opponents in Westminster.",
          "lens": "When the US President publicly predicts a sitting British PM's resignation, it signals serious turbulence in a key bilateral relationship that directly affects global trade and security arrangements India watches closely.",
          "source": "NDTV",
          "url": "https://news.google.com/rss/articles/CBMizAFBVV95cUxQUGFLN3FUNzl2cktRTzBDMGoxeVNGeXFENmdnMXozVFhrTlBzTU93a3RLR2x4SThzMkhjOGlSbWJqTTdlNUh2d2s5d3p1OFFCOVh6NGI4RjZuUHFFVFdkZVV6bjVEQWR6LW9aUmQxUENFbERuZTlMRXdremczTGN0VmZuaWZYaUJXUUxGWG1fQ3VMYVk1a0UwdjU3Ymd0cVhJRExpeXcxckNvNXNkQ29zN3FvUHVaV3ljNXNYcWhHQlhaSFg0amxWbll4Y1XSAdQBQVVfeXFMUHJZZXhJNnJGWHJhSEdjWEdPOFhfbl9ndVp1MmJEM0l4MldXNFNEcHNTUTJpZFRqZHFhN29Ta3Z4c1R5YW5fd0Y1Ykx4M0xmWW4wSjZhUzUya1dYR21DRll0YWFRdEVsaHhNQTZXcEs4LTNucWotV3VKMFZfTG1vb0o2ZmNDN0VUWHQ3WTBDeG9oQnJ0Sll4cXVDaEdfdVJwRGZvY3p2LUVGbnZIazlkTXJyeWJZYm9ieXpQY0c1WWJqUERBV2xMeTFRb0JZaHlpbkF2RVY?oc=5",
          "breaking": false,
          "slug": "20260622-trump-says-keir-starmer-failed-badly-and-will-resign-as-uk-prime-minis",
          "image": "https://pixabay.com/get/g9956e450e612cae1abc5858f1ea099f325fbd3a07fe9b86809514905817af0da60b3f3292d8d05183cc32a5d034edbf7b2dc21f3843992959d0e284511317983_1280.jpg",
          "image_kind": "photo",
          "image_credit": "vjkombajn",
          "image_credit_url": "https://pixabay.com/users/vjkombajn-764634/"
        },
        {
          "hour": 20,
          "time": "20:54 IST",
          "headline": "Trump Predicts Keir Starmer Will Resign as UK PM Faces Mounting Pressure",
          "what": "US President Donald Trump has publicly declared that UK Prime Minister Keir Starmer will resign, saying he has 'failed badly'. The remarks arrive as pressure on Starmer is intensifying at home over a combination of economic headwinds, public discontent, and political missteps in the early months of his Labour government. Trump's intervention, characteristically blunt and globally amplified, adds an unusual layer of external pressure on a sitting British prime minister.",
          "lens": "Trump wading into British domestic politics signals how his unpredictable commentary is reshaping the diplomatic norms between the US and its closest allies — and could complicate India-UK trade talks that depend on a stable British government.",
          "source": "NDTV",
          "url": "https://news.google.com/rss/articles/CBMizAFBVV95cUxQUGFLN3FUNzl2cktRTzBDMGoxeVNGeXFENmdnMXozVFhrTlBzTU93a3RLR2x4SThzMkhjOGlSbWJqTTdlNUh2d2s5d3p1OFFCOVh6NGI4RjZuUHFFVFdkZVV6bjVEQWR6LW9aUmQxUENFbERuZTlMRXdremczTGN0VmZuaWZYaUJXUUxGWG1fQ3VMYVk1a0UwdjU3Ymd0cVhJRExpeXcxckNvNXNkQ29zN3FvUHVaV3ljNXNYcWhHQlhaSFg0amxWbll4Y1XSAdQBQVVfeXFMUHJZZXhJNnJGWHJhSEdjWEdPOFhfbl9ndVp1MmJEM0l4MldXNFNEcHNTUTJpZFRqZHFhN29Ta3Z4c1R5YW5fd0Y5Ykx4M0xmWW4wSjZhUzUya1dYR21DRll0YWFRdEVsaHhNQTZXcEs4LTNucWotV3VKMFZfTG1vb0o2ZmNDN0VUWHQ3WTBDeG9oQnJ0Sll4cXVDaEdfdVJwRGZvY3p2LUVGbnZIazlkTXJyeWJZYm9ieXpQY0c5WWJqUERBV2xMeTFRb0JZaHlpbkF2RVY?oc=5",
          "breaking": false,
          "slug": "20260622-trump-predicts-keir-starmer-will-resign-as-uk-pm-faces-mounting-pressu",
          "image": "https://images.pexels.com/photos/37477812/pexels-photo-37477812.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Joshua Santos",
          "image_credit_url": "https://www.pexels.com/@joshua-santos-1174893"
        },
        {
          "hour": 9,
          "time": "09:16 IST",
          "headline": "Keir Starmer Said to Be on the Brink of Resignation as UK Political Crisis Deepens",
          "what": "British Prime Minister Keir Starmer is reportedly on the verge of resignation, with an announcement expected imminently, according to NDTV. The development signals a dramatic collapse of Starmer's Labour government less than two years after it swept to power with a historic majority in the 2024 general election. The news has sent shockwaves through Westminster and raised urgent questions about the future of British political leadership.",
          "lens": "A change in UK's top leadership has direct implications for India-UK relations, including the ongoing Free Trade Agreement negotiations and the Indian diaspora's status in Britain.",
          "source": "NDTV",
          "url": "https://news.google.com/rss/articles/CBMirAFBVV95cUxQX0k3cjNsdUZUUVFWS0ZpTEZjV0RGSElhT3hwcHBWcXpnRDN3WWxyM2dQTURRc3BEN0tJN3JOR1AtRng2VlFRTlhOY1JzTkNxcGRFcko0ZzBGdVExbG9aQXh3TWU4XzAwSWVOYzVkaWE5Z3YwNUVnbXVqZVNYMVl3eDlXcWRqSXZ5SVFYWlZBMjNOYmw0R18waGttMHhwdWxhYmc0ZWtkamk5MEFz0gG0AUFVX3lxTE5fTjQzNk9jSkVscFBuem5HcGdMaXlIVHVQX05RWmhpaUtGTk1jWmhXMGdxZW1TLWZLY1cwc3E0MHhCY0VPaXoxUlZsNGNMMERlM3VWSmVIV3ZXTmoxWFBraUNCXzNpTWQ2Q29sX1dwd01DeFV3MjNLMFkzcFBvRS1lUWxHWUZod3BGczdZVXVkZDhJS191YTNyb01WVDdEYm12azNaSk9TUU1MclROSnZnbnVmdg",
          "breaking": true,
          "slug": "20260622-keir-starmer-said-to-be-on-the-brink-of-resignation-as-uk-political-cr",
          "image": "https://upload.wikimedia.org/wikipedia/commons/9/91/Prime_Minister_Keir_Starmer_Portrait_%28cropped%29.jpg",
          "image_kind": "photo",
          "image_credit": "Prime Minister's Office / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Keir_Starmer"
        },
        {
          "hour": 7,
          "time": "07:24 IST",
          "headline": "US-Iran Nuclear Talks End in Switzerland Without Deal; Technical Negotiations to Continue",
          "what": "A fresh round of US-Iran nuclear negotiations concluded in Switzerland without a breakthrough agreement, with both sides indicating that technical-level talks would continue. The latest diplomatic session was part of ongoing efforts to revive a nuclear deal that would curb Iran's uranium enrichment programme in exchange for sanctions relief. The inconclusive outcome keeps global oil markets and regional security in a state of uncertainty.",
          "lens": "Iran is a major oil supplier and India is one of its biggest customers — any breakdown or breakthrough in these talks directly affects Indian crude import costs and energy security.",
          "source": "Business Standard",
          "url": "https://news.google.com/rss/articles/CBMi0gFBVV95cUxOV0ptQVkzMEpPSFoyT0Z0YU5aZ1dGNlRkYS1qM0hSRnlqTXhZdUpNLXdyZ0hGQW1OSzIzUEtlMnlXX3JtaEhQVWJybHF2bnItZmxVaGpST1o3MFVPUGt4Mzk1dFdEUXJUQzlBczl2UlFoclp5dEFpQWE3R2g0ZXlScThyMnlwTU9SbmE4bmtZTWxqV2tiOHJ1b2ZyMkw0ZXlrZldYa05yb1BlSWJXcTZJSWhyWGZ5Z3N5dHZScjhacTVVbnZxeVhQTzFHRGt2Mi1pLUHSAdIBQVVfeXFMTldKbUFZMzBKT0haMk9GdGFOWmdXRjZUZGEtajNIUkZ5ak14WXVKTS13cmdIRkFtTksyM1BLZTJ5V19ybWhIUFVicmxxdm5yLWZsVWhqUk9aNzBVT1BreDM5NXRXRFFyVEM5QXM5dlJRaHJaeXRBaUFhN0doOGV5UnE4cjJ5cE1PUm5hOG5rWU1saldrYjhydW9mcjJMNGV5a2ZXWGtOcm9QZUliV3E2SUloclhmeWdzeXR2UnI4WnE1VW52cXlYUE8xR0RrdjItaS1B",
          "breaking": false,
          "slug": "20260622-us-iran-nuclear-talks-end-in-switzerland-without-deal-technical-negoti",
          "image": "https://pixabay.com/get/gbba8bf4bb617f78458313eecf70d6693507f5f1d9491170b557d9144aa2835b19e4b2e1e647f03fa788d3bc5bf58327d5bbac73cd22618128b7b33ee741bc47f_1280.jpg",
          "image_kind": "photo",
          "image_credit": "995645",
          "image_credit_url": "https://pixabay.com/users/995645-995645/"
        }
      ]
    },
    {
      "id": "business",
      "name": "Business & Markets",
      "stories": [
        {
          "hour": 23,
          "time": "23:30 IST",
          "headline": "India may seek sunset clause in U.S. trade pact amid tariff concerns",
          "what": "India is considering pushing for a sunset clause in any trade agreement with the United States, according to Business Standard, a provision that would allow the deal to be reviewed or expire after a fixed period. The demand reflects Indian negotiators' concerns about locking into long-term tariff commitments with the U.S. in a volatile trade environment. A sunset clause would give India flexibility to renegotiate terms if geopolitical or economic conditions shift significantly.",
          "lens": "A sunset clause would protect India from being permanently bound to unfavourable terms, giving future governments room to renegotiate — a safeguard that matters for sensitive sectors like agriculture and dairy.",
          "source": "Business Standard",
          "url": "https://news.google.com/rss/articles/CBMi3gFBVV95cUxPcUFxUnBKNTNxRzNFOVFEQW1aQmhaWFJNSVczSlgwX0R6UVpQeFVnRnNCMWE0VUJDTm5KYkRDU3k2XzU2TVdYZ3NET3NRaHJPUU54eFFkNHRvWExGb0pyN3ViLWJ5ckZHWDdjRGpuY3NMN0RnNXM1QjNVcW16YTBqZjAzT01YWm1McXNkVEFKcDBnNjB3ZnFaZWtWSTYyWUtUam82NE43ejJGRHlPQ1U3WjVJYTV4aHhRWWhObVBmbVN3RnZxUGRVcVRpMHkzQXRjbkQzRkxfZkkydkhNblHSAd4BQVVfeXFMT3FBcVJwSjUzcUczRTlRREFtWkJoWlhSTUlXM0pYMF9EelFaUHhVZ0ZzQjFhNFVCQ05uSmJEQ1N5Nl81Nk1XWGdzRE9zUWhyT1FOeHhRZDR0b1hMRm9Kcjd1Yi1ieXJGR1g3Y0RqbmNzTDdEZzVzNUIzVXFtemEwamYwM09NWFptTHFzZFRBSnAwZzYwd2ZxWmVrVkk2MllLVGpvNjRON3oyRkR5T0NVN1o1SWE1eGh4UVloTm1QZm1Td0Z2cVBkVXFUaTB5M0F0Y25EM0ZMX2ZJMnZITW5R?oc=5",
          "breaking": false,
          "slug": "20260622-india-may-seek-sunset-clause-in-u-s-trade-pact-amid-tariff-concerns",
          "image": "https://images.pexels.com/photos/30839695/pexels-photo-30839695.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Markus Winkler",
          "image_credit_url": "https://www.pexels.com/@markus-winkler-1430818"
        },
        {
          "hour": 23,
          "time": "23:58 IST",
          "headline": "Mega FTA wave to bring 60% of India's trade under preferential regime",
          "what": "A sweeping wave of Free Trade Agreements being pursued by India is set to bring 60% of the country's total trade under a preferential tariff regime, according to The Economic Times. India is simultaneously negotiating or concluding deals with the United States, the European Union, the United Kingdom, and the Gulf Cooperation Council, among others. The shift marks a fundamental change in India's historically cautious approach to free trade.",
          "lens": "If 60% of India's trade moves to preferential tariffs, everyday imported goods from electronics to food could get cheaper, while Indian exporters gain a structural edge in global markets.",
          "source": "The Economic Times",
          "url": "https://news.google.com/rss/articles/CBMi6wFBVV95cUxPVnZxSl81SFRmMFpGYzE1UFlUMHd3dmxHWkltd0lGZEUxTWxPQ3hYM09DSHNxMWV2MmZSVnpheDdYNERoTU5qc0NBNU9GclhaT19GWExaeVVRRDdlR2R0YzRGOEtERTNEN1dvV1FROEdIRHFycGxqMHk2R0pCbjQyUjNSMkJ4aC1XZzhUelRaX19hQmRmTlJvNDlCSHIxbU90R1BFcWpRVU9MZmtpaG4zczVLTklGRnhjNFc3NXJOalpzUk95eF8wckNWcXdfWHhTdERBNFlSZ0J5MTY4V293Zk82emNoLU5zMlFz0gHwAUFVX3lxTE9Ha0xFTkZxdXg1S3c4aTdBOGU1WFhuSndXYTJ3NE5nVEg3VUdEaFpvbm5pRjVHZmpmRkxxNUtCS3UxMlI3YVJJazlqcWN1VE91NEsySXBnRzdpWGRKX0xPMEJoYlhZOVZxcDJ1YjVfV3BSaXMyY3RuMXJqZThreXpkcG5EcFpwbWNCSTZtcURjRnc4LXZLNElkcFJ3UTZMR3ktWkZ0WFlXZVFQZDNmTnlmYUhVVUpnS0hCVkZpeUxNRm9Da3djdkRORWhUWk95SlZzNzlGSnBJMERUYzRyVzRKVGh2S2tQT2tMUzQyRmRjRw?oc=5",
          "breaking": false,
          "slug": "20260622-mega-fta-wave-to-bring-60-of-india-s-trade-under-preferential-regime",
          "image": "https://pixabay.com/get/g360e5b34c890fb1073433ac8e4c5373067ddebc6bd50d34196b580a8a01ea7467b455738f3a14b0ec2119f1a28947679_1280.jpg",
          "image_kind": "photo",
          "image_credit": "Simon",
          "image_credit_url": "https://pixabay.com/users/Simon-3/"
        },
        {
          "hour": 22,
          "time": "22:30 IST",
          "headline": "India's dependence on services exports is rising as trade composition shifts",
          "what": "India's export mix is undergoing a structural shift, with the country becoming increasingly dependent on services exports relative to merchandise goods, according to an analysis by Business Standard. Services — led by IT, business process outsourcing, and financial services — now account for a growing share of India's total export earnings. While this reflects India's competitive strengths, it also raises questions about the resilience and diversification of the export base, particularly as goods exporters face tariff headwinds globally.",
          "lens": "Rising services export dependence means India's economic fortunes are increasingly tied to global demand for IT and outsourcing — a key concern for the millions employed in those sectors.",
          "source": "Business Standard",
          "url": "https://news.google.com/rss/articles/CBMi0wFBVV95cUxQVk1QUjFPVndfRHhqY2xFSVJaaVlINjBJblljTFliUGJyWTVMa2RzUkZVa21veExYbURpOFZDRUFIbVZiWXBjVUFmNkhnSnVZZGxyM05UUTc1RXdZNDV2T3o5THd3eEdQMDVuaEU0MGRORGFvQ2R2a192amVZYWV0bVNNS0NnenNIb1liNVlMbkxsaUk1ZG9sRmRBMzM2SHZnZ3E5aTNmS3oxUS1HWGxFYko2N0RKQTQ0VGljUkxCSjdXZzI5SkNsc1lJV1pIWkpmSk5v0gHYAUFVX3lxTE5UQjdSTmpiLXpNWmFJLWl4VUlFU2ZvekpjRW05NE1rZEZzQUQzWkhCeEg4Xzd2S2w3enZQdlRHeGZQNmtSM0k0d05HSFBfM1RjOTJpd3NzSlJnQXJuczBoVUtnZjBGbFRERkw3Z2RBMHNwN25ERHBpOFc5dWppUDhHR3pTdEgxdDBSVHVKTFdTQ3VrUHpUVEVrODNKRzlwQUZIaHNraVJCaUc0RlBqOTJhSjJzOUtwTkFtbk1VMS14SDBzbUo4eWV2UVBHSEROV0hHZTJhNkl5eQ?oc=5",
          "breaking": false,
          "slug": "20260622-india-s-dependence-on-services-exports-is-rising-as-trade-composition",
          "image": "https://images.pexels.com/photos/28185416/pexels-photo-28185416.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Md Sihabul Islam",
          "image_credit_url": "https://www.pexels.com/@md-sihabul-islam-750002427"
        },
        {
          "hour": 21,
          "time": "21:34 IST",
          "headline": "Modi-Trump bilateral at G7: Trade, tariffs and trust dominate as India-U.S. reset gathers pace",
          "what": "Prime Minister Narendra Modi and U.S. President Donald Trump held bilateral talks on the sidelines of the G7 summit, with trade, tariffs and strategic trust forming the core of the agenda. The meeting comes at a critical juncture as the two countries race to finalise an interim trade deal ahead of the expiry of a 90-day tariff pause. The discussions signal a concerted effort by both sides to stabilise a relationship that has been strained by Washington's sweeping reciprocal tariff regime announced earlier this year.",
          "lens": "The outcome of Modi-Trump talks directly affects tariffs on Indian exports worth billions of dollars, with knock-on effects on jobs and prices across Indian industries.",
          "source": "India Today",
          "url": "https://news.google.com/rss/articles/CBMi3gFBVV95cUxPVnM1VDJEazh1ck9uYUtNNi1NbG12Q3plOG9nOXNJVTdtb1VER25HZUtDeGdweHlqWFpvRXcwNl9FaVRHUU1tR0hkNHdSSXpXZ1ptaVZ4ZUUzLVBqNnNIN29XMTk1ckdoWVlpa1l4SF9TV3RBdU45anFfczFUaTVsb3p3S2pfTVZOLVR3MFVIWXdyeGhVSFJwS0JTMUVFM3ZXaE9uY04wdjdUSFJfSGxNZThUTk90TU9EMUI1b0RBdXk5dnpWT1pYVlpfcHRmZDFlejBBX3cxbEN0Q0xYWXfSAeMBQVVfeXFMUFBrblR4RDUxUy1KR2ktMXl4R0dZeDhOejA1T0VDNF80MzcwdFExT0lxQ2E2ckRtRklIelI1WC1Lc241MGRUaFdDaW44VjJUMVZRR0NHQnRHb2dkUHFGQTVqUEk5YmgzVVpfdDcxd3pnVzZnQkU1THJXSk52VjFucnhLM1Z4ejdRX2FlOW12TWpLTnlSQUd3VWNqR3RwWmp6VEd0cW9KdUI5MnQ0UUhZNmZyb18zRm1GYkZjRXlWMEt2NVlGbGhNOTZ5VGE3R0pNOGFKTmdtc3VKUUlPRGUzM1Q4UWc?oc=5",
          "breaking": false,
          "slug": "20260622-modi-trump-bilateral-at-g7-trade-tariffs-and-trust-dominate-as-india-u",
          "image": "https://images.pexels.com/photos/30855417/pexels-photo-30855417.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Markus Winkler",
          "image_credit_url": "https://www.pexels.com/@markus-winkler-1430818"
        },
        {
          "hour": 18,
          "time": "18:51 IST",
          "headline": "India-U.S. interim trade deal needs only 'final touches'; Greer to visit New Delhi on June 23-24",
          "what": "The India-U.S. interim trade deal is nearly complete, requiring only 'final touches' before it can be signed, with U.S. Trade Representative Jamieson Greer scheduled to visit New Delhi on June 23-24 to advance negotiations. The visit signals that both sides are in the home stretch of a bilateral trade agreement that has been in the works for months. The deal is expected to lower tariffs on select Indian exports to the U.S. while opening Indian markets in key sectors.",
          "lens": "A finalised India-U.S. trade deal could shield Indian exporters from the steep reciprocal tariffs imposed earlier this year, directly affecting sectors like textiles, pharmaceuticals and IT services that employ millions.",
          "source": "The Hindu",
          "url": "https://news.google.com/rss/articles/CBMi5AFBVV95cUxPTHZCVHcyQjU1UUo5eWdqTGpqb29wSUQ2eXF5THF5S2x6WExCamllLUJDOUVCVFpMZmo3Q3ptV0hVZ1JEVlFPSy1zLVA2SGtpUmJyUGpvcmVmUFhWZ2dIRGFIeHY0SFhQYW42TXN4SFE4NFRuU0I0WWZObkxBSEdhanUtVzg5b3hkNE5keDctb1c5U2VFNHc2WFBHdndib1B0Z0I0cENDUXg0VXVoOHdpVVpsalVKSDVBcVFULUY5TERiY3RleE82SGI1YXdFdGQ0b09jVWpBeWpUMlIxVmxYVS1SYTjSAesBQVVfeXFMTWw0dDRzQ2dPV2pabUtTblNIellmS2tzblhaTjh2Z01DLV9NdDVNMlQ2MGNmTGdiSVlMTkJ0eTBaMUtVSmRCV0lPQlJDLU42SmFxOVpNOUJsUUtQeUVkaGpleC1PeUZfdHl6Tmo0bmgtem93NTRDRkk4Y25ZSHU3aHRtdGlLVC1WNi1MSkw3QVlqVmlaNkhVeVMyWkptR1ZueWctV0VNMGdHZlBjZzZuR0gwOTVlb3BpQ29sSXVJbnFUMmI2VWZmbkZyenZZbUFtZVpVZkxlQ0NSZXFZWVkwODNBSWYyTm9YM0t1TQ?oc=5",
          "breaking": true,
          "slug": "20260622-india-u-s-interim-trade-deal-needs-only-final-touches-greer-to-visit-n",
          "image": "https://upload.wikimedia.org/wikipedia/commons/b/bb/Official_portrait_of_U.S._Trade_Representative_Jamieson_Greer_%28cropped_2%29.jpg",
          "image_kind": "photo",
          "image_credit": "Office of the United States Trade Representative / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Jamieson_Greer"
        }
      ]
    },
    {
      "id": "tech",
      "name": "Technology",
      "stories": [
        {
          "hour": 23,
          "time": "23:41 IST",
          "headline": "West Asia conflict squeezes startup funding routes for Indian firms",
          "what": "The ongoing conflict in West Asia is tightening funding options for Indian startups, as investors from the Gulf region — a growing source of venture capital for India — grow cautious amid regional instability. Business Standard reports that the geopolitical turbulence is disrupting capital flows at a time when Indian startups were increasingly looking to Middle Eastern sovereign and family-office money to diversify away from traditional US and China-linked funds. The development adds another layer of uncertainty to an already challenging fundraising environment.",
          "lens": "Gulf money had emerged as one of the freshest and fastest-growing pools of capital for Indian startups; if that tap tightens, founders at all stages will find fewer options and likely face tougher valuation terms.",
          "source": "Business Standard",
          "url": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxPRmRqaV93eEd6dWowLWgtdlZET296NFZyaE5EVHR5WmZuaTYtVjFFdU1tLTIwTEFBYURwdVlwT2poaDZjeUxoZEs1Qk5zV2JlYzJOZ3UyZER2T1g2QnJ3dmR0MjBXQ19QQmZoVHNBNTBBb3lnRnVpZzh6RUdtSFVJMnJ0NGtyZjRnYzVCVkFTaGdlNGQ0dnV5dHFLbzl3X2QyVTZaZU1RNnRJUHVtU1dfamMzZU1nQmxLSC1VUWdnbWdEUmJ1aHkyedIBzgFBVV95cUxPcUdSS1VRVi03R0luaDhKb2dmaEM4ek1JalVGbXBBU2g4THdsN2N0Z3RhT2ZDNzk4QVBmUzJtRGtXZHJEUVpWXzh0WkJscW5WSkVjVmFJaGJBdURRYkNXNUdaTG0yS3RmNEVJZFUzSWdxSDdCd1k5Zi15U202WTA5THI2bnJLQTRYdGh0MHUzeVN4NHdBeWdOUXBOT0had196MlJoanhDZW1HQW9XaDNVUWUwQVJuVW9Ua0gtNHNTZzlqanlPZkxYUkY5bUUwdw",
          "breaking": false,
          "slug": "20260622-west-asia-conflict-squeezes-startup-funding-routes-for-indian-firms",
          "image": "https://pixabay.com/get/g2d652ac7fbbbbe2dc630de2b8790c2419a960851f774dce4f93056163edae1594c41ed088c778ff91359d056e50cb1e7c63d023b3c6a63e69c51aecaad633199_1280.jpg",
          "image_kind": "photo",
          "image_credit": "Tumisu",
          "image_credit_url": "https://pixabay.com/users/Tumisu-148124/"
        },
        {
          "hour": 23,
          "time": "23:41 IST",
          "headline": "West Asia Crisis Drags Indian Startup Funding Down 43% Year-on-Year Since March",
          "what": "Global geopolitical turbulence stemming from the West Asia crisis has hit Indian startup funding hard, with investment volumes falling 43% year-on-year since March, according to Business Standard. The sharp decline signals that international investor risk appetite has contracted significantly, with funds pulling back from emerging-market bets amid war-driven uncertainty. The drop marks one of the steeper funding contractions seen in the Indian startup ecosystem in recent memory, coming even as inflation and interest rate pressures had already tightened venture capital globally.",
          "lens": "A 43% funding collapse means fewer Indian startups can raise capital to grow, hire, or survive — affecting jobs and the next wave of consumer products millions of Indians use.",
          "source": "Business Standard",
          "url": "https://news.google.com/rss/articles/CBMizgFBVV95cUxPcUdSS1VRVi03R0luaDhKb2dmaEM4ek1JalVGbXBBU2g4THdsN2N0Z3RhT2ZDNzk4QVBmUzJtRGtXZHJEUVpWXzh0WkJscW5WSkVjVmFJaGJBdURRYkNXNUdaTG0yS3RmNEVJZFUzSWdxSDdCd1k5Zi15U202WTA5THI2bnJLQTRYdGh0MHUzeVN4NHdBeWdOUXBOT0had196MlJoanhDZW1HQW9XaDNVUWUwQVJuVW9Ua0gtNHNTZzlqanlPZkxYUkY5bUUwd9IBzgFBVV95cUxPcUdSS1VRVi03R0luaDhKb2dmaEM4ek1JalVGbXBBU2g4THdsN2N0Z3RhT2ZDNzk4QVBmUzJtRGtXZHJEUVpWXzh0WkJscW5WSkVjVmFJaGJBdURRYkNXNUdaTG0yS3RmNEVJZFUzSWdxSDdCd1k1Zi15U202WTA5THI2bnJLQTRYdGh0MHUzeVN4NHdBeWdOUXBOT0had196MlJoanhDZW1HQW9XaDNVUWUwQVJuVW9Ua0gtNHNTZzlqanlPZkxYUkY5bUUwdw?oc=5",
          "breaking": false,
          "slug": "20260622-west-asia-crisis-drags-indian-startup-funding-down-43-year-on-year-sin",
          "image": "https://images.pexels.com/photos/15195538/pexels-photo-15195538.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Ashwani Babbar",
          "image_credit_url": "https://www.pexels.com/@ashwani"
        },
        {
          "hour": 21,
          "time": "21:24 IST",
          "headline": "AI Agents Are Quietly Replacing Human Workflows Across India's IT Services Industry",
          "what": "Artificial intelligence agents — software systems capable of autonomously completing multi-step tasks — are driving a silent but accelerating workforce shift across India's IT services sector, Business Standard reports. Major IT firms are deploying these agents to handle coding, testing, client communications and back-office processes that were previously managed by large human teams. The shift is raising urgent questions about the future shape of employment in an industry that directly employs over five million Indians and underpins the country's largest export sector.",
          "lens": "India's IT sector employs over five million people; AI agents automating core workflows could reshape hiring, salaries, and career paths for a generation of Indian tech workers.",
          "source": "Business Standard",
          "url": "https://news.google.com/rss/articles/CBMi-AFBVV95cUxPTnNqT21qUDJpdDgxUjJWTm1vZ0gyUk5qZ1FOaTZlUEs1c29abEJMNGNTV25FSnJMemxPcmNId21qNzl3X0F1dXQxNUFCSklGWWFLMFA1U2ZvZ2lDMmhwZEx6WmxWSHNlWmpMV0lkc3RIM0s5YUEwaWQ5WmNxUEFTTGFUS0o5dE8zMk5teGx5ZXJZOG9Hcml5alFGLXJncFlMOTgyWU42TloyUk9tNUNZV2tHLXBmYl9NN0NRWWNRVUYtS3BtNkhLdkdsV3NvdVdvUUVCQ0o0X3hIRFVOOE1LdGhGTkZ6QkhHRDdtbUFscG1vTjFQbEVTYtIB-AFBVV95cUxPTnNqT21qUDJpdDgxUjJWTm1vZ0gyUk5qZ1FOaTZlUEs1c29abEJMNGNTV25FSnJMemxPcmNId21qNzl3X0F1dXQxNUFCSklGWWFLMFA1U2ZvZ2lDMmhwZEx6WmxWSHNlWmpMV0lkc3RIM0s5YUEwaWQ5WmNxUEFTTGFUS0o5dE8zMk5teGx5ZXJZOG9Hcml5alFGLXJncFlMOTgyWU42TloyUk9tNUNZV2tHLXBmYl9NN0NRWWNRVUYtS3BtNkhLdkdsV3NvdVdvUUVCQ0o0X3hIRFVOOE1LdGhGTkZ6QkhHRDdtbUFscG1vTjFQbEVTYg?oc=5",
          "breaking": false,
          "slug": "20260622-ai-agents-are-quietly-replacing-human-workflows-across-india-s-it-serv",
          "image": "https://images.pexels.com/photos/7709182/pexels-photo-7709182.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "MART  PRODUCTION",
          "image_credit_url": "https://www.pexels.com/@mart-production"
        },
        {
          "hour": 9,
          "time": "09:48 IST",
          "headline": "Amazon defends India data centre water use, points to conservation measures",
          "what": "Amazon has responded to growing scrutiny over water consumption by its data centres in India, pointing to conservation steps it has taken in the country. The company's defence comes as hyperscale data centre expansion across India has raised concerns about pressure on local water resources. The disclosure puts a spotlight on the environmental footprint of cloud infrastructure at a time when India is rapidly scaling up its digital capacity.",
          "lens": "As Amazon and rivals race to build data centres across India, how much water these facilities consume — and whether conservation pledges hold up — directly affects communities sharing already-stressed local water supplies.",
          "source": "The Hindu",
          "url": "https://news.google.com/rss/articles/CBMi2AFBVV95cUxPYVBaYWV0N1ZkWUt2WldTYWNYNEZac0w3cnZCbG1ZNDBxbE1kZmJhWWVTcU5MRk1JWGFqQzdwU0c2NndUaFhScDMyRi03b3g3MFNfWEt6UkVWQW5hNjNZOUZqSnRZUWZZM1hldnVrckVXeEk3dUpSYUxZTG03el9lbDNDMkJrRVh1aDZ1SjlGWFRmSElpM0laYnpobmhoUGkyWU94d19wOFJ5Y3M4SHFBOExIQ1psMUJoNmV3SDY0bjhnRERrTjJrX1gtOFd5OFdqeEJ6UVJoSGHSAd8BQVVfeXFMTUZxZGEzdS1tTHlLSkhMNTR6MGdjNjc2TUNOSWZzcjI4NVdwSUYwZUc4RjhtZlQ0MVdtVV9WUEFLRFNLOE5GMC1OSFVtSjByTjR0cU9GeE8ta1ZSd3g4TVpQMi1zdkFUZjcwVFlsNnBsYkNlei1uSVFjdjdvVUN6NjJ5NG1nSk9tQkt1ZHRIMUlibm9aendWaEpQb3B5WWtpOXJ2Yi1VeF9GWENwelZGRzFmLS1wM29sT25Ed3pxVGZNZnBiRzNUUk8zRjdfSFVBSzVHbDJ3SWRIRmMyMUVrMA",
          "breaking": false,
          "slug": "20260622-amazon-defends-india-data-centre-water-use-points-to-conservation-meas",
          "image": "https://upload.wikimedia.org/wikipedia/commons/b/bc/Amazon_Tower_I_topped_out%2C_June_2015.jpg",
          "image_kind": "photo",
          "image_credit": "SounderBruce / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Amazon_(company)"
        },
        {
          "hour": 8,
          "time": "08:08 IST",
          "headline": "India needs a full Science & Technology Mission, not just an AI mission, Moneycontrol argues",
          "what": "A Moneycontrol commentary argues that India's current focus on building a standalone AI mission is too narrow, and that the country needs a broader, integrated Science and Technology Mission to remain competitive in the global technology race. The piece contends that AI cannot deliver its potential without foundational investments in basic science, research infrastructure, semiconductor capability and STEM talent — areas where India still has significant gaps. The argument arrives as the government finalises its AI policy framework.",
          "lens": "If India bets its entire tech future on AI alone without fixing the underlying science and research gaps, it risks building an impressive-looking edifice on weak foundations — a concern that affects India's long-term economic competitiveness.",
          "source": "Moneycontrol.com",
          "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxQY2lBRzBzak9xYmp1M1E0c1lmV2Z6VWc5Y1JRem91VnpPV0syNTh3MVVtSGRmVDhjNDRCS2tsR0RNTEZYeExjc2ZTWTBaX09tQ0swYW9CVmlZdDEzeWhoUEJfZ2V0QkVkT2hBRWlsUE1KUjN3Y2tJQzh1TUpvZDdabkJ4RUdoazFScHJDQkVmOW53YkswVWFBVXdFQzJTWFZsNklTYWJSdDVuQVlqR3dxeUNuZmhBUFBHNTUwT3BR0gHDAUFVX3lxTE51ZW4wYzRab2RPTlhzaUFTdU1BRURhR2xDYXpXdWlhMktlcHlOeVlMTDVGRDRrTmpXV2YyN3MwTFJUUDNBZ3o2U0RIcVAwdjhhM3ZCd1N3NmZnVzNMRjR3RWkzTlBEVXJJM2N3TzhpeHdJZnJWaG1HaEVzZllOMEU4X1dZUHg4NngxVkY3akpEcGxuU0pDcm1RNFlvcVNQcGM2cmc1b0Zic0ZCUDUwUkRVRHFxUWdnZ2tvNEVESXczdHkzcw",
          "breaking": false,
          "slug": "20260622-india-needs-a-full-science-technology-mission-not-just-an-ai-mission-m",
          "image": "https://pixabay.com/get/ge59c83e3cf09e1fb91898df8ddfa71888ee203ecdd41d8789a9d070af680dd5e66d67560179780779f64138a15e4d081f23d569760ed2c899a6af83d67034d81_1280.jpg",
          "image_kind": "photo",
          "image_credit": "tiburi",
          "image_credit_url": "https://pixabay.com/users/tiburi-2851152/"
        }
      ]
    },
    {
      "id": "national",
      "name": "National",
      "stories": [
        {
          "hour": 14,
          "time": "14:47 IST",
          "headline": "Congress Demands Fundamental Right to Vote, Citing Supreme Court's Footpath Ruling",
          "what": "The Congress party has urged the Supreme Court and the government to recognise voting as a fundamental right, drawing on the court's recent landmark ruling that affirmed citizens' right to walk on footpaths. The party argued that if the right to use public infrastructure can be elevated to a constitutional right, the right to vote — foundational to democracy — deserves explicit fundamental-right status. The move is seen as part of a broader Congress push on electoral and democratic rights ahead of upcoming political contests.",
          "lens": "By linking a pedestrian-rights verdict to voting rights, Congress is using a popular Supreme Court ruling as political leverage to push for stronger constitutional protection of the ballot — a debate that could reshape electoral law conversations.",
          "source": "India Today",
          "url": "https://news.google.com/rss/articles/CBMizAFBVV95cUxPV0l4cl9EQmppY3pXUWFXdXJMZnk5cXVvdVpENXVyQXFvYjJfUk81VXRfdnd3QUhuSDBrVWV3OFdodlg3bHg1VlJ3cUVkQ3ZVYzBIUUR0YUdKdno0X0hOQ245THYwb24zbGJQaDlnQm42dVVhQmd3aVBDU1kwcG9MdkNrVm1Ld205UEhUejVJTkR3UGtqbDA3a1JzYXFiUnRBdnBmZlRyUHJURnJzV3AzLU1fWTFkeV9ILXBpeDd6ZUt2YXBOUVpJd2NuVEbSAdIBQVVfeXFMT21ndUFyelhpenlWSUJuSFRoNlpxRTFEbUxXc0NnT0VEVHRhMmlIWW5OZHdXWThDN0dSQlZ4MFE5dzVlNGJ3QW5EREdNYmVHY3FfdFZ5TThpVG1sYzZRVjFYN3BMNmdKNTFFdmxpSDlMU3gwQ3RRNzRMTFdpOVVJTW1WSkpIMHdfcTZoQm9sWVVCTEVNamk4cmU5LURDVmt2VXViZGlJMGpaUWRlT09McmQ3T3JNd21UV0JVM0RNcnU4NURlYXlpZnJYSVp3V0dLR2FB?oc=5",
          "breaking": false,
          "slug": "20260622-congress-demands-fundamental-right-to-vote-citing-supreme-court-s-foot",
          "image": "https://pixabay.com/get/gdc9bec37b642462d882c1a4659cff1109c779ea29008706e3c852c7b43cb7dc58459c6b9d79b0608069e7533135fa533fbb8ca8b5afa90de3de4ee265c474bac_1280.jpg",
          "image_kind": "photo",
          "image_credit": "Leonhard_Niederwimmer",
          "image_credit_url": "https://pixabay.com/users/Leonhard_Niederwimmer-1131094/"
        },
        {
          "hour": 12,
          "time": "12:41 IST",
          "headline": "Supreme Court Orders Right to Walk on Footpaths as Pedestrian Deaths Surge Across India",
          "what": "The Supreme Court of India has issued an order affirming the right of citizens to walk on footpaths, a ruling prompted by a dramatic surge in pedestrian deaths across the country. The judgment puts the spotlight on encroached, broken, and non-existent footpaths in Indian cities that force millions of pedestrians onto roads daily. The ruling is expected to compel state governments and municipalities to take urgent corrective action on pavement infrastructure.",
          "lens": "With pedestrian deaths among the highest in the world, this ruling could finally force Indian cities to fix their footpaths — making walking safer for millions who have no other option.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMiswFBVV95cUxPSGN3QlZqVWN4VnNWZUQwUmRmOUNJeHZEWlFuckF4VU5oRUtGX21XRlBvNVYzM1BxS2VONnZmOTZEMGF1bWxrSjVyNktkMjNDQ29pakFXUjdCNEtXSXZ4MnZ0NjNLUUd4ZTM1amJjdmFlYTk2bU4tQnYtMzhkSU8zM0VVTlRjRko0dWQ4R1RTaFRKNFpGQ3h1S2RtTlA2QW9SS3BWRXVmYnljU3U1RzVhOGlaNNIBugFBVV95cUxOY09BVVJvSktoemRic2JBS1VOcWI5a2JqNFFhOWYzUG9SclRncWw2Y3ByX3Z0TnVUclFWRTZGeU4yZDdqekxrTHdILVAtZGlnSWd1cElISFQ0bDF3ZXhsMVhjS2s3eHcxZktyUGd5MVhzcU1FSEhGSWdPd2V6WXFydmJ2dXg0cHRtSUZUUUpZNWg2elVULTJoS0dDOTdsOFQtMDI4dmhabzJSTVpHZldiUTRPOXBsZDZMVVE?oc=5",
          "breaking": false,
          "slug": "20260622-supreme-court-orders-right-to-walk-on-footpaths-as-pedestrian-deaths-s",
          "image": "https://images.pexels.com/photos/365813/pexels-photo-365813.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Dom J",
          "image_credit_url": "https://www.pexels.com/@dom-j-7304"
        },
        {
          "hour": 11,
          "time": "11:36 IST",
          "headline": "Do Police Need Court Permission to Investigate Further After Filing Final Report? Supreme Court Explains",
          "what": "The Hindu has examined a significant legal question clarified by the Supreme Court of India: whether police require explicit court permission to conduct further investigation after a final report — known as a chargesheet — has already been filed in a case. The Court's ruling addresses a procedural grey area that has practical implications for how criminal investigations are conducted and how accused persons' rights are protected. The question is particularly relevant in high-profile cases where investigators seek to add new evidence or accused persons after initially closing the probe. The ruling brings clarity to the interplay between police powers and judicial oversight under the Code of Criminal Procedure.",
          "lens": "This ruling shapes how every criminal case in India can be reopened or extended by police — directly affecting the rights of the accused and the quality of justice delivered.",
          "source": "The Hindu",
          "url": "https://news.google.com/rss/articles/CBMi5AFBVV95cUxPQW9SYlRCc1V5ZXUtbE5Cd3BsT0FScmd4dGFBQ1doV3g3WnFSbm9zTEdpaDQtMDNnZnBUa1U4S05CUTA3SDZwWG9XQlRDeXdCbXNRNllIQUh3MXFFYkpNeE5ObmxCTzR4ZW1qZno2bXBVQ0p0OXlObHIydGx4YUpUdFAtc1hsak5jdHZUUVFIbWttaDZld0VrSzZXOGd6RktwcnJhRjNiMkp1U3k2SlF4ZEpLWEJBZUY3OG5tMFBSX09veTZKZEx2OXZxME5GYXJUSUNTQWJoMTR5OFYwUV9DQjNmembSAesBQVVfeXFMTnp3T2dCSGpGT0hhV0Y5VTBHckNNVzhKMXBJaHNaLVFPbUVZemZnNkpqTDllSnBmZllYTlE4cXdieWNiTWgzZGNHNE43Uk1mMjNkOG9STnhuQkRhVlc5WVZ5d3JfM1BueHVlWWVhRFBUMDd6eEdJWUh3T2w1bUVRU19pRkpBZ055eGxNeThkUHpXQ0ZzQ3FWQnZNcDc3M3ZVMmFkQUJZbG5pTDlSOUw2OFM0akZjLTFldk1sZVpsd1VaUXdHRE1EVW9ielFIcUdsbXJNcXVtanp3UEp4aGdvT294bWk3SGk1X3dodw?oc=5",
          "breaking": false,
          "slug": "20260622-do-police-need-court-permission-to-investigate-further-after-filing-fi",
          "image": "https://images.pexels.com/photos/10464437/pexels-photo-10464437.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "cottonbro studio",
          "image_credit_url": "https://www.pexels.com/@cottonbro"
        },
        {
          "hour": 20,
          "time": "20:36 IST",
          "headline": "Supreme Court refuses urgent hearing on plea to defer June 21 NEET-UG retest",
          "what": "The Supreme Court of India declined to grant an urgent hearing on a petition seeking to defer the NEET-UG retest scheduled for June 21. The court's refusal means the retest is set to proceed as planned, maintaining pressure on the National Testing Agency and the government to conduct a fair and secure examination. The development comes amid ongoing controversy over the NEET-UG paper leak and irregularities that have roiled India's medical admissions process for weeks.",
          "lens": "For the hundreds of thousands of medical aspirants who appeared in the compromised NEET-UG exam, the Supreme Court's refusal to defer the retest means June 21 remains the date they must prepare for — and the path to clearing admissions uncertainty stays on its current timeline.",
          "source": "The Hindu",
          "url": "https://news.google.com/rss/articles/CBMiwgFBVV95cUxOc0xsOTd6dHJ1MGhkbWlLNUxyN1FEcFpURmh3N01pX2lfVzg3LXllMHduUVFBdFdqcldGZWFVQUVROVlJTHY0RlVZTDlGUW1COGV3YW9jbUN3WkQzU05qeFJDUmRVaHhEaGxja3VIcnVFQ2xHR3dLb1VuZlFDYWRKTHNmSTh6THI0VlQxZG9VSzlkcDZRQzZTeUt2VVhpdllScVdPb25WNjF6UkdSTzBLWFlSNGstUHdWTTdSbTBmNjBqd9IByAFBVV95cUxNRFlLcEN2OGticW1sV09LMEVhMjFzR2VoRzJYRGR5UlQzdGJxRmJGQmZYSEdjdHo3dFMxdzZUOEpGUGlJa2lsOWxOcjV2Ty04TVpJWUxMcGJOSDJGTnlkcS1wVGlxajMtcDMwbE5QeDdSN3ZOSG9xbkltLXFJSEtiSWdpZjgzV3JWeUt6aWc0aHIxaGlGREQzWFNkSHBHVHJEelRSRlJubndDMi01Sk9CN0ptcjcyQ1VOZGVLRHFiLTdjQjJDS19fOA",
          "breaking": false,
          "slug": "20260622-supreme-court-refuses-urgent-hearing-on-plea-to-defer-june-21-neet-ug",
          "image": "https://images.pexels.com/photos/36984943/pexels-photo-36984943.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Mark Stebnicki",
          "image_credit_url": "https://www.pexels.com/@nc-farm-bureau-mark"
        },
        {
          "hour": 15,
          "time": "15:37 IST",
          "headline": "Supreme Court dismisses businessman's plea against ED searches in TASMAC liquor case",
          "what": "The Supreme Court has rejected a petition filed by a businessman challenging the legality of searches conducted by the Enforcement Directorate in connection with the TASMAC case — a high-profile money-laundering investigation linked to Tamil Nadu's state-run liquor corporation. The dismissal clears the ED to continue its probe, dealing a setback to those seeking judicial relief against the agency's search operations. The TASMAC case has significant political dimensions, with allegations of large-scale financial irregularities in the liquor supply chain.",
          "lens": "The Supreme Court backing the ED's search powers in the TASMAC case means the money-laundering probe into Tamil Nadu's state liquor corporation can press ahead without legal roadblocks.",
          "source": "The New Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxQVzB1VnF5YS15SlJJS2xKUWFVU3pSb3BGUVBWYWpyS2Zlc3NfSm9iemNBNzFQaGJDeDlGQTVBVjEwSXgzQVBvS3BFN2xuODJ3MVpqRUlFaVI0WDRIdnVRVk5tOFVRdV9DT2h6QUIzWTA0eDZxckVndU9fNmJGQmdOSzlRVVBaZ1FyOUJ6ajctQXR6dmc0SHBzYW80UW5mUjJCYkY0ZjJPS3ZrQkNySW42T2pyb2RXX2U1STFRSklRek43UTNVT3hmUXFXTE42Yjlx0gHeAUFVX3lxTE5rMDBrNmh3cHhIYXQ4VXRQVlotSHc0UUlxUTNtczVuRm5SUmllQ1pOYkZEdkFDdjN0dkZEZ2pFUHlBdEMyelJ3Mm4xVWk3RzdremtZOVRUeWtjNnlWRU43VThkQTJCYlE2RVNjeTVDTXZ6enNFckxOWXVnUFZDN3FDb1J1NVNHdVVpaDV0UmlpblVMcHdINEw4Z0N5V1RWTkNVU3Z1NndnRmItUm82Q2dHLXBLb0h2S2pTSkFlT3NlZlprV1dfNlI1YV9tTEg0cHBhT2ZxeEtNN2NOTGhLUQ",
          "breaking": false,
          "slug": "20260622-supreme-court-dismisses-businessman-s-plea-against-ed-searches-in-tasm",
          "image": "https://pixabay.com/get/g89f9d1a41beeeedaf347776bc3bed77ea0b53a6862bd2643571fafa7b0acdeefb69992e2a18f27759379203cfa47743d328aa57152b3c76136691e0cc812b6aa_1280.jpg",
          "image_kind": "photo",
          "image_credit": "BunteAufnahmen",
          "image_credit_url": "https://pixabay.com/users/BunteAufnahmen-6345617/"
        }
      ]
    },
    {
      "id": "ai",
      "name": "Artificial Intelligence",
      "stories": [
        {
          "hour": 22,
          "time": "22:01 IST",
          "headline": "India's AI strategy problem: Why building sovereign models may not be the answer",
          "what": "A Business Standard analysis argues that India's push to develop sovereign large language models — AI systems built and owned by the Indian state — may be misguided, contending that the costs are prohibitive, the timelines are long, and the strategic benefits are overstated. The piece suggests India would be better served by focusing on AI applications, local data infrastructure, and regulatory frameworks rather than competing head-to-head with US and Chinese foundation model labs. The debate comes as the government's IndiaAI Mission rolls out funding and compute infrastructure.",
          "lens": "Whether India builds its own AI models or rides foreign ones will determine everything from data sovereignty to which language and cultural contexts Indian AI systems actually understand — a policy choice that affects every Indian who will eventually use an AI-powered government service or app.",
          "source": "Business Standard",
          "url": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxQR3J3OWtsbnVmU09RM0tqZ21BTmI1Z3AyNGhldndEU1JYZDhrRjdnRkJ6QUtVeWpNTDhuQkhXazZTX2UwVmR3a0VOby15MWJYdWt4eHh5cnp2V2FYMHRUZ0RfMUxXZzZjRWVPN0dkemxIWVJ5eWpMSmQzR0YxaDZ1NGl6TkVsN2RidXh4OEFBUkQ4S1V1TC1UN0FpdFprb3FVQlpyWEYyZFFpeS1uRGNFMFVwLTV2eTlhLWNCSjJVaDdPWE1xRlBjenplNHN5eDMtQkh3Y1R30gHbAUFVX3lxTE5vVy1jOWRlQ2NTZWJzWDhDcU81bWxuWkZOUTBSVDRobjZOUW1maGJ4WkpmaDFxdTFWRjBCSmdJUVlXWnE0WkdzZkt6a3ozRDN5LXc0YkZmdGhNWWJ0T1Y2cXJPUzhFaUJRWGdEbUhzMlExM1hyWTJXY3dzTVVtbEYwLWhJVm12TGlhbzRacXVYcGpxeE03YW1CaVBjdXoyRHdPMjFvYUk3bWduSDR5bFpzOS0zTlZKVVF5YkluTG1tQTNhMUI0N1gwYjJoa2pIMzRaZTB2RV9YZlZZQQ?oc=5",
          "breaking": false,
          "slug": "20260622-india-s-ai-strategy-problem-why-building-sovereign-models-may-not-be-t",
          "image": "https://images.pexels.com/photos/10822937/pexels-photo-10822937.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Prasanjeet Shyam",
          "image_credit_url": "https://www.pexels.com/@prasanjeet-shyam-279139"
        },
        {
          "hour": 22,
          "time": "22:01 IST",
          "headline": "India's Sovereign AI Model Push May Be the Wrong Answer, Analysts Warn",
          "what": "A Business Standard analysis argues that India's government strategy of building sovereign AI models — state-backed large language models developed domestically — may be misaligned with where AI value is actually created. The piece contends that pouring public resources into foundation model development puts India in direct competition with vastly better-resourced US and Chinese labs, rather than focusing on the application and deployment layer where Indian strengths in software services could yield greater returns. The debate touches the core of how India should spend its AI Mission budget.",
          "lens": "With India's Rs 10,372-crore AI Mission already under way, the question of whether public money should fund base models or application-layer innovation will directly shape thousands of AI jobs and the country's competitive position in global tech.",
          "source": "Business Standard",
          "url": "https://news.google.com/rss/articles/CBMi2wFBVV95cUxOb1ctYzlkZUNjU2Vic1g4Q3FPNW1sblpGTlEwUlQ0aG42TlFtZmhieFpKZmgxcXUxVkYwQkpnSVFZV1pxNFpHc2ZLemt6M0QzeS13NGJGZnRoTVlidE9WNnFyT1M4RWlCUVhnRG1IczJRMTNYclkyV2N3c01VbWxGMC1oSVZtdkxpYW80WnF1WHBqcXhNN2FtQmlQY3V6MkR3TzIxb2FJN21nbkg0eWxaczktM05WSlVReWJJbkxtbUEzYTFCNDdYMGIyaGtqSDM0WmUwdkVfWGZWWUHSAdsBQVVfeXFMTm9XLWM5ZGVDY1NlYnNYOENxTzVtbG5aRk5RMFJUNGhuNk5RbWZoYnhaSmZoMXF1MVZGMEJKZ0lRWVdacTRaR3NmS3prejNEM3ktdzRiRmZ0aE1ZYnRPVjZxck9TOEVpQlFYZ0RtSHMyUTEzWHJZMldjd3NNVW1sRjAtaElWbXZMaWFvNFpxdVhwanF4TTdhbUJpUGN1ejJEd08yMW9hSTdtZ25INHlsWnM5LTNOVkpVUXliSW5MbW1BM2ExQjQ3WDBiMmhrakgzNFplMHZFX1hmVllB?oc=5",
          "breaking": false,
          "slug": "20260622-india-s-sovereign-ai-model-push-may-be-the-wrong-answer-analysts-warn",
          "image": "https://pixabay.com/get/g27ed5460936c1809717cfb78e499c70763a48479b39b303dea98678789d398fa07de4969406572e27f73e687e922a1e9316645b5ddc235a8de2e78f76929e825_1280.jpg",
          "image_kind": "photo",
          "image_credit": "mickey970",
          "image_credit_url": "https://pixabay.com/users/mickey970-1278620/"
        },
        {
          "hour": 15,
          "time": "15:34 IST",
          "headline": "Google DeepMind loses Nobel laureate John Jumper to Anthropic",
          "what": "John Jumper, the scientist who won the 2024 Nobel Prize in Chemistry for his work on AlphaFold — the AI system that predicted the 3D structure of nearly every known protein — has left Google DeepMind to join Anthropic. The move is a significant talent win for Anthropic and a notable loss for DeepMind, where Jumper led one of the most celebrated breakthroughs in modern science. His hire signals Anthropic's ambition to deepen its fundamental AI research bench.",
          "lens": "Jumper's move from DeepMind to Anthropic underscores how fiercely Big Tech and AI labs are competing for world-class scientific talent — a race that directly shapes which platforms power drug discovery, biotech, and research tools Indian institutions may soon rely on.",
          "source": "outlookbusiness.com",
          "url": "https://news.google.com/rss/articles/CBMisAFBVV95cUxORnFkRlJIN2otYnFyb0IzbFpRU3NKRTdMZHhiSEtGYnlaOWpVdEJSdFViZjZVR2VfM2NhR055UEEzZmpSUHQwVC16SEhienRxdkVaZThpZGR6UEJWRmwtT3ZEcXZvb1BERzJoZGVmTTZuTmhmcDBoZG9yQW9GMjlGemZoTkdSQXZCSFFZcjZsdDkxLTdmaENNYUhQTDRfTUxUY2tNYXpUbTVLakFKMkc1Zw?oc=5",
          "breaking": false,
          "slug": "20260622-google-deepmind-loses-nobel-laureate-john-jumper-to-anthropic",
          "image": "https://upload.wikimedia.org/wikipedia/commons/b/b0/John_Jumper%2C_2024_Nobel_Prize_Laureate_in_Chemistry.jpg",
          "image_kind": "photo",
          "image_credit": "Arthur Petron / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/John_M._Jumper"
        },
        {
          "hour": 10,
          "time": "10:41 IST",
          "headline": "Tech Workers Who Maxed Out on AI Are Now Pulling Back",
          "what": "A new report in The Indian Express explores a growing backlash among tech workers who aggressively adopted AI tools — and are now deliberately scaling back their use. The pattern, emerging among software developers, writers, and knowledge workers, reflects concerns about cognitive dependency, skill erosion, and the diminishing quality of AI-assisted work. Rather than a wholesale rejection of AI, the retreat represents workers recalibrating how much they rely on tools like ChatGPT and GitHub Copilot in their daily workflows.",
          "lens": "For India's massive IT workforce — the world's largest pool of software professionals — the question of how much to lean on AI tools has direct implications for skills development, employability, and who gets left behind as the industry transforms.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi5wFBVV95cUxOblNpeklYakhZU0xOV1Rzc2RtTGRDbVlGams0RVJEN2MteGVWMkhHa0MtYVdFSklaQ1p4ekQ0LVk5QzNsWGZwbkgwemxIdlppd1EyM2tqTVVWc3h6V3d1OHJxYkJvcTZHRlhxWmxTS3VTLTYtMHpWc3pVczZva1gwenV5dkNORzlPSWIwRTFPZ1dtNl9nQjA4N0dWSW5NSjBheTdoVXFfQVFFclhnVzBaTENuem9YSE1LaDVYMHBHNGd2alV2TFBDLTlTRnBGcEZRN0hIUTVqWU9zUVVJV05GOXJVTHp0Y0k?oc=5",
          "breaking": false,
          "slug": "20260622-tech-workers-who-maxed-out-on-ai-are-now-pulling-back",
          "image": "https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Tara Winstead",
          "image_credit_url": "https://www.pexels.com/@tara-winstead"
        },
        {
          "hour": 9,
          "time": "09:32 IST",
          "headline": "Trump no longer views Anthropic as a national security threat",
          "what": "US President Donald Trump told Axios he no longer considers Anthropic, the AI safety company behind Claude, a national security threat — a significant reversal from earlier concerns about the firm's ties to foreign investment. The shift could ease regulatory pressure on Anthropic and smooth its path for US government contracts. It comes as Washington recalibrates its approach to domestic AI companies amid intense competition with China.",
          "lens": "For Indian AI researchers and firms watching US policy closely, a softer American stance on Anthropic could accelerate global enterprise adoption of Claude-based tools and reshape which AI platforms Indian businesses partner with.",
          "source": "The Hindu",
          "url": "https://news.google.com/rss/articles/CBMi3AFBVV95cUxNcWJMTm5fMVhMOTk0NmdHcjRlV1lCVWZYMkMzaWJRN2VlNWNwYU5vQlZUZ3daVkxFYTdCQVBWSm1RcnNKSDNjUzUwbWFYVHpjbUVWMWlwNkFLckl5U3NCdUVDeXdoVzVXc3BmdlJiQWZCX2RKWVlnSW9wcDhLQlZRbWVVTF9nWXFOcGtzVlBSM1Z5eEdhNDFLSFZLT2dNYW1hMzBlTHQ0QmtyVEZZYnBMeFZma3NrcmJNVkg5X3UyaTczU3Zzb3ladmxCandkUUFVSl9sVWRWaUFhUzF30gHcAUFVX3lxTE1xYkxObl8xWEw5OTQ2Z0dyNGVXWUJVZlgyQzNpYlE3ZWU1Y3BhTm9CVlRnd1pWTEVhN0JBUFZKbVFyc0pIM2NTNTBtYVhUemNtRVYxaXA2QUtySXlTc0J1RUN5d2hXNVdzcGZ2UmJBZkJfZEpZWWdJb3BwOEtCVlFtZVVMX2dZcU5wa3NWUFIzVnl4R2E0MUtIVktPZ01hbWEzMGVMdDRCa3JURllicEx4VmZrc2tyYk1WSDlfdTJpNzNTdnNveVp2bEJqd2RRQVVKX2xVZFZpQWFTMXc?oc=5",
          "breaking": false,
          "slug": "20260622-trump-no-longer-views-anthropic-as-a-national-security-threat",
          "image": "https://pixabay.com/get/geba30e8a928e546701dd83e9c21727096810f4dc859d8aef81dc1675e2ea1f9578263bd0d7ca8486369fb5918637f245244dfc83f1423e3abaa0ed371552725c_1280.jpg",
          "image_kind": "photo",
          "image_credit": "Alexandra_Koch",
          "image_credit_url": "https://pixabay.com/users/Alexandra_Koch-621802/"
        }
      ]
    },
    {
      "id": "sports",
      "name": "Sports",
      "stories": [
        {
          "headline": "FIFA World Cup 2026: latest scores and full results",
          "time": "10:51 IST",
          "hour": 10,
          "what": "The latest FIFA World Cup 2026 results in full — scorelines, goalscorers and what's coming up next, all in IST.",
          "lens": "Every matchday, tracked in your time zone.",
          "source": "openfootball",
          "url": "https://thelast24.in/worldcup.html",
          "breaking": false,
          "worldcup": true,
          "slug": "20260622-fifa-world-cup-2026-latest-scores-and-full-results",
          "image": "https://pixabay.com/get/gbf1c8db89bf0c632342e8a0287fa9679a791d202e5e46b98bb0453d5e96a23035c4b2915981d9fdd324f7ad8dc112b16fae3a4f4bfad9c8f3d6412a4f129905c_1280.jpg",
          "image_kind": "photo",
          "image_credit": "jorono",
          "image_credit_url": "https://pixabay.com/users/jorono-1966666/"
        },
        {
          "hour": 22,
          "time": "22:40 IST",
          "headline": "Marizanne Kapp Stars as South Africa Beat India to Keep Women's T20 World Cup Hopes Alive",
          "what": "India suffered their first defeat of the Women's T20 World Cup 2026 as South Africa beat them in a crucial group-stage contest, with Marizanne Kapp delivering a match-winning all-round performance. The loss ends India's unbeaten run in the tournament and injects fresh uncertainty into the standings. South Africa, who needed the win to stay alive in the competition, kept their qualification hopes firmly on track. India's middle order once again came under scrutiny as the side failed to build on their start.",
          "lens": "India's first loss puts their direct path to the knockout stage under pressure — the result could determine whether they finish top of their group or face a tougher route in the knockouts.",
          "source": "BBC",
          "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE1DRkRJTU5uUmEwNkZYZXd2ZWY1MTdEazhBcDd6enVFdFdVY19BSXZxdDZwcTRfTTlWSEhPMEhzWEM0U01SZEtWMGRCeGxsOHlaM0Vwc3lqSU5OODZ1Z3FDQVVHRXpIdw",
          "breaking": false,
          "slug": "20260622-marizanne-kapp-stars-as-south-africa-beat-india-to-keep-women-s-t20-wo",
          "image": "https://images.pexels.com/photos/36230651/pexels-photo-36230651.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Shlok",
          "image_credit_url": "https://www.pexels.com/@shlok-230964119"
        },
        {
          "hour": 22,
          "time": "22:58 IST",
          "headline": "Sloppy India lose Manchester thriller to South Africa, now in danger of early Women's T20 World Cup exit",
          "what": "India Women suffered their first defeat of the Women's T20 World Cup 2026, going down to South Africa in a thrilling match in Manchester. Marizanne Kapp was the standout performer for South Africa, whose victory keeps their own tournament hopes alive. The loss puts India in danger of an early exit from the competition, a major setback for a side that had started the tournament in promising form.",
          "lens": "India's Women's T20 World Cup campaign, which had looked steady, is now suddenly precarious — a further slip could mean an early exit from a marquee global tournament on foreign soil.",
          "source": "India Today",
          "url": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxNQ1RTMElkcW9OdVRZQ083bUtjamZJenVQMnhsV3k0LWdPS21rME1EaGFCSXFrU1FndEFLUEx6M0JCYllyeEhuVzJ5d25IYnEzSzk4NGNkM2RkcXdqbml5NTFuRVF1SXRRRWJPaDdCVTkybUR0bFlqUGtkcFRqU3BjZnZNaExmbE90blNoV2NHS2h2OVR5a2VxMnNrUGZiX1JDQzFpSzFmZzhjM0UtbEl5ODRSeF92M3ZLSk1CUlpfNjNic19XSzhpatIByAFBVV95cUxNQ1RTMElkcW9OdVRZQ083bUtjamZJenVQMnhsV3k0LWdPS21rME1EaGFCSXFrU1FndEFLUEx6M0JCYllyeEhuVzJ5d25IYnEzSzk4NGNkM2RkcXdqbml5NTFuRVF1SXRRRWJPaDdCVTkybUR0bFlqUGtkcFRqU3BjZnZNaExmbE90blNoV2NHS2h2OVR5a2VxMnNrUGZiX1JDQzFpSzFmZzhjM0UtbEl5ODRSeF92M3ZLSk1CUlpfNjNic19XSzhpag",
          "breaking": true,
          "slug": "20260622-sloppy-india-lose-manchester-thriller-to-south-africa-now-in-danger-of",
          "image": "https://images.pexels.com/photos/20987995/pexels-photo-20987995.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Leon Aschemann",
          "image_credit_url": "https://www.pexels.com/@leon-aschemann-734730704"
        },
        {
          "hour": 16,
          "time": "16:40 IST",
          "headline": "Vaibhav Sooryavanshi smashes record-breaking 11-ball fifty for India A against Sri Lanka A",
          "what": "Teenage sensation Vaibhav Sooryavanshi blazed to a half-century off just 11 balls for India A against Sri Lanka A, setting a new record for the fastest fifty in this format of the game. The innings underscored the explosive batting talent the 14-year-old has already displayed at the international level, and will delight selectors and fans who have been closely tracking his meteoric rise. The performance adds another stunning chapter to one of Indian cricket's most watched young careers.",
          "lens": "Sooryavanshi's 11-ball fifty is a reminder that Indian cricket has a genuinely generational talent on its hands — a teenager rewriting record books at every level he plays.",
          "source": "BBC",
          "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE5uUF95MnNjM0dFZUdzLURxYkpFWGVzeG12M29tSGhVM0QweHF1MUVrV2U5LTg0bFd2NC05eVgwYUdkWGtlNUllT2VLdzY4c05vOHBWMVRPaWhxQ2FXSTk3UThyLWIwZw",
          "breaking": false,
          "slug": "20260622-vaibhav-sooryavanshi-smashes-record-breaking-11-ball-fifty-for-india-a",
          "image": "https://images.pexels.com/photos/15132924/pexels-photo-15132924.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Nevin Verochan",
          "image_credit_url": "https://www.pexels.com/@nevin-verochan-27256961"
        },
        {
          "hour": 6,
          "time": "06:56 IST",
          "headline": "Jaiswal Axed from England ODI Squad Despite Century; Virat Kohli Returns to India Setup",
          "what": "Yashasvi Jaiswal has been dropped from India's ODI squad for the England series despite scoring a century, in a major selection surprise that has set off debate about the selectors' priorities and team balance. Virat Kohli, meanwhile, has been named in the squad, marking his return to the Indian setup after a period away. The contrasting fortunes of the two batters — one in red-hot form yet left out, the other returning on reputation and past record — has made this one of the most talked-about selection calls in recent memory.",
          "lens": "When a centurion gets dropped while a rested superstar walks back in, it tells everyday fans exactly how the selectors weigh current form against established stature — a debate that cuts to the heart of Indian cricket's selection culture.",
          "source": "Telegraph India",
          "url": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxQUmxrejVzSTlmRXp0NnVOM1RxSldid05qOWxrQVlhcjJkZkdldkFEVDRrSVdESDl6VFpDSEZhMkpldTM1NTBhYVo1QU1zS1QtOXl1U19xS3pCdVpEaVB4bndYcTQ3R1BXOEstSkx1Nm8xVTVHQXVlV04tcExsbzNnZEhMYmd0cFI4Z1JOSTlqWi1pQzFpbUpTVml3SEMyTXU1bXlpS0padmxBcnNkRUdKcDE0U2dyX1h4UWpUTFY0eU5SYzA3MXp1aGJPZS1qcHBXR1pacNIB2gFBVV95cUxNNzBJLTZjMUhOcXdKTnBkR2JLdnl1WGNKbWVYTWt5NmI0VDg2c2xCRTVHZGhmTkFLeW5hTGhlOXlkZHotMUsyWWZjMy12R0hfTEdOREZaZGpSdVpGOTBuRHEtZ1VsSlJxLURFM2JKRURDT2ctcGxkcUNFQlVZMUk2ZzRuNHFiR0FqeUJXN29XZkVNaFRYNURVckZ6VGdQeWw4X2hyWkFsdXYxWFEtLUxGUXRwWjZRUWtzaThoZWgxTUNJR0ZKZGh5S25PclZpamJia0pXUjRJeWxaUQ",
          "breaking": false,
          "slug": "20260622-jaiswal-axed-from-england-odi-squad-despite-century-virat-kohli-return",
          "image": "https://upload.wikimedia.org/wikipedia/commons/9/9b/Virat_Kohli_in_PMO_New_Delhi.jpg",
          "image_kind": "photo",
          "image_credit": "Prime Minister's Office / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Virat_Kohli"
        }
      ]
    },
    {
      "id": "entertainment",
      "name": "Entertainment",
      "stories": [
        {
          "hour": 18,
          "time": "18:00 IST",
          "headline": "Did Amitabh Bachchan shelve Khabardar to avoid being overshadowed by Kamal Haasan?",
          "what": "A long-circulating piece of Bollywood lore has resurfaced: that Amitabh Bachchan pulled out of — or effectively shelved — the film Khabardar because he feared being outshone by co-star Kamal Haasan. The Indian Express revisits the story behind the ill-fated collaboration between two of Hindi cinema's biggest names, a project that was never completed. The episode, if true, would represent a rare instance of Bollywood's biggest superstar stepping back from a project for fear of artistic competition.",
          "lens": "The Bachchan-Haasan rivalry anecdote is a window into the ego politics and star-power calculations that have always shaped — and sometimes killed — ambitious Bollywood projects.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi4wFBVV95cUxPX3B3T085UXVoTTBOQl8wMS03QUdKZDJYeDZKTWRQV0V0WkZoNkQtVk1FaGJGTExpbXh4Y1RqSjlpZV91WGJpQ0VIUnRSSWRFVFh4NWhwX2pCN2lBaVVQc1NsQ0tJSGNZOEVBNy14T2ZfYmZxNDE5MS1qTDE4Q3RMbFlnbnV5WUh0MG55UnJMZ3MzVUc2Y1dDMUtjdUVCV0NiV0NyZE5Cc0E0ZzduME1MM3ZzU0JYUjEtYnZIQVdBOXBlVS0ycEdNM3dSU2k0WW1Gb09scEVlLWZRX3M5UlZTV2wyVdIB4wFBVV95cUxPX3B3T085UXVoTTBOQl8wMS03QUdKZDJYeDZKTWRQV0V0WkZoNkQtVk1FaGJGTExpbXh4Y1RqSjlpZV91WGJpQ0VIUnRSSWRFVFh4NWhwX2pCN2lBaVVQc1NsQ0tJSGNZOEVBNy14T2ZfYmZxNDE5MS1qTDE4Q3RMbFlnbnV5WUh0MG55UnJMZ3MzVUc2Y1dDMUtjdUVCV0NiV0NyZE5Cc0E0ZzduME1MM3ZzU0JYUjEtYnZIQVdBOXBlVS0ycEdNM3dSU2k0WW1Gb09scEVlLWZRX3M5UlZTV2wyVQ?oc=5",
          "breaking": false,
          "slug": "20260622-did-amitabh-bachchan-shelve-khabardar-to-avoid-being-overshadowed-by-k",
          "image": "https://images.pexels.com/photos/7723755/pexels-photo-7723755.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Tara Winstead",
          "image_credit_url": "https://www.pexels.com/@tara-winstead"
        },
        {
          "hour": 15,
          "time": "15:55 IST",
          "headline": "How Om Puri's craft silenced Raaj Kumar's on-set insults",
          "what": "A behind-the-scenes anecdote about the late actors Om Puri and Raaj Kumar has resurfaced, describing how Puri's raw acting ability effectively stopped Raaj Kumar — notoriously imperious on film sets — from directing his trademark contempt at him. The story, revisited by The Indian Express, illustrates the complex hierarchies and personality clashes that defined Hindi cinema's golden era. It also serves as a tribute to Om Puri's formidable reputation as one of the most technically accomplished actors of his generation.",
          "lens": "For fans of classic Hindi cinema, this anecdote captures something real about how genuine craft — not stardom — was the ultimate currency even in an industry driven by ego and hierarchy.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi2gFBVV95cUxQWU43eEsycng1N3Z3Q2NEY25tRXNVSGtNaFNDSUE2dnBoQWs2ajFFcFV2bFN5Z1Ewc0pva2VMZ0hUWTQ0SEliMUNCSTFsWG9qNklYYXBuSVJsNF8waFIxaVljZkF2TGRlVjc5NEJ1bDNteEhydnh6cHJBVmRoM0FoZEx5andQU3gwelNsT19EOXBDWmtRVHU4Wm84NW5jdTVmLU5xQVk4dUZLZ2Y5S0J0U0VFZGl3SGc4N3dUNnNMTWNBa0tfQWJYM1gwRGhwVE5wbUlSaVlBSjNCd9IB2gFBVV95cUxQWU43eEsycng1N3Z3Q2NEY25tRXNVSGtNaFNDSUE2dnBoQWs2ajFFcFV2bFN5Z1Ewc0pva2VMZ0hUWTQ0SEliMUNCSTFsWG9qNklYYXBuSVJsNF8waFIxaVljZkF2TGRlVjc5NEJ1bDNteEhydnh6cHJBVmRoM0FoZEx5andQU3gwelNsT19EOXBDWmtRVHU4Wm84NW5jdTVmLU5xQVk4dUZLZ2Y5S0J0U0VFZGl3SGc4N3dUNnNMTWNBa0tfQWJYM1gwRGhwVE5wbUlSaVlBSjNCdw?oc=5",
          "breaking": false,
          "slug": "20260622-how-om-puri-s-craft-silenced-raaj-kumar-s-on-set-insults",
          "image": "https://pixabay.com/get/g51680a3f9616480c79a22a280200c7d0f0d7e03ca57d7457da276f9c33edee0127c38e7a44ff77d1ee36292c8ba6a61f1024cf8e325f7a3706728f2cf0b723a7_1280.jpg",
          "image_kind": "photo",
          "image_credit": "pprasantasahooo",
          "image_credit_url": "https://pixabay.com/users/pprasantasahooo-5744012/"
        },
        {
          "hour": 9,
          "time": "09:45 IST",
          "headline": "After publicly demanding Samay Raina be 'paraded on a donkey', Shaktimaan actor Mukesh Khanna ends up collaborating with him",
          "what": "Mukesh Khanna, the actor famed for playing Shaktimaan, had previously made headlines by saying stand-up comedian and roast-king Samay Raina 'should be paraded on a donkey' — a sharp public rebuke. Now, in a striking reversal, Khanna has gone ahead and worked with Raina on a project. The about-turn has drawn wide attention online, given how emphatic Khanna's original criticism was. It underscores the peculiar pull of Raina's growing cultural platform.",
          "lens": "When one of Bollywood's most vocal moral guardians ends up on the same set as the man he publicly shamed, it says something sharp about how creator-economy clout now reshapes old-guard celebrity calculations.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi9AFBVV95cUxPZnlBQjdlX0poVFprUEVWZlhzc2VkZjR0ZUlFbmxiSVpfVFpObFZJYnV1dWtDeTByaW1CMlkwRjRfVzUyVHpibEQ4STdPUVFGUWdWYUl0RjNET193NWlfNkJWNXp2RHlDTTZtY2FET3pNUVpkei1vV3ZuX0tFR2ozZjJoRy15eE8zUWJVTXQyeWRRVFZ6ZWlQc0VZeTZPNGdvQ3Nsb2U0SXhCa0dnODhfSkR6NUFHOUpBaXRTRU9sSi0xbUtISWpIS3JwUDNMQVZDNVQ4dF9KMmdpZ3hCX1R2bGxHR2FDeTFRWFM5MnYtd1d0d0530gH7AUFVX3lxTE1uNXJWYXMwV1FOWGtiLVZtdnltTF9nUElxTW13d0hoUTJBRC1vcGFVUlViTlRLOW1sXzBOejFpMGJIdDBPUXZyVVJtUDZmNG1QNG1yUWhMblhFa3BwdE9GQktVcURJTFczR2Q3ZUY5cGNTS0o5MlBwdFN0TVh4NTRNV2NHRTVtMHBQQ2dwZElTRG5rX1A0S2VvZmhmbDlkc3pLbEUwOFpvbEJsdS1VbnZDVnY2aXVFZWZTNEJ6d0NDbFd2MEkxQ3htUFA0aXpzRHdwNWJqYWd2U0VtczhweVZlYVd3QWFjZ2VOWFR5U2UzRDB2cW1oLTVWX2VB",
          "breaking": false,
          "slug": "20260622-after-publicly-demanding-samay-raina-be-paraded-on-a-donkey-shaktimaan",
          "image": "https://upload.wikimedia.org/wikipedia/commons/d/de/MukeshKhanna.jpg",
          "image_kind": "photo",
          "image_credit": "Bollywood Hungama / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Mukesh_Khanna"
        },
        {
          "hour": 9,
          "time": "09:16 IST",
          "headline": "Sona Mohapatra says Bollywood heartbreak songs are 'reserved for men', questions why women's pain goes unsung",
          "what": "Singer Sona Mohapatra has called out a longstanding gender imbalance in Bollywood music, arguing that heartbreak songs are overwhelmingly written for and performed by men, leaving women's emotional experiences largely invisible in mainstream Hindi film music. She pointedly asked 'is man making love to himself?' — highlighting the absurdity of a musical landscape where male longing is central but a female counterpart is absent. The comment has reignited debate about representation in the Hindi film music industry.",
          "lens": "Bollywood produces hundreds of songs a year that shape how millions of Indians process love and loss — if women's heartbreak is systematically absent from that canon, it reflects and reinforces a real cultural blind spot.",
          "source": "The Times of India",
          "url": "https://news.google.com/rss/articles/CBMitwJBVV95cUxQd3E5dlhKQlJzc2Jia08yVWJWNDNkN0QwdWFVeFhjMmFybUhyeE56MFdNcHBOVlhFdjREeTdoQk1mRElCUDMtbE42Y1FfRTdBd3pLdUxEUWhETmlwWVlRQVJJWWhZVlJ6WjJ1b043S1g0QWNCeU9MS1QtbTJSU2dfWW1sR3BKVGxhOTBMT1NkbDlzQ1UtLVBKanhRT3ZKQmdEemRkalR4X083a1VCTjdQQW5hTGRHd2ZwX2YtX1JLanNUOUthQXJHSEYzNWxlWk54Y0xIRG1uaWRLNUROQjhPa0FJYzVObDBlSWRvcUdtMTZEMlVGdXE1YkJ0M0lhMi1DdmxEV2F5TmRpV0FSZDJsTHg5ZG9YanF5ZF9udWZSMWluQ3lsODFGeUl3QzBSVWtFU193NGthUdIBvAJBVV95cUxOaDd2cnlMS1FwOWNBMVR0Qzd2aWZXZ2tPSGpzZkJocDFuY2V3a1NWRnZqdnRDeHJHU0IxNVZwUDhRU0dza21odDByWlZPd3JFc05FbHduNHRqXzFSR0Znbko1b2Fyc3JJUmo1UWs2Q2lnamo1VkJ6ODRiRzg1R1JYQTFUdWZ4S3hkUV9STXhzY25xZF8tNlpkYjBZblBNdzR1SjJ3SVdIMFM1R3pvZlBIbTRBeHZyQ2VqckFVSi11Qlk5bGRDNFFHT0dBdEZtaHpzR253ZXRMZzZQdUk3V2F0WUVYTWdYQU5FTy1ZU1BDVVVWMjU5TGYtcmRUeFhfdXpBdW0tWlFzNVhsZUlsc1pPcExqa0FLSTNsN1EwdlV6LW1xc0tDVjZYUzJCbWdmZ0E2U1ZpN19ka3RQX0lO",
          "breaking": false,
          "slug": "20260622-sona-mohapatra-says-bollywood-heartbreak-songs-are-reserved-for-men-qu",
          "image": "https://upload.wikimedia.org/wikipedia/commons/6/66/Sona_Mohapatra_snapped_at_a_store_launch_in_Khar_%28cropped%29.jpg",
          "image_kind": "photo",
          "image_credit": "Bollywood Hungama / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Sona_Mohapatra"
        },
        {
          "hour": 9,
          "time": "09:00 IST",
          "headline": "Indian kids' IP brand behind 'Emomee' launches its first animated series",
          "what": "The Indian children's intellectual property brand behind 'Emomee' has rolled out its first full animated series, marking a significant step for homegrown kids' content in a market long dominated by foreign IP. The launch, reported exclusively by Variety, signals growing confidence among Indian creators in building original characters and franchises aimed at young domestic audiences. Emomee is positioned as a character-driven brand built around emotional literacy for children, making the animated series a natural extension of the IP.",
          "lens": "As global streaming platforms flood Indian children's screens with foreign content, an Indian-origin kids' IP graduating to a full animated series is a meaningful step toward building homegrown franchises that reflect Indian children's lives and emotions.",
          "source": "Variety",
          "url": "https://news.google.com/rss/articles/CBMihAFBVV95cUxOc1VHdUZ6NzN6SG1KV3BndUU0NjI3bWNTWVlWSWdXa3JTaDVrX1hPNm1pTkR4QWlxUDhDMzk5TENUdFFTZnBmaDRHV0pyWmJlMlVDLVZaSU5ONXlqS3pBWDhZNjk3c1RHYnN0WlBlMmZUZVFpTlRNM3lUXzdEalFBbjhDQU0",
          "breaking": false,
          "slug": "20260622-indian-kids-ip-brand-behind-emomee-launches-its-first-animated-series",
          "image": "https://pixabay.com/get/g34b57c39d2332e8660ecfdc0804e787e4bc9d64fa203c85b73b63ec12d0799d22b2a00bd4daaaa90ba3a6fbc593936d2f81a70244cf668c048b1f1389a806a0e_1280.jpg",
          "image_kind": "photo",
          "image_credit": "stevepb",
          "image_credit_url": "https://pixabay.com/users/stevepb-282134/"
        }
      ]
    }
  ]
};
