// auto-generated 2026-06-22 23:44 IST
window.BRIEF = {
  "date": "Monday, 22 June 2026",
  "edition": "2026-06-22 23:44",
  "topline": "Keir Starmer becomes the sixth UK Prime Minister to fall since Brexit as Lionel Messi breaks the men's World Cup scoring record, while India pursues preferential tariff access in US trade talks and Meta bets $900 million on Kunal Shah to lead WhatsApp.",
  "lensLabel": "Why it matters",
  "sections": [
    {
      "id": "world",
      "name": "World",
      "stories": [
        {
          "hour": 23,
          "time": "23:27 IST",
          "headline": "Lionel Messi Breaks Men's World Cup Record, Becomes All-Time Leading Scorer",
          "what": "Lionel Messi broke the men's FIFA World Cup all-time scoring record during Argentina's match against Austria, cementing his status as the greatest goalscorer in World Cup history. The goal surpassed a record that had stood for decades and arrived as Messi chases further history at what is widely expected to be his final World Cup. The moment was watched by hundreds of millions of fans globally, including a massive Indian audience.",
          "lens": "Messi is one of the most followed sporting figures in India, with a fanbase that rivals any domestic sport hero — this record puts him alone at the summit of football's greatest tournament, a moment Indian fans will remember for decades.",
          "source": "The Guardian",
          "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxPM1dKUTZCajlwZ3hENl9yR19qNlVJSnFOOVY1bHVQMWZuOWVyZDA4RWo3TDZOenI4Wi1ycUxPaHVGTG1QQko3Z1FTcTJveGZyLWxRZ2RNc2VvSkw3eEdyaHVGeGY0T3hCWnVOdEV4RG9kcUxQY3gyMmVDWmdIcFVfQlBPU2ptcjRtcUxIUFRmN0hYZkN2NDVKY0FmX3lvTU1CMXlWQmh5UFpaV3RhYTFxUkMxNlZWLXRkNzdlMEp3?oc=5",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-lionel-messi-breaks-men-s-world-cup-record-becomes-all-time-leading-sc",
          "image": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Lionel_Messi_White_House_2026_%283x4_cropped%29.jpg",
          "image_kind": "photo",
          "image_credit": "The White House / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Lionel_Messi"
        },
        {
          "hour": 22,
          "time": "22:09 IST",
          "headline": "England Name Harry Brook-Led 17-Member Squad for India T20Is; James Coles Gets Maiden Call-Up",
          "what": "England have announced a 17-member T20I squad for the upcoming series against India, with Harry Brook named as captain. James Coles, who earned his maiden call-up after a record-breaking hundred, is the standout new face in the side. The squad selection marks a significant moment for both teams as the T20 format continues to grow in importance ahead of future ICC events.",
          "lens": "India vs England T20Is are among the most watched cricket series globally, with hundreds of millions of Indian fans following every match — the squad news sets up the lineup fans will scrutinise as the series approaches.",
          "source": "The Times of India",
          "url": "https://news.google.com/rss/articles/CBMimwJBVV95cUxOYkhMbzBtZ3VIUlFoOUdmTGx6VjU5VHgxdkk5b2ZsM3AyLW1mZGxnZFlpNGZHVG5JbGVzNXdfM3ZLcjNSSmlVei1wUWZxS2VuT1NzbjBNU24wU2VLeENTcEFBVEZfZE9yTklNU1Flc2FwZmROdG9HYlhNQXBqX1d2QVdnQVFJUUo0S0xHRDh0QUZFVVZoMW55QjJoQXpZQjhkX2hfbGMyUjVMeE01akdDVTFQa3BYd0hyU05fMlVYMGp3ZzE3T0hNNnJvMTg1bWFwUVdDOU9qenFWVk0yVDNlMEQtemkxeVhSSEF4R3JpY00wRlpjWnVPQmp2US0xVi02TzF6cXktRnlxeVA4bFFScGdGQWgyUnR4VDVF0gGgAkFVX3lxTE5PcTNqbmVtc2hoRkFnQzJzWmVkenZNaWZhcXJGcmlBT2t3Z0x3S25JVF9SY2I0TFJaUGZBTTBLOW1kTVZDWlZuUUFWTHZmR0J5cFc4YU5LNUtOUjh5bU9WN1ZjNFVMU2tLNkhnMlliM0J5SjZ4eVlCcFhucDR4bXJKR1BhcmoyYjBQeWdGbkk1QnFaakdYVkZUQUdyQXFQS1lZNV93QU5nUlF0NDJnSkhvYlBrSXR4LW5ycjRIejZoZXYxVm9sUkxTYlZnVm5iMFpkLWNRWTVIYThrbU90TnAzelVCQ0pXNFBNZ0VlQzRkQ3JsUC1wTjBkRnI4dmJIV291bDlIYWlmUE1MTS1PU1ZaTjZCczRZNm8xaWU0NUJZZw?oc=5",
          "breaking": true,
          "_hot": true,
          "slug": "20260622-england-name-harry-brook-led-17-member-squad-for-india-t20is-james-col",
          "image": "https://upload.wikimedia.org/wikipedia/commons/6/63/Harry_Brook_County_cricket_cropped.jpg",
          "image_kind": "photo",
          "image_credit": "Dave Morton / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Harry_Brook"
        },
        {
          "hour": 20,
          "time": "20:16 IST",
          "headline": "US Authorizes Iranian Oil Sales Amid Talks on Final Nuclear Peace Deal",
          "what": "The United States has authorized the sale of Iranian oil as both sides move toward what officials describe as a final peace agreement on Iran's nuclear programme. The move represents a significant easing of sanctions that had strangled Iran's oil exports for years. JD Vance said the US would ensure any unfrozen Iranian funds would not finance terrorism, while Wall Street moved near record highs on easing oil prices tied to the development.",
          "lens": "India is one of the world's largest buyers of crude oil and has historically been a major importer of Iranian oil — any easing of US sanctions on Iranian exports could mean cheaper crude for Indian refiners and lower fuel prices for ordinary Indians.",
          "source": "Reuters",
          "url": "https://news.google.com/rss/articles/CBMiogFBVV95cUxQYzdZaTNrdXFNYWlPV2hKM1g2TDZkUFRmM3pMTE5HZzc1NnRuY1Y1cEdkLWl4bWpWOWFHdmZnMDN0cS0zdFdOeVIzalM0cGN1Yk1PV1lmc0I1NElkUjI5cWtKQzVvdHVqZFFNUm9nT01BZDdlYXFJdnVPM2NiMF9mUFduSFhlcUZWUjV0RVJtY0NFcFVmSElZSXk0V1IxN3ZrLXc?oc=5",
          "breaking": true,
          "_hot": true,
          "slug": "20260622-us-authorizes-iranian-oil-sales-amid-talks-on-final-nuclear-peace-deal",
          "image": "https://upload.wikimedia.org/wikipedia/commons/1/16/Strait_of_Hormuz_and_Musandam_Peninsula_%28MODIS_2018-12-10%29.jpg",
          "image_kind": "photo",
          "image_credit": "MODIS Land Rapid Response Team, NASA GSFC / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Strait_of_Hormuz"
        },
        {
          "hour": 20,
          "time": "20:51 IST",
          "headline": "Meta Taps CRED Founder Kunal Shah as WhatsApp's New Chief, Invests $900 Million in Startup",
          "what": "Meta has appointed Kunal Shah, the Indian entrepreneur who founded fintech startup CRED, as the new chief of WhatsApp, one of the world's most widely used messaging platforms. Alongside the appointment, Meta has invested $900 million in CRED, in what TechCrunch describes as a landmark deal linking two of India's most prominent technology stories. The appointment elevates an Indian founder to lead a global platform used by over 500 million people in India alone.",
          "lens": "With WhatsApp already functioning as a primary communication, payments, and commerce layer for hundreds of millions of Indians, having an Indian founder at its helm could meaningfully shape how the platform evolves its India-specific products and business strategy.",
          "source": "TechCrunch",
          "url": "https://news.google.com/rss/articles/CBMiygFBVV95cUxQekdvbzV0T1VYdk5yeXhTTjFMdlE5WWY5MDFIUmU2ZVNiWm5obGJQWHQwZVFOY1BJM29FeWYzanNBdVdnMDBaS1Mtb3RsdnhYdlFURVVuckJweXltUjJtLWJnTlVDNzNVTlBvZGFoQmtnNF9hWnNONjhjZ2R2N2QtRzBjS0FvUklsTF91Yy1Zc2JHVEVZeERMQXVsS1JDWlFpTlRmSkpuZ0owdzltVG01VFFDUzVqRXh6cm1lckJKejRUZFJNNkJIQlB3?oc=5",
          "breaking": true,
          "_hot": true,
          "slug": "20260622-meta-taps-cred-founder-kunal-shah-as-whatsapp-s-new-chief-invests-900",
          "image": "https://upload.wikimedia.org/wikipedia/commons/8/83/Kunal_Shah_in_FreeCharge_T-Shirt_%28cropped%29.jpg",
          "image_kind": "photo",
          "image_credit": "Kaustubha Dahibhate / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Kunal_Shah"
        },
        {
          "hour": 19,
          "time": "19:53 IST",
          "headline": "X Down for Thousands of Users Globally; India Among Countries Hit by Outage",
          "what": "X, the social media platform formerly known as Twitter, suffered a significant global outage that affected thousands of users, with India among the countries hit. The disruption, which was tracked across downtime monitoring services, left users unable to access feeds, post content, or load the platform. X subsequently recovered from the outage, though no immediate explanation was provided for the cause.",
          "lens": "X remains a primary platform for breaking news, political discourse, and public communication in India — an outage affecting Indian users disrupts real-time information flow for journalists, policymakers, businesses, and millions of everyday users.",
          "source": "Hindustan Times",
          "url": "https://news.google.com/rss/articles/CBMi4wFBVV95cUxNWEc0YmthZTVTR2RfNm12cU4zVDZBLU5Tc1E5V014bnI4aGRsQzlrRjdqSF9IckZVU252X0c2Z0lTQW5PUzlpSXkwUmFIaWZfVjRabFFaUHhaSGFXUDhzZXJvQlhPZEJNYkRDMUFzQW5jdEtnc29HZWdScndMZGV6Q2d4Um9pZWVja3otZ1VQMVdGeTYxMjRrcm1rbFZvNHdZaExiZkNDUVdqXzdaYW5Bc2FjZ0l0MjNvckZPNkxaUkozQTljazFBT25kYkhVc3F2YVdmYTNGYjJVeXo0MFlPdkRsdw?oc=5",
          "breaking": true,
          "_hot": true,
          "slug": "20260622-x-down-for-thousands-of-users-globally-india-among-countries-hit-by-ou",
          "image": "https://pixabay.com/get/gc4b839543e4119808f128e3575a25cb2eb2a5d14fd9a80bb6b3538f104899dde744a4938ca3e1424718ff9cf73f2023923fed1cbae7eebc84f2595dace980beb_1280.jpg",
          "image_kind": "photo",
          "image_credit": "LoboStudioHamburg",
          "image_credit_url": "https://pixabay.com/users/LoboStudioHamburg-13838/"
        }
      ]
    },
    {
      "id": "business",
      "name": "Business & Markets",
      "stories": [
        {
          "hour": 22,
          "time": "22:33 IST",
          "headline": "Tata Electronics hit by cyber breach allegedly exposing Apple and Tesla trade secrets",
          "what": "Tata Electronics, a key supplier to global tech giants including Apple and Tesla, has been hit by a significant cyber breach that attackers claim has exposed sensitive trade secrets belonging to both companies, Reuters reported. The breach targeting Tata Electronics — which manufactures iPhone components in India — raises serious concerns about supply chain cybersecurity and the security of proprietary data entrusted to Indian contract manufacturers by global clients. The incident could have major implications for Tata's relationships with Apple and Tesla and for India's ambitions to become a trusted global electronics manufacturing hub.",
          "lens": "A cyberattack exposing Apple and Tesla secrets at a Tata facility puts India's credibility as a secure global electronics manufacturing destination directly at risk — with consequences for billions of dollars in future contracts.",
          "source": "Reuters",
          "url": "https://news.google.com/rss/articles/CBMi0gFBVV95cUxQbHRnOGVKZXFxVV9uVlMzMWtWeHlnMUhnVy1TclhMZ1VMQkxaZ3NwWXhnODhkYWhSSUNsSV93SEJLQ3FnSk9vZnVFeWFfcG1aNlpMUjJaV2dKbkJ0WTlWWGl4OVd2Zm05REV3MUhnczhZZDlwbUxMM1JUVTRZU0R4QWRmN3IyUWZlckJtd3JKSmlaS0RyYzJHU3BJTWlTTlFLNlhHcDlUQWZicW9OZ3RxVGFaTFRuekpabF9kM2xKd2hIYnRrVkJqMi1Od1lXLXV5OWc",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-tata-electronics-hit-by-cyber-breach-allegedly-exposing-apple-and-tesl",
          "image": "https://images.pexels.com/photos/5380655/pexels-photo-5380655.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Tima Miroshnichenko",
          "image_credit_url": "https://www.pexels.com/@tima-miroshnichenko"
        },
        {
          "hour": 18,
          "time": "18:50 IST",
          "headline": "India becomes world's top ship recycling nation in 2025, hits Vision 2030 target five years early",
          "what": "India has overtaken all competitors to become the world's number one ship recycling nation in 2025, achieving a target set under its Vision 2030 maritime plan a full five years ahead of schedule, Mint reported. The country's ship recycling yards — primarily at Alang in Gujarat, the world's largest ship-breaking facility — have processed the highest volume of tonnage globally this year, surpassing Bangladesh, Pakistan, and Turkey. The achievement marks a significant milestone for India's maritime and steel industries and reinforces the country's position in the global circular economy.",
          "lens": "India's global leadership in ship recycling means cheaper secondary steel inputs for domestic industry and thousands of jobs at Alang — a real economic dividend from maritime policy hitting its target early.",
          "source": "Mint",
          "url": "https://news.google.com/rss/articles/CBMi9AFBVV95cUxNQmt2T0RCLThoLS0tVl84ZU12R1FyS1ZERzhUakhtRThGMUQzYW1wYjlnOUtHbkJjZ3dzU2lPR0xfQWE5UVIzUXdXby0xdVJSTW1SdGlQTnBubGxVUTZYNWJpcERKem9jQ25TdGtxVWRTWkNham1mNTR1R0pJNlNPall0QjBVUXFPTEplYl9zZmVDOUZjbEQ3alhIRWwyQ3BORlVYNGdGUGsyQkVTYjY1Z2E1eUJSTUYyV2M0d09GZ0ZmR3BPLXdoLXdJejVXMWRQTnUtQWNJRENZRkE1MkEzaVhXY1dFSHp1bkVzdmx5Rm1tT0Mt",
          "breaking": true,
          "_hot": true,
          "slug": "20260622-india-becomes-world-s-top-ship-recycling-nation-in-2025-hits-vision-20",
          "image": "https://upload.wikimedia.org/wikipedia/commons/4/40/Shipwrecking_in_Alang%2C_India%2C_2017-03-23_by_Planet_Labs.jpg",
          "image_kind": "photo",
          "image_credit": "Planet Labs, Inc. / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Alang_Ship_Breaking_Yard"
        },
        {
          "hour": 17,
          "time": "17:16 IST",
          "headline": "India's core sector growth hits seven-month low of 0.5% in May",
          "what": "India's eight core industries — which include coal, crude oil, natural gas, refinery products, fertilisers, steel, cement, and electricity — grew by just 0.5% in May, the slowest pace in seven months, according to government data reported by Business Standard. The steep deceleration from recent months signals a softening of industrial momentum at a time when the broader economy has otherwise been showing signs of recovery. The core sector accounts for roughly 40% of the Index of Industrial Production, making it a key barometer of manufacturing and infrastructure health.",
          "lens": "A near-stall in core sector growth at 0.5% directly signals weaker industrial and infrastructure activity, which can translate into slower job creation and tempered business investment for ordinary Indians in the months ahead.",
          "source": "Business Standard",
          "url": "https://news.google.com/rss/articles/CBMizgFBVV95cUxQTWU1SFdYUm5GYWl1ME9wTjBWaXc4T2h2MmFnQ0NCeS1SYVFJZkhSeF9BTE8wRDhKNkxObFFsdU5qQ0tySWZXNzBIeGNYSzNrdDNpU0JkN2tDdGZfc20xbDZXQUdIOFNIMEFWRl9ibkVoaHNQSGJCd29lQjZLZU5IZFI3ODB0WEFFRk5xVXZIX1UwSG9uV0tjQ25uQk1BZ0ZVSjBBNXpHZmZ6dVl2SUxlVDYwNUI4RGNHSWZpY09FcWRiU2hfVUs2WUE5VU9RQQ",
          "breaking": false,
          "_hot": true,
          "slug": "20260622-india-s-core-sector-growth-hits-seven-month-low-of-0-5-in-may",
          "image": "https://images.pexels.com/photos/31199564/pexels-photo-31199564.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "EqualStock IN",
          "image_credit_url": "https://www.pexels.com/@equalstock"
        },
        {
          "hour": 16,
          "time": "16:40 IST",
          "headline": "India imposes anti-dumping duty on rubber chemical imports from China, EU and US",
          "what": "India has slapped anti-dumping duties on imports of a key rubber chemical from China, the European Union, and the United States, in a move aimed at protecting domestic manufacturers from unfairly priced foreign competition. The duty targets a specific rubber processing chemical used widely in tyre and automotive component manufacturing — industries where Indian producers have complained of being undercut by subsidised imports. The decision, reported by The Times of India, reflects India's increasing willingness to deploy trade defence instruments to shield domestic industry.",
          "lens": "Anti-dumping duties on rubber chemicals will directly affect tyre manufacturers and auto component makers — potentially pushing up costs that could filter through to vehicle prices for Indian consumers.",
          "source": "The Times of India",
          "url": "https://news.google.com/rss/articles/CBMi9gFBVV95cUxNNWtuRDRGM0VNRkM2bnRIblhhMTdHaXBJQV9qVmRNVmdDaEc3bUtzd09aQnBXUG9XSmlON1dEOWtxSjRNRmtyaG1wc2Y1VHYxOXlTTlpBTFZwbWNlMTZfNVltMEtIWVpVRXdHdmw0NGw2dnlycU02alRja3RGMzdPTmw3TlpVU1pWRVJCOTllQ2hfYnE5YnZtMkFYSkI0T2hvcXJMaHVkcFJCbjlaYTV2bXdkUDd6QWNmdGtGdWJsbmFTQkEtSXlZMTZLZ3FERjUwSUFQZE1WZXhjYnZkSkJXa1hGYU1JazlYZHprWHEtamdRc1dqS2c",
          "breaking": false,
          "_hot": true,
          "slug": "20260622-india-imposes-anti-dumping-duty-on-rubber-chemical-imports-from-china",
          "image": "https://images.pexels.com/photos/31336008/pexels-photo-31336008.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "EqualStock IN",
          "image_credit_url": "https://www.pexels.com/@equalstock"
        },
        {
          "hour": 15,
          "time": "15:26 IST",
          "headline": "India's economy is booming — so why are foreign investors looking away?",
          "what": "Despite India posting strong GDP growth figures and a buoyant domestic market narrative, foreign portfolio investors have been pulling back from Indian equities, raising a paradox that India Today explores in depth. Elevated valuations, a relatively strong rupee reducing currency-adjusted returns, concerns about corporate earnings sustainability, and competition from other emerging markets have all been cited as factors dampening overseas enthusiasm. The divergence between India's macroeconomic story and foreign investor behaviour has become one of the defining tensions for Indian financial markets in 2025.",
          "lens": "Foreign investor hesitation despite India's growth boom directly affects stock market performance and the rupee — both of which hit the savings, mutual fund returns, and borrowing costs of ordinary Indians.",
          "source": "India Today",
          "url": "https://news.google.com/rss/articles/CBMizgFBVV95cUxQb21EZXlObVFHN05FSE9iNFVBc2cwbGd2QUh4N0VBd0NEM3AtMGhjVFFZRTJwaVBseUJhTDZ2ZGdLdmw4OVdyN0NzTVNTOFg2cm1rcjZqbk1aTUlrdFJfU3EzVWxPemZHS1g1emNWVml6Qlo4V2RNendDMEgwZlhkdmZ5S0RCMnZGaUg3TE1kU1poVDdKNkw2UkNDY0lQN3JpQVlwUkRXZGVLYVhDc2xxeGQwbE82MmU0XzhRUWU5Y1p3aWpNaHlCeDYwSl81Zw",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-india-s-economy-is-booming-so-why-are-foreign-investors-looking-away",
          "image": "https://upload.wikimedia.org/wikipedia/commons/4/4b/BSE_building_at_Dalal_Street.JPG",
          "image_kind": "photo",
          "image_credit": "BSEINDIA / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Bombay_Stock_Exchange"
        }
      ]
    },
    {
      "id": "tech",
      "name": "Technology",
      "stories": [
        {
          "hour": 22,
          "time": "22:30 IST",
          "headline": "Valve Prices the Steam Machine at $1,049",
          "what": "Valve has officially priced its Steam Machine gaming PC at $1,049, marking a significant development for the PC gaming hardware market. The Steam Machine, which runs on Valve's Linux-based SteamOS, aims to bring the Steam gaming library to a living-room console-style form factor. The pricing positions it above mainstream gaming consoles but below high-end custom PC builds. The announcement is expected to reignite interest in SteamOS as a Windows alternative for gamers.",
          "lens": "For India's rapidly growing PC gaming community, the Steam Machine's pricing sets a benchmark for what a dedicated living-room Linux gaming device costs, influencing import and grey-market interest.",
          "source": "The Verge",
          "url": "https://news.google.com/rss/articles/CBMigAFBVV95cUxQYU81ZVgtbFFmeXQydU4zYVNySG9vVkt6dGFTWUQ4LXFla1QzRXM2ZXRMMnl4R3NucGdETHo3YzdkVTJtYngyMEZSdkcwWnhScHVkNkpzYl9jbFNaTVFxRHJ0OVA4LVE0cGhNemRmNVFhWDctTHREM2JObUdTVXBRRQ",
          "breaking": true,
          "_hot": true,
          "slug": "20260622-valve-prices-the-steam-machine-at-1-049",
          "image": "https://upload.wikimedia.org/wikipedia/commons/2/27/Valve_Lobby_2016.jpg",
          "image_kind": "photo",
          "image_credit": "Tim Eulitz / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Valve_Corporation"
        },
        {
          "hour": 20,
          "time": "20:25 IST",
          "headline": "Air India Appoints Former Civil Aviation Secretary as Advisor to Chairman",
          "what": "Air India has appointed a former civil aviation secretary of India as advisor to its chairman, the airline announced. The appointment brings high-level regulatory and policy expertise into the carrier's leadership structure at a critical period of its transformation under the Tata Group. Air India is in the midst of a sweeping overhaul — expanding its fleet, integrating acquired carriers, and rebuilding its service reputation after decades of government ownership. Adding a former top bureaucrat as a strategic advisor signals the airline's focus on navigating complex aviation policy and regulatory relationships.",
          "lens": "As Air India undergoes its biggest transformation in decades under the Tatas, bringing in a former civil aviation secretary strengthens its hand in dealing with DGCA regulations, airport slot negotiations, and government policy — all of which affect ticket prices and route availability for Indian flyers.",
          "source": "The Economic Times",
          "url": "https://news.google.com/rss/articles/CBMigAJBVV95cUxOLWNNMk5pTUlRSktRZ2szb21aNXI4dk1CRE12VlRvM083TkFxMWViXzNOWXZwNktiTnJVQ3VNY09LeGJwUU5CT1RvSFkwUHVadzM2UnFRcmM0MVB3ajBJRVlydmVJVU5UZjlTOFBVaHRTNE5hcE9IYUhQV0JlM2pZZXA3MFZSUlROTnp0TjdnbUJuRWlCSkJHNmY3YkM3Y1ZWM3dCdG9YQVhoQkU0clE3d3NjNmlsV255ZHh1cS1BNlVHQlpNYlBnc3o5UG1UbEFYQVJYbEJsUTFMNWxBUFhrZ0xmNFpGeEVyWDhXZ3l3UG50MHFfZWVic29XTGhINlRI",
          "breaking": true,
          "_hot": true,
          "slug": "20260622-air-india-appoints-former-civil-aviation-secretary-as-advisor-to-chair",
          "image": "https://pixabay.com/get/ge97d2214a05e38fe03ad6f5b6df0b42a97b09484430a4cac001555f719daf25b274d7deb2e2e3b1b1c3261152a6e12b3ccd4b3bf892673c7fe2ffad4d6fb6507_1280.jpg",
          "image_kind": "photo",
          "image_credit": "652234",
          "image_credit_url": "https://pixabay.com/users/652234-652234/"
        },
        {
          "hour": 16,
          "time": "16:47 IST",
          "headline": "Satya Nadella Tells Google, OpenAI and Anthropic: You Can't Win the AI Race Alone",
          "what": "Microsoft CEO Satya Nadella delivered a pointed message to rival AI companies including Google, OpenAI, and Anthropic, signalling that no single player can dominate the artificial intelligence landscape independently. Nadella's comments underscore the increasingly collaborative and competitive dynamics in the global AI race, as major technology firms race to deploy large language models and AI-powered products. The remarks come as Microsoft deepens its own AI integration across Office, Azure, and its Copilot suite. His statement is seen as a strategic repositioning of Microsoft as a platform and partner rather than a pure competitor.",
          "lens": "Nadella's comments matter to Indian tech professionals and enterprises adopting AI tools, as they signal how Microsoft's Azure and Copilot ecosystem — widely used in India — will evolve relative to Google and OpenAI.",
          "source": "The Times of India",
          "url": "https://news.google.com/rss/articles/CBMiwgJBVV95cUxOeGJncFI3bHZoWjdLN3J6c2VyUFdReGg5WjJhcy1pNF94QUFYV212OEF2UHE4V0tlTWxRN0NPeG9qOHRGLXZZeUVKS2FFVFVMalhWU0tXSWxFa1g1c1MtaENSNmFVYkpsTDdaMV8ybVNQemdVRHVscWVUREc4UWZJYm8yb3lUWGpZSlZNSmxBbXV5czFtRUJsa2hCTEF2QnctV1NHOHJTRmxPOGdsc1ZHdG5XYzBjYWtUdXJvNnRJeUluNWpRTTdFSC1fc242MndaMjZjMFNEVFo2Qm1Gd2ZNVGVvSkFLMldEWDhqTld5R3BfZFVIOE51NERXbkY2UFBwa2d1YXBrdXVUT1daekliczBVTmNiVHhaNkNSMXlQb1VlUEpqeng5bzFCNE9pSXRkVWRVV2ZCSzhweUcxd0tiN3dn",
          "breaking": false,
          "_hot": true,
          "slug": "20260622-satya-nadella-tells-google-openai-and-anthropic-you-can-t-win-the-ai-r",
          "image": "https://upload.wikimedia.org/wikipedia/commons/7/78/MS-Exec-Nadella-Satya-2017-08-31-22_%28cropped%29.jpg",
          "image_kind": "photo",
          "image_credit": "Brian Smale and Microsoft / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Satya_Nadella"
        },
        {
          "hour": 16,
          "time": "16:55 IST",
          "headline": "Krafton India Makes Strategic Investment in Bitkraft Ventures' Global Gaming Fund",
          "what": "Krafton India, the Indian subsidiary of the South Korean gaming giant behind BGMI (Battlegrounds Mobile India), has made a strategic investment in Bitkraft Ventures' global gaming and interactive entertainment fund. The move signals Krafton's intent to deepen its footprint in the Indian gaming investment ecosystem beyond its core publishing and development business. Bitkraft Ventures is a specialist gaming-focused venture capital firm with a global portfolio. The investment positions Krafton India as a financial backer of emerging gaming ventures worldwide.",
          "lens": "Krafton India backing a global gaming VC fund shows how India's gaming market — one of the world's largest by users — is maturing from a consumer market into a source of investment capital for the global games industry.",
          "source": "Business Standard",
          "url": "https://news.google.com/rss/articles/CBMi3wFBVV95cUxNdXdOQ2ZWNWotYjVVTEU4OVRmV2U0QUVRcnBKMDdsUVdpWl9IaGc4bUV0ZFR4MVlFb2dLNzFGM2lobGlUQ29UYVNnZDBUenMwcUpQY3gyOVQ0LWJpZXRxUVpTcjdnMkt1dUlrWWdZbHNsQjVrY3hudzBzNEtKOHRHQmpHVGxFbjdqZkw5VWozT2tlTFZzTFBtZGFIMlhBLU5BQmVZcTUxdGh1bExGQ3NKckVBMGJjajB5VzBrVTZ2NURVeWFXYjktRm1hZUlBa0hjdl9ZT0xUX3pTVkxWSVNz",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-krafton-india-makes-strategic-investment-in-bitkraft-ventures-global-g",
          "image": "https://images.pexels.com/photos/7915285/pexels-photo-7915285.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "RDNE Stock project",
          "image_credit_url": "https://www.pexels.com/@rdne"
        },
        {
          "hour": 16,
          "time": "16:47 IST",
          "headline": "Satya Nadella Warns AI Companies: 'You Can't Win by Hoarding'",
          "what": "Microsoft CEO Satya Nadella has issued a pointed message to rivals including Google, OpenAI, and Anthropic, signalling that the era of closed, proprietary AI development is not a sustainable winning strategy. Nadella's remarks, reported by The Times of India, come as the global AI race intensifies and Microsoft deepens its own open-ecosystem bets through its partnership with OpenAI and investments in open-source tooling. The statement is being read as a strategic positioning move ahead of what could be a landmark period of AI standardisation.",
          "lens": "As Indian developers and businesses increasingly build on AI platforms, Nadella's push for open AI ecosystems could determine which tools — and whose rules — shape India's own AI industry.",
          "source": "The Times of India",
          "url": "https://news.google.com/rss/articles/CBMiwgJBVV95cUxOeGJncFI3bHZoWjdLN3J6c2VyUFdReGg5WjJhcy1pNF94QUFYV212OEF2UVE4V0tlTWxRN0NPeG9qOHRGLXZZeUVKS2FFVFVMalhWU0tXSWxFa1g1c1MtaENSNmFVYkpsTDdaMV8ybVNQemdVRHVscWVUREc4UWZJYm8yb3lUWGpZSlZNSmxBbXV5czFtRUJsa2hCTEF2QnctV1NHOHJTRmxPOGdsc1ZHdG5XYzBjYWtUdXJvNnRJeUluNWpRTTdFSC1fc242MndaMjZjMFNEVFo2Qm1Gd2ZNVGVvSkFLMldEWDhqTld5R3BfZFVIOE51NERXbkY2UFBwa2d1YXBrdXVUT1daekliczBVTmNiVHhaNkNSMXlQb1VlUEpqeng5bzFCNE9pSXRkVWRVV2ZCSzhweUcxd0tiN3dn",
          "breaking": false,
          "_hot": true,
          "slug": "20260622-satya-nadella-warns-ai-companies-you-can-t-win-by-hoarding",
          "image": "https://images.pexels.com/photos/30608594/pexels-photo-30608594.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "UMA media",
          "image_credit_url": "https://www.pexels.com/@uma-media-2149408028"
        }
      ]
    },
    {
      "id": "national",
      "name": "National",
      "stories": [
        {
          "hour": 23,
          "time": "23:19 IST",
          "headline": "Rs 38,000 Crore at Stake as Delhi Government's Court Battle With Power Discoms Over Audit Drags On",
          "what": "A high-stakes legal battle between the Delhi government and the city's electricity distribution companies — discoms — over a financial audit is continuing in court, with Rs 38,000 crore at the centre of the dispute, India Today reports. The Delhi government has been pushing for an independent audit of the discoms — BSES Rajdhani, BSES Yamuna, and Tata Power Delhi Distribution — alleging that consumers have been overcharged and that the companies have reaped excess profits over the years. The discoms contest this position, and the matter has been tied up in litigation, with the audit's findings potentially reshaping electricity pricing for millions of Delhi households.",
          "lens": "With Rs 38,000 crore at stake and Delhi's electricity bills among the most debated political issues in the capital, the outcome of this case could directly determine whether millions of households see lower power tariffs or continued high bills.",
          "source": "India Today",
          "url": "https://news.google.com/rss/articles/CBMi2wFBVV95cUxONUhsOHRsY0FIdjF1OUhEeHNka0Z1S2RVeGJSVWY5NU9yOWg4WWN6azdzNnZ6WS1tWW0xa1NEc0UzRFgzWDhXemtKN0k2Z0V0RDVnVzVBRlE5djlqWUpIRUE2MlhUd0d6alc3MjROd3FzTVYyRlhNU3VuSExwNFVSbUtoSnlRZTJjM3dpZm1YZGFqUDdEalZidndPZ2RIUjhEQWhZcXZ3Z0N0VHZmaGhJU3VFVnlUcnF3aDFXWkxqNktZczB2b09DNUYybFNvV2pWM1g0eGs4MVpoVTg",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-rs-38-000-crore-at-stake-as-delhi-government-s-court-battle-with-power",
          "image": "https://upload.wikimedia.org/wikipedia/commons/4/40/Jama_Masjid_2011.jpg",
          "image_kind": "photo",
          "image_credit": "Marcin Białek / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Delhi"
        },
        {
          "hour": 17,
          "time": "17:09 IST",
          "headline": "'6 Tigers Are Here': Rebel Uddhav Sena MPs Join Eknath Shinde Camp in Major Political Shake-Up",
          "what": "Six rebel Shiv Sena MPs loyal to Uddhav Thackeray have formally joined Eknath Shinde's faction, in a development that further consolidates the Shinde camp's grip on the party's parliamentary strength. The defections, announced with the taunt '6 Tigers are here', mark a significant blow to the Uddhav Sena as it continues to contest the legitimacy of Shinde's leadership. The move deepens the ongoing split in one of Maharashtra's most storied political parties and could have implications for upcoming electoral contests in the state.",
          "lens": "The Shiv Sena split has reshaped Maharashtra's political balance of power — each defection narrows Uddhav Thackeray's ability to mount a credible challenge to the Shinde-BJP alliance.",
          "source": "NDTV",
          "url": "https://news.google.com/rss/articles/CBMipwFBVV95cUxNSDYxdlp2QkVSSlpGLVV3dUdkRG1xRWZHcEJ0Y3R3Y3hubWxacDdxS25lUmdhZVhpVXd1eXNLaTFQUkw3R2wyYzhZTEhxcEZ1S2xGWVlqNWhRc3VGQmVva0RVS3NJZlpMNlltSjFQdUNPNUloX3NrRUlJOEJmVjZ6dkU3eEFaUHBuM3lKWlF0dkRIc21DX0ZzcHRPeHkyaDBlNGR2U2RHSQ",
          "breaking": false,
          "_hot": true,
          "slug": "20260622-6-tigers-are-here-rebel-uddhav-sena-mps-join-eknath-shinde-camp-in-maj",
          "image": "https://upload.wikimedia.org/wikipedia/commons/5/53/Eknath_Shinde_SS.jpg",
          "image_kind": "photo",
          "image_credit": "Real96kmaratha / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Eknath_Shinde"
        },
        {
          "hour": 17,
          "time": "17:10 IST",
          "headline": "India in Talks to Sell Supersonic BrahMos Missile to UAE in Major Defence Export Push",
          "what": "India is in advanced discussions to sell the BrahMos supersonic cruise missile to the United Arab Emirates, in what would be one of the country's most significant defence export deals. The BrahMos, jointly developed by India and Russia, is one of the fastest cruise missiles in the world and a flagship product of India's defence manufacturing ambitions. A successful sale to the UAE would mark a major step in India's push to become a global defence exporter, following earlier BrahMos deals with the Philippines. The deal also carries strategic significance given the UAE's importance in India's Middle East partnerships.",
          "lens": "A BrahMos sale to the UAE would directly boost India's defence export revenues and signal to global buyers that Indian-made weapons systems can compete at the highest level — with real economic and geopolitical dividends for the country.",
          "source": "News18",
          "url": "https://news.google.com/rss/articles/CBMi6AFBVV95cUxQRkRVWVZtTlB2WC1GTWE1VFJXeFZLU2FsVjU3LUZwR1NqRTRHcGdxLXVTYmM2M1hZRjNhWHV6ZVZ1ZU1QVHBDNXEwanNlaGt0elh2bURDUVFkVHNwTFRPTWg3anZiY2FBeV8tVmhIMGJUVGNndmhERTR4UzlqNFNoZXY2Nm9mUmVXVzdDNE1pY01XcjM5Nm5YODdQQzlrSzE4Q0JtdmlrWFBQYkZVeVJyZ29GNVZnZTAzMGtDVHlzMk96WUo4UjR2MUNUZFA3NWN5cExTZE81dEtfdjRhZVZrcWZRZVdOaDF20gHuAUFVX3lxTFBoNFhSaXpVZzd4NjRrT19wbzF1bnJtUVVWWnVUZmk0MXF4MzF1cUUtMVVmQ1R5cEZubXFZcjJoeW5UWWlVMlg2MHRJOHAzcDUxZnUyNVpiZ3hDY3NMeEg2OUphQnRrdDYwOTNVdDIzcENfOGtQZmpSRjVJLS14c3RVZlY0N0U5dDFPY3hDSUVtRklrVWJ1VGlRRzU0ckdaM3VmenVXNXl5c3U2eExaNXFGZklnZzdKUncwS1RaeFVwQnA5UWQ0VWpMYzdDYnRINmtHSDRWYU5KS2ZWV0tBR1ZJMGp6UHdSdWZWV3FKMVE",
          "breaking": false,
          "_hot": true,
          "slug": "20260622-india-in-talks-to-sell-supersonic-brahmos-missile-to-uae-in-major-defe",
          "image": "https://upload.wikimedia.org/wikipedia/commons/c/ce/The_Brahmos_Missile_system_passes_through_the_Rajpath_during_the_full_dress_rehearsal_for_the_Republic_Day_Parade_in_New_Delhi_on_January_23%2C2006.jpg",
          "image_kind": "photo",
          "image_credit": "Ministry of Defence / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/BrahMos"
        },
        {
          "hour": 16,
          "time": "16:09 IST",
          "headline": "15 Killed in Fire at Lucknow Coaching Centre, Students Jump From Building to Escape",
          "what": "A devastating fire tore through a coaching centre in Lucknow, killing at least 15 people and forcing students to leap from the first floor to save their lives. The blaze engulfed the building rapidly, trapping students who had been attending classes. Emergency services rushed to the scene as eyewitnesses described scenes of panic and chaos. The tragedy has reignited urgent concerns about fire safety and building code violations at commercial coaching institutes across India.",
          "lens": "Coaching centres are where lakhs of Indian students spend long hours daily — this fire raises an immediate question about whether the building where your child studies meets basic fire safety norms.",
          "source": "NDTV",
          "url": "https://news.google.com/rss/articles/CBMisgFBVV95cUxPYmJ1c0xoM2tVQWF2Y2JKbXV1Tm85dzFwNUVUdVlDdmROcEtYVnJPUnpxNmJzTFdxcU1JZERtSzlyYlVHVEoxWXRFRWYzWFNTdFBWUUVCNE5fbFdtdEV2WHd1cWU1YlRzajFGcEVCMU9JdG4wWXF2aDFySHdGckhkNEt5SlFJSWhncVlXd3VsbEx6Tld6Mm02cVdkaU5FWkNzVGpyRjludG1tTE1TMEI2SVFB",
          "breaking": false,
          "_hot": true,
          "slug": "20260622-15-killed-in-fire-at-lucknow-coaching-centre-students-jump-from-buildi",
          "image": "https://upload.wikimedia.org/wikipedia/commons/5/51/Harzratganj_Market%2C_Lucknow.jpg",
          "image_kind": "photo",
          "image_credit": "Mohit / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Lucknow"
        },
        {
          "hour": 13,
          "time": "13:15 IST",
          "headline": "Supreme Court Rules Right to Walk on Footpaths Is a Fundamental Right",
          "what": "The Supreme Court of India has declared that the right to walk on footpaths is a fundamental right of citizens, in a landmark ruling that takes direct aim at the rampant encroachment of pavements by vendors, parked vehicles, and illegal structures in Indian cities. The court's observation elevates pedestrian access to constitutional status, making it actionable against municipal authorities that fail to maintain usable footpaths. The ruling is expected to force civic bodies across the country to treat pavement upkeep and clearance as a legal obligation rather than an optional civic duty.",
          "lens": "For the millions of Indians — especially the elderly, differently-abled, and those without private transport — who walk city streets daily, this ruling provides a constitutional basis to demand safe, clear footpaths from municipal bodies.",
          "source": "The Business Standard",
          "url": "https://news.google.com/rss/articles/CBMiswFBVV95cUxPcFlDczRQVk5NM1l5RVc1RGYyYkl0XzRwNjVpd3FJNnlGSzFMX19TT0toRWNSRmIxdy11Z1lkcHdwVXFuR0tKZjMwSFZYWnhBMGswS1J3SUJhMnJRcTEzam12ZXBMei1mZkRtcTVoamx2bXd1MDBZSm1RT3JfR0NVRWVGc2htNmg2eWNNaXd2UUlWb2toZlVQSlhNNmRKZjNneGFvajFuZmRyOWlxTVBEMzhTUdIBuAFBVV95cUxQSEhXa2h1dkdsenJQemNDbVFfbHhJTzh0QzZ0ME5BNHFBX3VpamxHajhSWUE1cHJxSGtkR3BXYlJpanU0MW1odi1aUlVJZnhWU0Z2azFobXF3UXFQUzE4OWJuUnprTF90R3R4OUcwMXVZQlBpVTJuaGVLTFlPZGNrb0laM1hSQmZFN2tpRllnank4LWhkRDE1UkNRWEo4c0NDTy04UEZtMWxqTmJzTnJINS1MRHdwaVB1",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-supreme-court-rules-right-to-walk-on-footpaths-is-a-fundamental-right",
          "image": "https://images.pexels.com/photos/365813/pexels-photo-365813.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Dom J",
          "image_credit_url": "https://www.pexels.com/@dom-j-7304"
        }
      ]
    },
    {
      "id": "ai",
      "name": "Artificial Intelligence",
      "stories": [
        {
          "hour": 22,
          "time": "22:34 IST",
          "headline": "AI models capable of taking down governments and businesses are months away, Five Eyes alliance warns",
          "what": "In a rare joint statement, the Five Eyes intelligence alliance — comprising the US, UK, Canada, Australia and New Zealand — has warned that AI models powerful enough to destabilise governments and disrupt major businesses could be available within months. The statement marks an unusually direct public alert from the world's most influential intelligence-sharing bloc about near-term AI risks. It underscores growing concern among Western security establishments that frontier AI capabilities are advancing faster than regulatory and defensive frameworks.",
          "lens": "A joint warning from the world's top five intelligence agencies that destabilising AI is months away is a direct signal that AI governance — including India's own AI policy — needs urgent acceleration.",
          "source": "The Guardian",
          "url": "https://news.google.com/rss/articles/CBMiwgFBVV95cUxNTklxTWJwcms1UlBCeUYyTGtNTGFtdEtGcmR3bEJJWHY2VHRpbUJqR3lUdW13RkF6MWJ4SklkWEtEYUlOLURENnRDNWNjN1dCclZVVGNOQVV0OEg5U0gyY2pGWDVDY3JUR3lKelJGSHdxUUM1UXY2UXFpa09idjN1Z0ZLNFZWX2dmR1FyaDRrM2NVY2trNFJwbjJHdWZuYUUtck1rWU9VRWZEbV9kT2hXOUNxbm1iU3FwTlp3dzkzdUhQdw",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-ai-models-capable-of-taking-down-governments-and-businesses-are-months",
          "image": "https://pixabay.com/get/gff951d9a9e173b58ba5d3cb4ef925a7220f8cc28ab068b976856fb9eb3a6f211c93bd4dd1c5fbd569afa8f91a623fb0f8ee0249935fbe77c0d79c334c7d5f651_1280.png",
          "image_kind": "photo",
          "image_credit": "Janson_G",
          "image_credit_url": "https://pixabay.com/users/Janson_G-5907103/"
        },
        {
          "hour": 21,
          "time": "21:46 IST",
          "headline": "Alphabet heads for worst day in a year as AI concerns and high-profile exits rattle investors",
          "what": "Alphabet, Google's parent company, was on course for its worst single-day stock performance in a year after a wave of AI-related concerns and high-profile employee exits unsettled investors, according to CNBC. The sell-off reflects mounting anxiety about whether Google can maintain its competitive position in AI against OpenAI, Anthropic and Microsoft. The development comes as rival AI labs continue to attract talent and capital at an accelerating pace, putting pressure on Alphabet's standing as a foundational AI company.",
          "lens": "Alphabet's worst trading day in a year signals that investors are losing confidence in Google's AI strategy — a shift that matters to Indian tech firms, startups and developers who rely heavily on Google Cloud and its AI tools.",
          "source": "CNBC",
          "url": "https://news.google.com/rss/articles/CBMiekFVX3lxTFB0bUh0Uk95MWYxNVZRc2VQdFpaWWRYZEJ0MEdQOWhFWkNNa19pdDcyazBqTGE2MHdMTzhfTHh5STk2NVB0d2dsMlFFb0JteGR4MWxsY3VPUWM4NjdHUk1PY2pJdVA4S1E1allZS0JMWjAyX0lMdUlRRHZR0gF_QVVfeXFMTzFzeWhOZXAwdk9JNDJvekdBajl4X1lBSU0yUmkxVGpoS09rZmFoMDdMRUZkckM2TEs0M3JsZ3hxcThhS0xLRDhIeVVZU3otdWMteGVzMHdNMXBYdVRfZk0xZzg1NU1RbUlrVzNnTXNuX3Y4dEN2aGlzVllRNFA1Yw",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-alphabet-heads-for-worst-day-in-a-year-as-ai-concerns-and-high-profile",
          "image": "https://upload.wikimedia.org/wikipedia/commons/e/e2/Google_Campus%2C_Mountain_View%2C_CA.jpg",
          "image_kind": "photo",
          "image_credit": "Austin McKinley / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Alphabet_Inc."
        },
        {
          "hour": 21,
          "time": "21:28 IST",
          "headline": "Micron invests in Anthropic and partners on AI memory infrastructure",
          "what": "US chipmaker Micron has announced an investment in AI safety company Anthropic and a strategic partnership focused on AI memory infrastructure, according to Analytics India Magazine. The deal brings together Micron's expertise in high-bandwidth memory — a critical bottleneck in running large AI models — with Anthropic's frontier model development. As AI models grow larger and more capable, memory architecture is increasingly recognised as a key competitive frontier, and Micron's move signals that semiconductor companies are racing to embed themselves into the AI value chain at the infrastructure level.",
          "lens": "Micron's bet on Anthropic's AI memory needs shows that the hardware race underpinning AI is intensifying — relevant to India's semiconductor ambitions and to Indian AI startups that depend on the cost and availability of AI compute.",
          "source": "Analytics India Magazine",
          "url": "https://news.google.com/rss/articles/CBMipAFBVV95cUxNZFNjZ0ZqbEVWTm9rM3c5T0x4c1Zkam9acjlKUFoxUkNGLVhJaWlDNUNBRWppMDN2ZC1ldDZSM2E3R1llcGtlVVpNRnNQcGJxR00wM3FWYXRLZnBEdmdTRU5zV2MxUWtNdmpqc1BuNnFuQ1RId19oTHpUNVF4NDVWQzJROFBoSkpocS1KTnFDd1VJOWI2YWRqMXJZcEVodnhxd18tVQ",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-micron-invests-in-anthropic-and-partners-on-ai-memory-infrastructure",
          "image": "https://pixabay.com/get/ge36b1970dfa6b5f881a1a6a1d9f8cb18432a7e1995819207dd9833c15184d57b91634f3061ff26c11a413b748ce3890653dfbdedf0bfbd59a4d5532c08aba01a_1280.jpg",
          "image_kind": "photo",
          "image_credit": "ElasticComputeFarm",
          "image_credit_url": "https://pixabay.com/users/ElasticComputeFarm-1865639/"
        },
        {
          "hour": 17,
          "time": "17:37 IST",
          "headline": "What is GLM-5.2? China's latest open-weight AI model turning heads in Silicon Valley",
          "what": "China's latest open-weight AI model, GLM-5.2, is attracting significant attention in Silicon Valley for its competitive performance relative to leading US models, according to The Indian Express. Developed by Zhipu AI, GLM-5.2 continues China's streak of releasing capable open-weight models that challenge the assumption of US dominance in frontier AI. Open-weight models are particularly significant because they can be downloaded and run independently, making them harder to restrict and easier for developers worldwide to build upon.",
          "lens": "GLM-5.2's arrival matters to Indian developers and startups because open-weight Chinese models offer a powerful, freely available alternative to paid US AI APIs — potentially reshaping which AI infrastructure India's tech ecosystem builds on.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMivgFBVV95cUxPNWkycHBOUjlrWnhpclpDd0hJZ3gxR0VTVmtkMG1LWlJLOG1UZ09mWkpBZmpnMFNwVF83aGFRQ3Q3WVZaME5ReDIyNHJaNm5hTm1aZUZtc1lZM3FkR2wzUW1la2tvdmltZFZOSUFfLURaT0ROSl85Z1dJOUhDclBoQ0dMNGg5QUN5ajhtQlR1eUwxdUVFOHJYYzhDbjZJWk5DckRWa2IxMnZMRi12NEphUk8wWWZXdVVrdjhoaG5B0gHEAUFVX3lxTFBCUk9yUjJkNHFJNmJ0VHNKZ0J2M1RNWUN3TVZNSWdGZkNheTZIRlg4a3hRcm92SmFlZEZsVnRWWDduUE1MWkZZU2pYNEYwdmY5QkZXX3c4MmgtbTMwUm0zMGdfYWxVYkhIdE9MVFZvcVBkWmw4TGd6Q1ZTTUhITjFZM0pZT19UQmV1UFVKRHBqUDEtRTItTUhXN3B3T2NPOXlNczAxWUVFRXZiMkE1RlZJdVR3OWVxUEtuMTVHMUFtNmdjamw",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-what-is-glm-5-2-china-s-latest-open-weight-ai-model-turning-heads-in-s",
          "image": "https://pixabay.com/get/g9987322bb2009fbd8d7a1719caf9bd1a1753823074d4ae149c5eb6b9ebadbc48b0b48f28a42c85f0a32ee6a2d58aaf808201d4a26fd9f4f58518106628cd6463_1280.jpg",
          "image_kind": "photo",
          "image_credit": "51581",
          "image_credit_url": "https://pixabay.com/users/51581-51581/"
        },
        {
          "hour": 14,
          "time": "14:05 IST",
          "headline": "India needs its own DeepSeek or risks dangerous dependence on US AI models, Bernstein warns",
          "what": "Global research firm Bernstein has warned that India risks becoming dangerously dependent on US-developed AI models if it does not invest in building indigenous large-scale AI capability comparable to China's DeepSeek. The report argues that without a homegrown frontier AI effort, India's critical sectors — from defence to finance to healthcare — could become structurally reliant on foreign technology whose alignment, access and pricing are outside Indian control. Bernstein's framing positions AI sovereignty as a strategic necessity, not merely a technology aspiration.",
          "lens": "Bernstein's warning that India could become a captive market for US AI — like it once was for enterprise software — is a direct challenge to Indian policymakers and tech investors to fund a serious domestic AI push now.",
          "source": "Moneycontrol.com",
          "url": "https://news.google.com/rss/articles/CBMi3wFBVV95cUxPUWRsU0ZfM3hHZ05OWVhod29hQ1ZjOWVOeDJFRElVOXBITk15UU00eGtuRVdET1NXamlwVkJXZzVpQ3hhQkpyUGV0TEd6OXhUXzRRR0VxNFdYZGstdFdGZURlbGVlVTFzaXdvZjFaRHBZMXdtVGlyT2hNYmJ5akJ2Nkg1US14RzhLeFJqMWM3OERxSFNvd29GYk9mTm0zV0kyUEN0bFhjcWhDYmVYTnZvU0M3NE55WlM5Rl9rakUzdE5YdmpCcGJtaWkxY2VJOGR5YVlTbTJ4RlcxMUVKSVpR0gHkAUFVX3lxTE1hMVVRdHVnSmpod1YtakxjWE12TV9UdGVaRFYzelFMX0tqcHA1ckFWRV80TnZwRFVlbm9yZjBWZ3pSTHpJazNWWndOQndUMzVfNk0xWmtmcHR2MjVpR3pUQms4YWdIVk1UbmpFakhVa0xQNEFIMi0tUmtjYUFCVTdLclFHMmFVSzNIeTFqeGNVMGZFd0pJdnhSYmNyQXlua3diTHBOdzVzZ3BqTnRralRmNDRvWE12LTMyaHNOXzJHMmlLTl80NVNGQmx5c0ZBd3JUdVIxaW9FY25JOURLMXBDTXpqTQ",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-india-needs-its-own-deepseek-or-risks-dangerous-dependence-on-us-ai-mo",
          "image": "https://pixabay.com/get/g843a4cdfa7b2049244cd616cc17da64ea28b0f9521801190536d56de01935fcbcd89ae82c3ebaf250f76113d161a95b37e44013503022a4d66a6356cc3f842f4_1280.jpg",
          "image_kind": "photo",
          "image_credit": "geralt",
          "image_credit_url": "https://pixabay.com/users/geralt-9301/"
        }
      ]
    },
    {
      "id": "sports",
      "name": "Sports",
      "stories": [
        {
          "headline": "FIFA World Cup 2026: latest scores and full results",
          "time": "00:16 IST",
          "hour": 0,
          "what": "The latest FIFA World Cup 2026 results in full — scorelines, goalscorers and what's coming up next, all in IST.",
          "lens": "Every matchday, tracked in your time zone.",
          "source": "openfootball",
          "url": "https://thelast24.in/worldcup.html",
          "breaking": false,
          "worldcup": true,
          "slug": "20260622-fifa-world-cup-2026-latest-scores-and-full-results",
          "image": "https://pixabay.com/get/g3cca154562fda6a00e5a62301d31b40627f892775fd1bdadbf904ce00ceef378b9932074c065af242a283e6f757dd57dcc4560bc1b2e12bd81fdc01f64aa3cd0_1280.jpg",
          "image_kind": "photo",
          "image_credit": "jorono",
          "image_credit_url": "https://pixabay.com/users/jorono-1966666/"
        },
        {
          "hour": 22,
          "time": "22:30 IST",
          "headline": "Women's T20 World Cup: India's fielding woes resurface again",
          "what": "India's fielding frailties came back to haunt them during the Women's T20 World Cup, with missed chances and lapses in the field again threatening to derail what could otherwise be a competitive campaign. The persistent nature of the problem — described by Hindustan Times as having 'resurfaced again' — suggests the issue has not been adequately addressed between matches. Fielding has been a recurring Achilles heel for the Indian women's side in major tournaments.",
          "lens": "Poor fielding has cost India crucial wickets and matches in previous Women's World Cups — if it keeps recurring in this tournament, it could be the difference between a podium finish and an early exit.",
          "source": "Hindustan Times",
          "url": "https://news.google.com/rss/articles/CBMiugFBVV95cUxNbzZycklNVUY2Ml9zOHlNejN1STR0NUpfLXhWMjVPNW9nTExneXRtbC1rSjM2dWlaZ1A1VU52NUFBc201SFlrNDBJclUyY0s4T004TjdkamcxQmlZUzBuZ1VoMnN6ZzBRd1dOOEtNVlYwSW5MMk1DTi11Z1pQTUxSdVJlVW92N1hMOHdqMXJlU3hheE54blBXTjNtWHZqbFBEMXNfOW9oUlM1elNxODZBWmRaQ0tIREg4a2fSAb8BQVVfeXFMT3RPYTkyR2IwT3dmOXg1dG9xVGlfcFZoT1FOeFBHNGdBWWZud0dWbmROb0tkdWVfS1FPNTczdjVCeDBxREJNcWRMWWNtWmEtdHBJMUVGRENhMHZ2LWc0Q2hyVTNYU0NrbkRnWFhZWlRTSlNjdFQzZ21VNW5zYVQ4ejlOUjNSNFUzanZnTjV0S0tKUXVqQ1MtNUZlOWlmZk5GOFViSWNXeFVPeVlKcVRpMmw5R1pIWUk1X0dRZU1qaG8?oc=5",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-women-s-t20-world-cup-india-s-fielding-woes-resurface-again",
          "image": "https://images.pexels.com/photos/13509971/pexels-photo-13509971.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Sandeep Singh",
          "image_credit_url": "https://www.pexels.com/@usbofphotography"
        },
        {
          "hour": 22,
          "time": "22:00 IST",
          "headline": "Cocktail 2 grosses Rs 76.25 crore globally in three days at box office",
          "what": "Shahid Kapoor's Cocktail 2 has collected Rs 76.25 crore globally in just its first three days, according to box office tracking reported by The Indian Express. The film's strong opening weekend performance puts it among the better-performing Bollywood releases of recent months and confirms audience appetite for Kapoor's star-driven vehicles. The Day 3 collection figure suggests the film has sustained its opening momentum through the weekend.",
          "lens": "For Bollywood's commercial health, a Rs 76-crore global opening weekend for a Shahid Kapoor film signals that star-driven Hindi films can still draw large audiences — useful data ahead of a crowded summer release schedule.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi-gFBVV95cUxPaUhqM01pX0lZblVwRVVzME8wMFBhX1JLZGV6U29yLXFleFgtSXV3c3Zqd3ZkWi1BRklnS2s2cHlGdVNVMmVKX0FwdGhNaVphWVdKblpYb240aVpEXzEyaUNnVEpFZHBfUkFtakNTaVFoQjREM0pZajRmNzVNY1htR2VMVXZYRC1kZmFFQWlVNU5aMXgyRzA0eHR0c29YMllwUGJKY0xOdjZZdl8tdWxVMDRtazZTcnFUQVk1Q0FSOWk3T2d2a1ljaE5CTy1YSUFhSjdtZVhlZ0NTQk4yYWNvMXhIZTAyXzBIVEVZTGFGNjd4cVdVUE51aGdn0gGAAkFVX3lxTE9pcEE1NkNvYmx0ZkNZZDlVd05IMHItNDBBWTEtd1M1QlFHZlZoUldSaWM2ZlFNTUJPRkw0azRnN0tSNFJicThQWF8tYV9UU0hGc09HazA0TjBXTDhSbFljeUctTUpEMTVCUEVGaDhoTktod2l2RjE0QkRzeDVmNjRCY08wS2hiZTlqNUtxSWhMN3NodG1tMTNPT3U4ZW9mM2JnVUhFcWhIQUxOUkVSUklrR1pMRmZPZUdDTmRiRkRXeWQ3U3VYVW1ic1lGelFYY013SERBeGwyVHdYLW9HdUZDam9xV2xOTnBxSGxQZE9mWFJLX0EzRzRYQy1zNVFnMWU?oc=5",
          "breaking": true,
          "_hot": true,
          "slug": "20260622-cocktail-2-grosses-rs-76-25-crore-globally-in-three-days-at-box-office",
          "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Shahid_Kapoor_at_Bloody_Daddy_launch_%28cropped%29.jpg",
          "image_kind": "photo",
          "image_credit": "Bollywood Hungama / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Shahid_Kapoor"
        },
        {
          "hour": 21,
          "time": "21:06 IST",
          "headline": "Manav Suthar follows dream Test debut with stunning five-wicket haul in England",
          "what": "India's emerging spin sensation Manav Suthar has followed up a memorable Test debut with a five-wicket haul in England, cementing his status as the national team's most exciting new spin prospect. The left-arm spinner's performance in England underlines his rapid rise through Indian cricket and suggests the team has found a dependable spinning option for overseas conditions. The feat drew widespread praise from cricket observers.",
          "lens": "India has long searched for a quality spinner who can take wickets in England's seaming conditions — Suthar's five-for suggests the selectors may have found their answer just in time for the Test series.",
          "source": "Hindustan Times",
          "url": "https://news.google.com/rss/articles/CBMi-AFBVV95cUxPdURjd0FtUFBhWnJ6UTRqTVd5TlZiTXNtNUg0d1gxQ0p4a21TNGZQWE9jellOVmJGTEJIX2VveFFnLUV4RVBZdzc3dUxEX24xYnQ3dTN3TElMU3dRbWxfTFhKM19xaHJncWUtNWg0c1JNYVNBRWRFN0pJci16eXJkaHR5WUttMjRia2l3MldwR0xiN3ZHWHRnLVQtY2dVNDZkNm5HSTVxaHRYY2FyY2kwZWhWdDFVeDhxNnN4R0tIZW93YXpsVDQ3bDNmaFZzU0dLdzlRcVgxREpPbE9jR2s0dU0wU3drZjRJVGlZRW5nMEpxaHdOQS0xT9IB_gFBVV95cUxPTlNtZDZlX0diT2JlRHRNcW1wQko1UjRHcm93VnBudHRYb3lDaU1zRU9tQktuUmpqalRnTWNpTnVURUVDWWtZMjBGNVNtNVJSa0pwUW11NElhRmZNcmJvNDNZTlFlUGlTM0RraHhEb0tOTVZ1UUNMUEhsWnBCcGZFbU5lZkJUaU1MMVRQeERsY0pIUi00S1Jxc1NSbVV4c0cwdFZnd0s2M242QzZhRjZtSGZ2S2xqYklDRTBDNVQ3bWhkbjJpdXpUZVVwSUx5ZlFqdUI2TlhGQ3B2Y0U1ME9rU3l6SjZYX3d4aWljVUthalZsM25QSElTOGI0MXlOUQ?oc=5",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-manav-suthar-follows-dream-test-debut-with-stunning-five-wicket-haul-i",
          "image": "https://pixabay.com/get/g847b3cb5980265aa8e9ac628f2fc5bebba64eb3c03f347f54fc34967e0d8c01f198ebf134952783ff897e6e2dc6fd2f7204c55f42cbf72fac3e935b398e0be44_1280.jpg",
          "image_kind": "photo",
          "image_credit": "shents",
          "image_credit_url": "https://pixabay.com/users/shents-941341/"
        },
        {
          "hour": 21,
          "time": "21:28 IST",
          "headline": "Lorcan Tucker named permanent Ireland T20I captain ahead of India series",
          "what": "Lorcan Tucker has been appointed as Ireland's permanent captain in the T20 format, with the announcement coming directly ahead of Ireland's T20I series against India. The wicketkeeper-batter takes on the role on a full-time basis, giving the Irish side some leadership continuity as they prepare for what will be a high-profile series. Tucker had previously led Ireland in an interim capacity.",
          "lens": "For Indian fans, Tucker's permanent appointment signals Ireland are serious about their preparations — and gives India's T20 squad a clear opponent to plan against in what could be a closely contested series.",
          "source": "BBC",
          "url": "https://news.google.com/rss/articles/CBMiZkFVX3lxTE5GSHE2ZXFCd0lUbjdvUjVBZWhyVDdXN0pIRmJjaEhIcW00cnJOM3FkSW8yTXpEVU1qZmYtX0R4NjBrV2g2azNGd2txQ3VKRGJDR0RYcTFIZXFHRVhxYUlmN19ZVUFEUQ?oc=5",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-lorcan-tucker-named-permanent-ireland-t20i-captain-ahead-of-india-seri",
          "image": "https://images.pexels.com/photos/30387507/pexels-photo-30387507.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
          "image_kind": "photo",
          "image_credit": "Lorien le Poer Trench",
          "image_credit_url": "https://www.pexels.com/@lorien-le-poer-trench-2148896580"
        },
        {
          "hour": 18,
          "time": "18:50 IST",
          "headline": "Kieron Pollard breaks Chris Gayle's T20 record, apologises to 'Universe Boss'",
          "what": "West Indies cricket legend Kieron Pollard has broken Chris Gayle's long-standing T20 record, prompting an affectionate public message to Gayle — nicknamed the 'Universe Boss' — in which Pollard said 'Sorry, Universe Boss.' The record, which relates to T20 appearances or runs at the top level, had been held by Gayle for years and was considered one of the most durable landmarks in the shortest format. Pollard's message reflected the mutual respect between two of West Indies cricket's greatest T20 players.",
          "lens": "Pollard surpassing Gayle's T20 record is a landmark moment in cricket history — it marks the passing of the torch between two giants of the format that India's IPL helped make globally popular.",
          "source": "The Times of India",
          "url": "https://news.google.com/rss/articles/CBMijAJBVV95cUxPclRpYzVaZ1c4RlZSZklHY1pGRmszclJnZ0RzX2dYNjdrYXpaNmZUX3RKeVBCMWo2dVBTSEJQVThkWDYxZS1TMUNaRENVU3p2bGVQNWFKa2NtWUUwMV9zV21BZzFoUVQ1MWVjczhtWDdKTEszVDNuNm1iNjMzMmNFd1pSRDNwUUZndHBWNGkwNlRZN3JrLWlFVTh3bTBPWnhRVDdCOHJVWU1hcmpyZThyMjVRNDlQdEVNX0NsVU9kMU1KcmJxdmxnWHZ6aEpXZXFUekdaWlpEZkRxLV9GTkJNZUtQckdlclFrbWFBc1ZCLVh1eWYwcTNBQjNTX1dnZ3dKeUxxNUltSUdRT1Aw0gGSAkFVX3lxTE4zWG9oTHdTTk1qWXJNWTlnUHlKYnltWVRCaEtSenZTNU0yMGdCcWp1dWpRcjZoajRKN1AyX3BQVW5fUlpSb21pQ0lJNVg2TmswaUotd0dTQkJMX2tBaE1oU1BOX2VCS1hWYl9zQXB6MnB0RldLRllTUENvZUlJcHZrYjhzR3hJTmh6bVQzcktFMXZSa0h0elJsSGxhN0hnNURYU2l4UkxuLVBqUU1DNEdxVFFxUnhHUlg0RHhKLWdKdzNPeVBOc3dPX0JOQk5QLVl6dEpXT1lpektWM05YWHpPdXJ4X1hmRTZMU3FOLXFSbkk1eVUtZE9hbHgtS2VIZnNyVTVpMVJZNm5NU1B3MklRMkE?oc=5",
          "breaking": true,
          "_hot": true,
          "slug": "20260622-kieron-pollard-breaks-chris-gayle-s-t20-record-apologises-to-universe",
          "image": "https://upload.wikimedia.org/wikipedia/commons/7/7d/Kieron_Pollard.jpg",
          "image_kind": "photo",
          "image_credit": "Adelaide Strikers / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Kieron_Pollard"
        }
      ]
    },
    {
      "id": "entertainment",
      "name": "Entertainment",
      "stories": [
        {
          "hour": 22,
          "time": "22:00 IST",
          "headline": "Cocktail 2 Crosses Rs 76 Crore Globally in Three Days",
          "what": "Shahid Kapoor's Cocktail 2 has grossed Rs 76.25 crore at the global box office in its first three days of release, setting a strong pace for a mainstream Bollywood commercial entertainer. The collection marks one of the more robust opening weekends for a Hindi film in 2026, underscoring continued audience appetite for star-driven theatrical releases. The film's performance will be closely watched as an indicator of whether post-pandemic box office momentum is consolidating.",
          "lens": "A Rs 76-crore global opening in three days signals that big-budget Bollywood releases with established stars can still reliably pull Indian audiences back into cinema halls.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi-gFBVV95cUxPaUhqM01pX0lZblVwRVVzME8wMFBhX1JLZGV6U29yLXFleFgtSXV3c3Zqd3ZkWi1BRklnS2s2cHlGdVNVMmVKX0FwdGhNaVphWVdKblpYb240aVpEXzEyaUNnVEpFZHBfUkFtakNTaVFoQjREM0pZajRmNzVNY1htR2VMVXZYRC1kZmFFQWlVNU5aMXgyRzA0eHR0c29YMllwUGJKY0xOdjZZdl8tdWxVMDRtazZTcnFUQVk1Q0FSOWk3T2d2a1ljaE5CTy1YSUFhSjdtZVhlZ0NTQk4yYWNvMXhIZTAyXzBIVEVZTGFGNjd4cVdVUE51aGdn0gGAAkFVX3lxTE9pcEE1NkNvYmx0ZkNZZDlVd05IMHItNDBBWTEtd1M1QlFHZlZoUldSaWM2ZlFNTUJPRkw0azRnN0tSNFJicThQWF8tYV9UU0hGc09HazA0TjBXTDhSbFljeUctTUpEMTVCUEVGaDhoTktod2l2RjE0QkRzeDVmNjRCY08wS2hiZTlqNUtxSWhMN3NodG1tMTNPT3U4ZW9mM2JnVUhFcWhIQUxOUkVSUklrR1pMRmZPZUdDTmRiRkRXeWQ3U3VYVW1ic1lGelFYY013SERBeGwyVHdYLW9HdUZDam9xV2xOTnBxSGxQZE9mWFJLX0EzRzRYQy1zNVFnMWU",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-cocktail-2-crosses-rs-76-crore-globally-in-three-days",
          "image": "https://upload.wikimedia.org/wikipedia/commons/2/25/Shahid_Kapoor_at_Bloody_Daddy_launch_%28cropped%29.jpg",
          "image_kind": "photo",
          "image_credit": "Bollywood Hungama / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Shahid_Kapoor",
          "carried": true
        },
        {
          "hour": 18,
          "time": "18:47 IST",
          "headline": "'Peek In, Peek Out': New Documentary Brings Delhi's Khirki Village Migrant Story to Screen",
          "what": "A new film titled Peek In, Peek Out, set in Delhi's Khirki village, brings the story of India's internal migrants to the fore, according to The Indian Express. Khirki, a dense urban village in South Delhi, has long been a transit and settlement point for migrants from across India and parts of Africa, making it a microcosm of the country's complex urban demographic shifts. The film's release marks a rare instance of Indian documentary or indie filmmaking training its lens on an often-overlooked neighbourhood and its residents.",
          "lens": "India's internal migration story is one of the defining socioeconomic realities of our time, and films that humanise it beyond statistics fill a genuine gap in the national cultural conversation.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMioAFBVV95cUxORFlOTDl3RXdNTTR3eDVqQ3V2X19iM3FUbGVrN1FsaGZpRWRhNUlIZVdTUnlMREVvNG9KNWNjYmR4LTRkVExzT0RDZXJ2RkxDb1pQeXh5ME42VXVpS2hNc2Z2RklLaWhqTFVvRHZhU0lUNk5NaHM5M2tFaGJNQ3YtbTcwVHpLaTFTbzFRZlVlcFJxRW5oa2lZTkdGQWY0QUQ20gGgAUFVX3lxTE5EWU5MOXdFd01NNHd4NWpDdXZfX2IzcVRsZWs3UWxoZmlFZGE1SUhlV1NSeUxERW80b0o1Y2NiZHgtNGRUTHNPRENlcnZGTENvWlB5eHkwTjZVdWlLaE1zZnZGSUtpaGpMVW9EdmFTSVQ2Tk1oczkza0VoYk1Ddi1tNzBUektpMVNvMVFmVWVwUnFFbmhraVlOR0ZBZjRBRDY",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-peek-in-peek-out-new-documentary-brings-delhi-s-khirki-village-migrant",
          "image": "https://upload.wikimedia.org/wikipedia/commons/e/e7/Main_south_entrance.jpg",
          "image_kind": "photo",
          "image_credit": "Varun Shiv Kapur / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Khirki_Mosque",
          "carried": true
        },
        {
          "hour": 12,
          "time": "12:25 IST",
          "headline": "Ten Korean Dramas Are Dominating Indian Streaming Right Now",
          "what": "A new India Today report highlights that ten Korean dramas are currently among the most-watched titles on streaming platforms in India, reflecting the sustained and deepening grip of the Korean Wave — or Hallyu — on Indian entertainment consumption. The phenomenon, which accelerated sharply post-pandemic with titles like Squid Game and Crash Landing on You, has now matured into a consistent content category that Indian streaming services actively programme for. The trend has significant implications for both Korean content exports and Indian platform strategy.",
          "lens": "Korean dramas pulling in Indian viewers at scale means Indian streaming platforms are dedicating real shelf space and subtitling budgets to foreign content — reshaping what 'mainstream' Indian entertainment looks like.",
          "source": "India Today",
          "url": "https://news.google.com/rss/articles/CBMi1wFBVV95cUxQS1lJSnlyMUlDM0tMZ2Izb2MxN3c3QnZwVzlMVlhVb0hINDN1NVNNMVozWnR3elhoVWlhVjlMbmJ3WlVEQno4X2ExSDFaU3ZtWDRTRDhaOU95eC1nVnJiamdxQ05UQ2tiVjhyV05ZLXphX05ZSzAtU3FQNnJ6NzRHU3pVZHlKT3lkVnRoMm1UX01IaE5vSS1ZT2E5QWRlVms1a3F5TXFlTEgwMTRvYzB4R2pzNFFxN0tkdWRGTGlSb3Eyd0otU0puZi1MaUN2ajNOUy1INVI2aw",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-ten-korean-dramas-are-dominating-indian-streaming-right-now",
          "image": "https://pixabay.com/get/gcdda807ed444cebb7d01b8c43cf871e9d95509cc11aea4cab13887bbc891059ddd138acc6ac54926141608456becb1606a78c39ddc3391b5eb936abbf31822e2_1280.jpg",
          "image_kind": "photo",
          "image_credit": "Tumisu",
          "image_credit_url": "https://pixabay.com/users/Tumisu-148124/",
          "carried": true
        },
        {
          "hour": 9,
          "time": "09:45 IST",
          "headline": "Mukesh Khanna Collaborates With Samay Raina After Publicly Calling for Him to Be 'Paraded on a Donkey'",
          "what": "Mukesh Khanna, best known for playing Shaktimaan in the iconic Doordarshan series, has collaborated with stand-up comedian Samay Raina — despite having previously and very publicly declared that Raina 'should be paraded on a donkey' for content he found disrespectful. The about-turn is striking given the vehemence of Khanna's earlier criticism, and has set off considerable chatter about the nature of celebrity feuds and reconciliations in the social media age. The collaboration was reported by The Indian Express.",
          "lens": "The Khanna-Raina patch-up is a snapshot of how quickly public feuds between old-guard TV icons and new-age digital comedians dissolve when both sides see mutual benefit — a dynamic that defines Bollywood and entertainment PR today.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi9AFBVV95cUxPZnlBQjdlX0poVFprUEVWZlhzc2VkZjR0ZUlFbmxiSVpfVFpObFZJYnV1dWtDeTByaW1CMlkwRjRfVzUyVHpibEQ4STdPUVFGUWdWYUl0RjNET193NWlfNkJWNXp2RHlDTTZtY2FET3pNUVpkei1vV3ZuX0tFR2ozZjJoRy15eE8zUWJVTXQyeWRRVFZ6ZWlQc0VZeTZPNGdvQ3Nsb2U0SXhCa0dnODhfSkR6NUFHOUpBaXRTRU9sSi0xbUtISWpIS3JwUDNMQVZDNVQ4dF9KMmdpZ3hCX1R2bGxHR2FDeTFRWFM5MnYtd1d0d0530gH7AUFVX3lxTE1uNXJWYXMwV1FOWGtiLVZtdnltTF9nUElxTW13d0hoUTJBRC1vcGFVUlViTlRLOW1sXzBOejFpMGJIdDBPUXZyVVJtUDZmNG1QNG1yUWhMblhFa3BwdE9GQktVcURJTFczR2Q3ZUY5cGNTS0o5MlBwdFN0TVh4NTRNV2NHRTVtMHBQQ2dwZElTRG5rX1A0S2VvZmhmbDlkc3pLbEUwOFpvbEJsdS1VbnZDVnY2aXVFZWZTNEJ6d0NDbFd2MEkxQ3htUFA0aXpzRHdwNWJqYWd2U0VtczhweVZlYVd3QWFjZ2VOWFR5U2UzRDB2cW1oLTVWX2VB",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-mukesh-khanna-collaborates-with-samay-raina-after-publicly-calling-for",
          "image": "https://upload.wikimedia.org/wikipedia/commons/d/de/MukeshKhanna.jpg",
          "image_kind": "photo",
          "image_credit": "Bollywood Hungama / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Mukesh_Khanna",
          "carried": true
        },
        {
          "hour": 9,
          "time": "09:49 IST",
          "headline": "Why Agent Vinod Is Sriram Raghavan's Most Fascinating Failure",
          "what": "The Indian Express has published a retrospective examination of Agent Vinod, the 2012 Saif Ali Khan spy thriller directed by Sriram Raghavan, arguing that it remains his most fascinating failure — a film that overreached its own ambitions but in doing so revealed something distinctive about Raghavan's filmmaking sensibility. Raghavan, who went on to craft the widely acclaimed Andhadhun (2018) and Merry Christmas (2024), has always operated at the intersection of pulp and precision. The piece revisits why Agent Vinod fell short commercially and critically despite its director's evident craft.",
          "lens": "Reassessing a director's misfires is how Indian film culture develops critical depth — and for a filmmaker of Raghavan's stature, understanding Agent Vinod illuminates everything he made after it.",
          "source": "The Indian Express",
          "url": "https://news.google.com/rss/articles/CBMi3gFBVV95cUxQc0dOc2U4QU10TjM0ZGlWZG93T0xoajBtVjlVd2EwdVZqRFl2T3EyZVF1bm9IekJ4eUFpTWpjU3YwOWFVZmE0UmpVMGdseC11MF9KMmpqM0Zjc0Vsa29NRkNfbW9HamlaZXBQRnhDaUZPQ1p0M3pSdmhGclpmSEoybXhEUlBkTFBkMmZSNkxMLURGZ19Rbmk1SVpLdERDd29uU2JtRG5ndWNzbnlPejN4WEVsWmFwQjk5UW54VmdoWW5CMnlsWE5qMGlNblZQblBEQi1QZkVTSzlyYl9KQUHSAeQBQVVfeXFMT0ZVaUIzbHdmS215Y2x0N3NmazVuX2pKc1Y4M3g3WkdmSzdvWFY2eWk1c2psRDlheVNDd29kSno2QTRySERycjhXaHBndXo2ZVllOXRaTDZpaUJfTE4yS3RURVB2eDdRVXp5bjlaWXItZzN0SWpEVnpxNGR4SV9mcURnblBMV3NmbDhrMFFFRngzc1FYaW4xRVp5d2ZVU3JyMmhFb0tNOU5TcXVjOFFSZi0xUWZHa2V1WElIWE9MMGpLSnRhMk5idFo0cm5NZjczQ05KQTRPYk9Sdk9hZ0N2bnV4eXJi",
          "breaking": false,
          "_hot": false,
          "slug": "20260622-why-agent-vinod-is-sriram-raghavan-s-most-fascinating-failure",
          "image": "https://upload.wikimedia.org/wikipedia/commons/6/62/Sriram_Raghavan_at_News_18_Reel_Movie_Awards_2019.jpg",
          "image_kind": "photo",
          "image_credit": "Bollywood Hungama / Wikimedia Commons",
          "image_credit_url": "https://en.wikipedia.org/wiki/Sriram_Raghavan",
          "carried": true
        }
      ],
      "carried": true
    }
  ]
};
